### PR TITLE
PHP 5.6 - minimum required version

### PR DESCRIPTION
**Pull request by AgelxNash**
### What does it do?
Minimum required php version. Synchronization with composer.json

### CODE REVIEW

**Comment by AgelxNash** [comment]
Also security reason https://www.youtube.com/watch?v=zmrqC2_XB_U

**Comment by mrhaw** [comment]
Not in any way a solution, but a quick fix:

RewriteCond %{QUERY_STRING} (.*)(http|https|ftp):\/\/(.*) [NC,OR]
RewriteCond %{QUERY_STRING} (.*)50738585072011(.*)
RewriteRule ^(.*)$ http://www.google.com [R,L]

// https://www.exploringbinary.com/php-hangs-on-numeric-value-2-2250738585072011e-308/

**Comment by JoshuaLuckers** [comment]
Since this is targeting `3.x`; do we really want to suggest PHP 5.6 as minimum required version?

**Comment by alroniks** [comment]
Yes, because statistics says that over half of websites still work on PHP 5.

**Comment by JoshuaLuckers** [comment]
By the time 3.x is released PHP 5.6 will be End of Life and not receive any (security) updates. A new major release would be a good reason to also increase the minimum required PHP version to a version that is still supported.

**Comment by alroniks** [comment]
It was discussed many times already. It will be increased when it will be required by the code.

**Comment by AgelxNash** [comment]
This PR is not critical for such a long discussion. Just merge or reject and we continue to work, not to talk.

**Review by alroniks — APPROVED** [review]

**Review by Mark-H — APPROVED** [review]

**Comment by Mark-H** [comment]
Thank you @AgelxNash!

**Pull request merged**
