### PR TITLE
 Add icons to elements in elements tree

### PR DESCRIPTION
**Pull request by Ruslan-Aleev**
### What does it do?
Add icons to all elements (chunks, snippets, TV, etc.) from parent category instead of an empty icon.
Changed class 'icon-file-o' to correct 'icon-file-code-o'

### Why is it needed?
The icon of the element will make it easier to navigate in the element tree, especially if it is large.

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/issues/14001

### CODE REVIEW

**Comment by Ruslan-Aleev** [comment]
@jonleverrier Hi, I sent a PR, can you test it? :)

**Review by JoshuaLuckers — APPROVED** [review]

**Comment by Mark-H** [comment]
Hey @Ruslan-Aleev - have you signed the CLA before? I can't seem to find your username to double-check.

If you haven't yet, please sign it via https://develop.modx.com/contribute/cla/ and let me know. Thanks :)

**Comment by Ruslan-Aleev** [comment]
@Mark-H Hello! CLA I signed.

**Comment by Mark-H** [comment]
Thanks @Ruslan-Aleev!

**Review by Mark-H — APPROVED** [review]

**Pull request merged**
