### PR TITLE
Fixed steal processor 

### PR DESCRIPTION
**Pull request by Semdevmaster**
### What does it do?
Fix missing scriptProperties array

### CODE REVIEW

**Comment by Ibochkarev** [comment]
@cla-bot check

**Comment by Semdevmaster** [comment]
@cla-bot check

**Comment by JoshuaLuckers** [comment]
@Semdevmaster thanks for taking time to help make MODX better! For future reference, did you encounter a specific issue this might solve (except the logic issue in the code)?

**Comment by Semdevmaster** [comment]
> 

During the data import process, I needed to intercept possible resource locks so as not to receive resource update errors. But this processor always returned an error. The problem turned out to be that the required array containing the input parameter was simply not declared in the processor. After adding the fix - everything worked as it should.

**Review by opengeek — APPROVED** [review]

**Pull request merged**
