### PR TITLE
Resolves #12578

### LINKED ISSUE #12578: Add title of edited resource to Manager Log
Before 2.4.x the Manager Log included the page title of an edited resource:

screenshot 2015-08-22 14 10 11

Now in 2.4.x the log just includes modResource for every update:

screenshot 2015-08-22 14 10 33

In my opinion its more useful to include the page title so a site admin can quickly know which resources have been modified without having to look up the page in the Resource tree via the ID numbers.

### PR DESCRIPTION
**Pull request by zaigham**
### What does it do ?

Add resource title in Manager Log, for edited resources.
### Why is it needed ?

The resource title was missing, and was only showing ID and the class_key
### Related issue(s)/PR(s)

Fixes #12578.

Special Thanks goes to @Mark-H :smile:

### CODE REVIEW

**Comment by Mark-H** [comment]
@zaigham could you please follow the template from https://github.com/modxcms/revolution/blob/master/CONTRIBUTING.md#submit-a-pull-request for this one?

I know what this does and why it does it because we discussed it on Slack, but others (or one of us in six months time) don't have that context, and the commit message, along with the pull request is an important piece of that history that helps make sense out of things now and in the future.

**Comment by zaigham** [comment]
@Mark-H My bad on not following that template.

Is it enough to edit this PR or you want me to add that tpl into commit message itself? Thanks.

**Comment by Mark-H** [comment]
Just the edit is great, thanks.
Op 10 sep. 2015 1:12 AM schreef "Zaigham Rana" <notifications@github.com>:

**Comment by theboxer** [comment]
Merged to 2.4.x

**Pull request closed without merging**
