### PR TITLE
Fix for displaying SVG in media browser

### PR DESCRIPTION
**Pull request by marcjenkins**
### What does it do?
Displays SVGs in the media browser.

### Why is it needed?
SVG's weren't being displayed as they were being processed by PHPThumb.

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/issues/12459

### CODE REVIEW

**Comment by sonicpunk** [comment]
#modxbughunt #3points @marcjenkins

**Comment by rtripault** [comment]
Thanks for that (not tested yet).
I believe this should go against 2.x branch instead.

Also i guess the default `imageExtensions` propertiess should be updated too in relevant media source classes

**Comment by gpsietzema** [comment]
Just tested this @marcjenkins - It does show a preview now, which is awesome! But is it possible to have the SVG fit within the thumbnail area. It looks a bit weird now:


screen shot 2017-07-07 at 17 30 20

**Comment by rtripault** [comment]
Just tested and we indeed see some svg preview!
However there appears to be no resizing. In my case, the svg was wider than the thumbnail width, and i only get a small portion of the svg

**Comment by sonicpunk** [comment]
#modxbughunt #1point to @rtripault

**Comment by sonicpunk** [comment]
#modxbughunt #1point to @gpsietzema

**Comment by OptimusCrime** [comment]
Wow, really nice PR! I looked at this once, and I found that handling SVG resizing was far more complex than I initially thought.

**Comment by labr1005** [comment]
I would either need some help with Git or you just add this to _browser.scss

```css
.modx-browser-thumb img[src$=".svg"] {
    width: auto;
    max-width: 100%;
    height: auto;
}
```
bildschirmfoto 2017-07-08 um 12 25 16

**Comment by OptimusCrime** [comment]
Oh. Is it really that simple? 😮 

@marcjenkins Could you put this code in, or do you want me to PR your fork?

**Comment by rtripault** [comment]
Also, as first time contributor, would you mind signing the [CLA](https://develop.modx.com/contribute/cla/) ?

Many thanks!

**Comment by labr1005** [comment]
Do we care about IE and if so, from which version on up? The problem with svg in general is, that the width and height attributes are optional. So it may look distorted in IE.

**Comment by labr1005** [comment]
@marcjenkins I'd thought that you would leave max-height: 80px; in place...

**Comment by labr1005** [comment]
@OptimusCrime Well, that's the best thing you can do with pure CSS.

And we're not done here, because then we'll also need to take care of TV previews for example.

bildschirmfoto 2017-07-08 um 17 03 03

The best solution for browsers would be to convert the Svg to Png for the previews. Some browsers still like pixels more than something that has "no size". I think that conversion can be done with imagick.

Another option would be add width and height attributes to the previews img tags in the manager (and then do some CSS adjustments). I'm currently looking into JP's mediamanager and how he extracts the width and height of Svgs...

**Comment by Mark-H** [comment]
Not sure if converting SVGs to a bitmap format is really the best solution. SVGs have a pretty solid 97.67% support, so that's not really the problem... phpthumb just doesn't know how to handle them, so the TV previews will need to use the raw SVG source instead of a phpthumb call.

**Comment by labr1005** [comment]
@Mark-H I agree. "best solution" was the wrong wording and I was talking about the thumbnails only. The problem: It's basically impossible to proportionally scale and center a svg using an img tag into a container that has a fixed width and height with pure CSS... in IE. :) The other browsers figure out what to do, of course. But I'm currently working on that.

**Comment by labr1005** [comment]
Here's my current status - working also in IE as you can see - and I look forward to your opinion and have some questions.

bildschirmfoto 2017-07-09 um 20 31 22

1.) What do you think of the checked background for transparent images?

2.) Until now the thumbnails and the preview did not reflect the image's original proportion - now they would. Do you agree?

(Kinda hard to describe in not my mother language. In the example above the apple preview would have more space to the left and right and it would look the the original image is landscape and not portrait.)

3.) In modfilemediasource.class.php and mods3mediasource.class.php I find some calls to get the system settings "filemanager_image_width", "filemanager_image_height", "filemanager_thumb_width" and "filemanager_thumb_height".

But these system settings are not set on a fresh install. And looking through the repository it looks to me that these are the only files where they are tried to be read, correct?

Besides, the width and height for the thumb for example are fixed set to 100px x 80px in the CSS…

Do you know of anybody who's ever altered these settings? IMO they don't make any sense for the preview anyway. For the thumbnail, ok - could make sense.

Option 1: Get rid of the system settings.

Option 2: Make the system settings really work (for the thumbnails).

**Comment by OptimusCrime** [comment]
That looks really, really good!

**Comment by Mark-H** [comment]
Any objections against this PR getting merged into 2.5.x so we get SVGs in the tree, and worry about the TVs in a next one? 

@labr1005 some of your questions are probably better in a new issue... unless you are planning to send a PR with some of your improvements?

**Comment by OptimusCrime** [comment]
No objections here.

**Comment by labr1005** [comment]
Objections if you care for IE and Edge. But you can merge this now and I'll send a PR in a couple of days.

**Comment by Mark-H** [comment]
Looking forward to your PR then @labr1005 ;)

**Comment by opengeek** [comment]
Is this good to be cherry-picked into 2.x for 2.6 release?

**Comment by gpsietzema** [comment]
I think so!

**Comment by rtripault** [comment]
@labr1005 does your PR (#13547) applies on top of this one, or would you need to send a new PR to apply the IE/Edge fixes ?

**Comment by OptimusCrime** [comment]
I can only reference what is already posted, but he said:

>Here's my current status - working also in IE as you can see - and I look forward to your opinion and have some questions.

**Comment by rtripault** [comment]
Thanks.

My understanding is that the other PR satisfies the same purpose as this one, with some additions (being IE/Edge compliant) and is not something that could apply on top of this one.

So i'd be in favor of using the other PR, albeit it would be a shame not to merge this once, since Mark spent quite some time answering our concerns/feedback.

If the other PR could be used on top of this one, then no issue (or if Lars is open to submit a new PR only with his additions).

Hoping that makes sense

**Comment by OptimusCrime** [comment]
I agree. Can @marcjenkins shed some light on what is left to do/not satisfied with this PR as it stand right now? I would love to see this feature in the next 2.x version of MODX.

**Comment by labr1005** [comment]
I will have to make some small adjustments to my PR - but I'm very fine with that.

So if you ask me: Please merge this one first.

**Comment by labr1005** [comment]
My new PR is ready for review.

**Comment by opengeek** [comment]
Merged into 2.x as 9e73dc474

**Pull request closed without merging**
