### PR TITLE
Add code quality GitHub Action

### PR DESCRIPTION
**Pull request by Ibochkarev**
### What does it do?
GitHub Action to run PHP_CodeSniffer of files changed in current PR or even on changed lines

### Why is it needed?
https://github.com/marketplace/actions/action-php-codesniffer

### Related issue(s)/PR(s)
NA

### CODE REVIEW

**Review by Mark-H — APPROVED** [review]
Curious to see how much issues this catches 👍

**Comment by Ibochkarev** [comment]
> Curious to see how much issues this catches 👍

After adding and check =)

**Review by alroniks — APPROVED** [review]

**Comment by alroniks** [comment]
But I have a question: where is phpcs.xml with rules? :)

**Comment by Ibochkarev** [comment]
> But I have a question: where is phpcs.xml with rules? :)

It can be added.

**Comment by JoshuaLuckers** [comment]
Is it just me or is the indentation for this file different from [ci.yml](https://github.com/modxcms/revolution/blob/c97dab98984e11b39f8e4a8783b1697e141a39c2/.github/workflows/ci.yml)?

**Review by JoshuaLuckers — APPROVED** [review]

**Review by theboxer — APPROVED** [review]

**Pull request merged**
