### PR TITLE
Fatal error

### PR DESCRIPTION
**Pull request by Fi1osof**
Fatal error: Cannot redeclare class modTemplateVarInputRenderText in /var/www/evakuator.ru/public_html/core/model/modx/processors/element/tv/renders/mgr/input/text.class.php on line 10

OR add if(class_exists) here: https://github.com/modxcms/revolution/blob/develop/core/model/modx/modtemplatevar.class.php#L420
like here: https://github.com/modxcms/revolution/blob/develop/core/model/modx/modtemplatevar.class.php#L445

### CODE REVIEW

**Comment by Fi1osof** [comment]
@TheBoxer @rthrash  Why it`s closed??? Problem still actual, People got fatal errors. We can not give another solution, because TV [will broken](https://github.com/modxcms/revolution/blob/master/core/model/modx/modtemplatevar.class.php#L449).
TV works not like MODx and does not do like [here](https://github.com/modxcms/revolution/blob/master/core/model/modx/modx.class.php#L1678).

**Comment by rthrash** [comment]
Hi @Fi1osof . @TheBoxer requested more feedback from you about a year ago on this; since it didn't come, it was closed I would guess—we can't keep what appears to be stagnant issues open indefinitely. We would re-open this since you're now able to provide additional information, but can't since the repository from which the PR was submitted was deleted (Github won't allow it). 

I know you have the skills to help fix this, so hopefully you'll submit a new PR to help do so, maybe with a little more explanation so the full scope of the impact is understood. Thanks!

**Comment by rthrash** [comment]
Hmmm … the close happened a few months after the PR was issued. Sorry if that created frustration for you. 

Can you provide more information in response to @pixelchutes' and @TheBoxer's comments/questions on your original PR, and re-submit it?

**Comment by Fi1osof** [comment]
@rthrash 
> @TheBoxer requested more feedback from you about a year ago on this;
I had wrong email here and was not recieve notifications :) 
OK, i will try now.

**Comment by Fi1osof** [comment]
@rthrash same solution (here)[https://gist.github.com/pepebe/7318178]

**Comment by Fi1osof** [comment]
@TheBoxer how can i send this PR again? File changes. Need create anothe PR?

**Comment by Alroniks** [comment]
@Fi1osof You should send new commits to this branch and PR will be reopened and updated. If you sent changes from github website, you should create a new PR and link with this.

**Comment by Fi1osof** [comment]
@Alroniks OK, will soon. Thanks!

**Comment by Fi1osof** [comment]
[#12369](https://github.com/modxcms/revolution/pull/12369)

**Pull request closed without merging**
