### PR TITLE
Update of the search processor for content-based search

### PR DESCRIPTION
**Pull request by Bournwog**
The search processor has been replaced with the one used in MODX 3
Now the search is performed based on the content
The commented-out functionality 'searchActions' has been removed

### CODE REVIEW

**Comment by Mark-H** [comment]
From a code review this looks fine for inclusion, just needs to get sufficiently tested, and probably targeting a 2.9 release instead of a 2.8.x?

**Comment by Bournwog** [comment]
I've used it on several sites, it seems ok

**Comment by Ruslan-Aleev** [comment]
@Bournwog You have a `quick_search_result_max` setting in your code, but you didn’t create it; MODX 2 doesn’t have it initially.

**Comment by Bournwog** [comment]
@Ruslan-Aleev yes, I replaced one setting that is hardcoded with another, without setting a variable, if there is no variable, the hardcoded value will be taken

**Comment by Ruslan-Aleev** [comment]
@Bournwog I understand how it works, yes. It just seems unfinished =) I would also add a setting.

**Comment by SnowCreative** [comment]
I have mixed feelings about this. I find the new search function less useful for finding certain things. There is the "advanced search" that will search content, and I find that the more appropriate place for that. For example, I used to be able to type in just a number, and the quick search would find all resources, TVs, etc. with that ID number. With the new search number, that doesn't work; all sorts of other matches get mixed in. Advanced Search has an ID field, but that only searches resources, not TVs, chunks, etc.

**Comment by Bournwog** [comment]
@Ruslan-Aleev 
add lexicon and settings fix

**Comment by Ruslan-Aleev** [comment]
@Bournwog Leave the lexicon only for `en`, for other languages ​​translations will be pulled from crowdin.

**Comment by Bournwog** [comment]
@Ruslan-Aleev
check it

**Review by Ruslan-Aleev — APPROVED** [review]

**Review by theboxer — APPROVED** [review]
works as described

**Pull request merged**
