### PR TITLE
Clear usergroups session var in leaveGroup

### PR DESCRIPTION
**Pull request by BobRay**
OK, this one is clean.

### CODE REVIEW

**Comment by pixelchutes** [comment]
Putting this here as a reminder to also fix the Docblock comment for `leaveGroup()`:

### BEFORE ###
```
@param mixed $groupId Either the name or ID of the User Group to join.
```

### AFTER ###
```
@param mixed $groupId Either the name or ID of the User Group to leave.
```

**Comment by Mark-H** [comment]
Are there any other related issues/prs to this one?

**Comment by Mark-H** [comment]
Thanks Bob, merged and ready for inclusion in 2.3.6. If you don't mind, please use the template from the Contributing Guidelines for future PRs, just to make sure we have all the info available in the pr. Thanks! 

https://github.com/modxcms/revolution/blob/master/CONTRIBUTING.md#template-1

**Comment by BobRay** [comment]
I'll try to remember. ;)

**Pull request merged**
