### PR TITLE
Missing three restricted symbols

### PR DESCRIPTION
**Pull request by darkarchon**
*full list symbols are in preg_match function
core/model/modx/processors/security/user/_validation.php:88

### What does it do?
Add missing restricted symbols to lexicon description ";", "<", ">".

### Why is it needed?
You can't using them for passwords.

### How to test
Try to use any of them in new password and you see incomplete list of restricted symbols.

### Related issue(s)/PR(s)
Not such an issue

### CODE REVIEW

**Review by Ibochkarev — CHANGES_REQUESTED** [review]
Changes to lexicons need to be made only in the English version. The rest is transferred via Crowdin

**Comment by JoshuaLuckers** [comment]
@darkarchon thanks for taking time to help improve MODX.

As mentioned by @Ibochkarev, changes in lexicon strings need to be done in the English files only. 
Can you undo the changes in all the files except `core/lexicon/en/user.inc.php`?

**Review by JoshuaLuckers — CHANGES_REQUESTED** [review]
@darkarchon thanks for taking time to help improve MODX.

As mentioned by @Ibochkarev, changes in lexicon strings need to be done in the English files only. 
Can you undo the changes in all the files except `core/lexicon/en/user.inc.php`?

**Comment by JoshuaLuckers** [comment]
@darkarchon if you have the opportunity to look at the requested changes that would be great, if not please let us know!

**Comment by Ibochkarev** [comment]
@darkarchon thanks for taking time to help improve MODX. 
I close this PR due to lack of activity in favor of https://github.com/modxcms/revolution/pull/15611

**Pull request closed without merging**
