### PR TITLE
SECURITY.md

### PR DESCRIPTION
**Pull request by JoshuaLuckers**
### What does it do?
Add a SECURITY.md file with info about reporting security issues in MODX

### Why is it needed?
Encourage responsible disclosure

### Related issue(s)/PR(s)
Fixes issue #14204

### CODE REVIEW

**Review by Jako — DISMISSED** [review]

**Review by alroniks — DISMISSED** [review]

**Comment by Mark-H** [comment]
@opengeek Any chance you heard back from HackerOne about potentially using that instead of the old emails?

**Comment by JoshuaLuckers** [comment]
@opengeek ping

**Review by opengeek — CHANGES_REQUESTED** [review]
HackerOne is not an option at this time. That link in this document is no longer valid either.

**Comment by JoshuaLuckers** [comment]
> That link in this document is no longer valid either.

Is there a new link available?

**Comment by opengeek** [comment]
I added a redirect for that old link; it now goes to:

https://modx.com/community/contribute/report-a-security-issue

**Comment by JoshuaLuckers** [comment]
> I added a redirect for that old link; it now goes to:
> 
> https://modx.com/community/contribute/report-a-security-issue

Thanks, I updated my PR with the new link.

**Comment by Ibochkarev** [comment]
@opengeek Please check again

**Pull request merged**
