### PR TITLE
Restrict static resources to predefined path (port of #15656 for 3.x, SEC-3801)

### PR DESCRIPTION
**Pull request by Mark-H**
WIP

### What does it do?
Describe the technical changes you made.

### Why is it needed?
Describe the issue you are solving.

### How to test
Describe how to test the changes you made.

### Related issue(s)/PR(s)
Provide any issue that's addressed by this change in the format "Resolves #<issue number>", and mention other issues/pull requests with relevant information.

### CODE REVIEW

**Comment by Mark-H** [comment]
If someone else has time to pick this up over the coming days, please do. I'm otherwise engaged and may not have the time, but it'd be good to get this included in the beta early next week.

**Comment by muzzwood** [comment]
I'm looking in to this at the moment. Though, *so far* all is working as expected without me changing anything.

**Comment by muzzwood** [comment]
I've tested this with the various different content types.

- If `resource_static_allow_absolute` is disabled. Requests always redirect to the `error_page` resource unless within the path specified by the `resource_static_path` setting.
- If `resource_static_allow_absolute` is enabled, the static resource loads the file contents correctly even if outside the path set by `resource_static_path`.
- Full absolute paths work on the resource if `resource_static_allow_absolute` is enabled.
- Full absolute paths work on the resource even if  `resource_static_allow_absolute` is disabled, as long as the path is the one that's set in `resource_static_path`. **NOTE: I'm not *entirely* sure if this is the intended behaviour, but I believe it to be.**
- Working as expected with or without a template applied.
- Tested with different filesystem media sources; no issues found.

**Comment by opengeek** [comment]
@Mark-H — this seems like it is working as expected. Can you verify and go ahead and mark it ready for review if so?

**Comment by Mark-H** [comment]
I've not personally done as extensive testing as @muzzwood but as it's practically copy/pasted from 2.x (which was tested a fair bit!), plus I trust @muzzwood's judgement, go for it. ;)

**Review by opengeek — APPROVED** [review]

**Pull request merged**
