### PR TITLE
Show all resources to purge in the trash manager and change the tree options for deleted resources

### PR DESCRIPTION
**Pull request by Jako**
### What does it do?
- Add the not deleted children of deleted resource parents to the trash manager grid. 
- Don't show the create/quick create context menu  and the plus button for a deleted resource.

### Why is it needed?
- The not deleted children will be purged during purging the parents, so they have to be shown in the grid and in the list of purged resources.
- It makes no sense to create resources where they could be purged afterwards.

### Related issue(s)/PR(s)
#14167

### CODE REVIEW

**Review by JoshuaLuckers — APPROVED** [review]

**Comment by Ruslan-Aleev** [comment]
@Jako Can you mark resources as deleted if their parents are deleted?
This would be visually useful, because it is immediately visible in the tree that the resource will be deleted and the user will not be confused.

**Comment by Jako** [comment]
@Ruslan-Aleev It would be strange, when a file, that does not have the 'deleted' property enabled, is shown as deleted.

At the moment, all resources in a tree are marked as deleted, when the parent is deleted (maybe this works only with the context menu - but thats a different issue see #14349). So if you undelete afterwards a subtree, this is a user decision and should be visible in the tree.

**Comment by Ruslan-Aleev** [comment]
> It would be strange, when a file, that does not have the 'deleted' property enabled, is shown as deleted.

Yes, it is true, but there is confusion. The user notes them that they are not deleted, but they are also displayed in the trash manager, isn’t there a  logical conflict?

> So if you undelete afterwards a subtree, this is a user decision and should be visible in the tree.

Such resources should not be deleted in the trash manager, but they will be deleted (you won't even restore them until the parent is restored).

It would be correct either to mark them deleted (for example, activate and block the deleted checkbox), or to change their parent.

**Comment by Ruslan-Aleev** [comment]
As a result, we can undelete resource, but if its parent is deleted, the resource is also wil be deleted, so I suggest marking and freezing the deleted  checkbox for such a resource, which will immediately let the user know that something is wrong.
If we do not mark the deleted checkbox, then visually everything in the tree looks fine, but the resource will be deleted from the trash manager, and this is more serious situation.

**Comment by Jako** [comment]
The additional purged resources could be marked special in that trash manager grid and in the popup. Would that be enough?

**Comment by JoshuaLuckers** [comment]
I think it makes more sense to "undelete" the parent if you "undelete" a child.

**Comment by Ruslan-Aleev** [comment]
@JoshuaLuckers Yes, I agree, in a issue I described several variants:
1) Activate and freeze the setting "Deleted" in children resources until the parent is deleted
2) Restore parent if children been restored
3) Change the parent to 0 and set the resource to unpublised, if it has been restored and its parent has been deleted.

**Comment by Ruslan-Aleev** [comment]
@Jako I do not know, here we need additional discussion. I’m still in favor of marking resources as deleted (if the parent is deleted), because in fact, such resources will be deleted.
And if there are a lot of deleted resources, then in the trash manager you may not notice the marks (since pagination is used there).
By the way, it is not clear what will be in the tree if this function is implemented - https://github.com/modxcms/revolution/issues/14158

@Alroniks @Mark-H @opengeek Can you help with the discussion?

**Comment by Jako** [comment]
@Ruslan-Aleev 
- Freeze the deleted setting is not an option, because sometimes you want to delete all but one item. This could be handled by deleting the parent and restore just that item and the parent.
- Restore the parent could be an option (or a warning, what could happen without restore the parent).
- Change the parent to 0 is not an option, since that can't be reverted easy.

**Comment by Ruslan-Aleev** [comment]
Probably yes, it is better to restore more than necessary than to delete more than necessary :)
The option of restoring a deleted parent, in the case of restoring a deleted child, is the best option.

**Comment by Jako** [comment]
I suggest to do get this merged into 2.7.1 and do the changes for restoring the parent(s) during restoring a child in 3.x, since that would be a 'behavior change'. I will create a new issue for this.

**Comment by Jako** [comment]
This PR is still valid at the moment for the following list:

- if a resource is deleted by quickedit or by checkbox in the resource edit, the children are not deleted
- if the resource is deleted by changing the deleted field directly in the database, this is the same
- undeleted resources could be dragged into deleted parents

Then the undeleted children of a deleted resource would be purged in the trash manager without showing them there.

**Review by Ruslan-Aleev — APPROVED** [review]

**Review by opengeek — APPROVED** [review]

**Comment by SnowCreative** [comment]
OK, I know I'm a bit late to the party here, but to me the most user-friendly option would be this:
If there is an undeleted resource under a deleted folder (either because someone dragged it there or manually undeleted it after the parent was deleted), when purging the parent, an alert would pop up like the following:
_The resource "[resource name]" is not marked for deletion but its parent will now be deleted. Delete this resource as well, or move it upwards in the tree?_
Then you'd have the option to either delete the undeleted resource, or move it up in the tree to the closest undeleted parent.

**Comment by Ruslan-Aleev** [comment]
Pop-up windows have inconvenience: some users may not pay attention to this.
There is an issue - https://github.com/modxcms/revolution/issues/14368

**Comment by Jako** [comment]
We will refactor the modResource model for deleted resources in MODX3: https://github.com/modxcms/revolution/issues/14368#issuecomment-463370037

**Comment by JoshuaLuckers** [comment]
This PR is already merged and the ongoing conversation will end up in oblivion. It's better to move the conversation to an existing or new issue.

**Pull request merged**
