### PR TITLE
[#12508] Validate chmod value

### PR DESCRIPTION
**Pull request by garryn**
PR related to #12508.

### CODE REVIEW

**Comment by Mark-H** [comment]
Hey @garryn can you follow the template from the [contributing guidelines](https://github.com/modxcms/revolution/blob/master/CONTRIBUTING.md#submit-a-pull-request) next time? ;)

**Comment by garryn** [comment]
@Mark-H Probably not, lol - I'll not bother putting a fix in.

**Comment by Mark-H** [comment]
`if (!preg_match('/^[0-7]{4}$/')) {` is incorrect, should have been `if (!preg_match('/^[0-7]{4}$/', $mode)) {`

**Comment by Mark-H** [comment]
Cherry picked for 2.3.6, and added $mode param, in b6f9b5a88b0f55a7a43ffcc44fbf85a6bc211841.

**Comment by Mark-H** [comment]
This change actually breaks being able of changing the chmod completely, always returning the error. `$mode = $this->parseMode($mode);` returns a decimal representation of the octal value.

**Comment by Mark-H** [comment]
I've reverted the merge in 3cc59d0b939817ec43ba40abf3aa821b82626d72, please update your PR and let me know when it's ready again.

**Pull request closed without merging**
