### PR TITLE
Code coverage

### PR DESCRIPTION
**Pull request by AgelxNash**
### What does it do?
Code Coverage
Html report: [coverage.zip](https://github.com/modxcms/revolution/files/2432534/coverage.zip)
Html report

### CODE REVIEW

**Review by JoshuaLuckers — CHANGES_REQUESTED** [review]
Can you undo the reformatting of the composer.json file? The formatting changes hide the actual addition of the coverage additions.

**Comment by OptimusCrime** [comment]
@JoshuaLuckers on the other hand. Having it indented with just two spaces is much nicer.

**Comment by JoshuaLuckers** [comment]
True, then a separate commit for the reformatting would be a better idea.

**Comment by AgelxNash** [comment]
@JoshuaLuckers Enjoy:-)

**Comment by JoshuaLuckers** [comment]
@AgelxNash Thanks! This makes it easier to see what has been added to the composer.json. Feel free to re-apply the reformatting. 👍

**Review by Mark-H — DISMISSED** [review]

**Review by Jako — APPROVED** [review]

**Pull request merged**
