### PR TITLE
Purge old packages button in packages management

### PR DESCRIPTION
**Pull request by Jako**
### What does it do?
Add a 'Purge Old Packages' button to the Package Management manager page.

### Why is it needed?
In Package Mananagement the details of a package could be shown with a list of all previous installed package versions. The entries in that grid could be removed one by one. There is a button missing for 'Purge Old Packages' that removes all old package versions.

The processor could be restricted to one package name by an option. A 'Purge Old Versions' button is available in the package details window.

### Related issue(s)/PR(s)
#12818

### CODE REVIEW

**Comment by rthrash** [comment]
Awesome!

**Comment by sottwell** [comment]
Maybe a checkbox and bulk operation on all checked items instead of willy-nilly removing all previous versions?

**Comment by Jako** [comment]
Nice idea, but a lot more work than my addition.

**Comment by Alroniks** [comment]
Purge all old versions may be dangerous and yes, I'd prefer to select items and delete only selected. Nevertheless, it's a good start.

**Comment by Jako** [comment]
A trash is a trash and previous installed versions are previous installed versions. Why should a special previous version be retained? 

Maybe there could be an input to remove all but the last two versions of each package. And of course: there should be a button in each package details window, to purge only the previous versions of this package.

**Comment by Alroniks** [comment]
@Jako It was that I mean. Sometimes you need at least keep the previous version to have an ability to rollback changes. But removing all except current and -1 version is also not so useful. Checkboxes more complex to implement but it adds more freedom and covers more use cases.

**Comment by Omeryl** [comment]
@alroniks What’s preventing the user from downloading the old version again? If I recall, we don’t delete old versions from the official provider automatically.

**Comment by OptimusCrime** [comment]
@Omeryl The API only returns the last version. The REST API would need to be upgraded.

**Comment by Omeryl** [comment]
@optimuscrime yeah, but we’re not doing this on upgrade. If you really need to downgrade, you can pull up the old package version and just download it yourself. The normal workflow I see would be:
1) Upgrade package
2) Test your site
3) Purge old versions

**Comment by Alroniks** [comment]
I agree with that we should have the ability to remove old versions but I am advocating variant and implementation when a user has more ways that one (real freedom) to do that.

**Comment by rthrash** [comment]
I would suggest starting with a simple purge all but current … you're not forced to purge anything and 99% of users won't notice this anyway. If there is demand down the road it can be expanded to save the N-last versions, but it sure would get rid of a lot of cruft in the interim.

**Comment by Jako** [comment]
Now the old versions of one package could be purged with another button.

**Comment by Mark-H** [comment]
Works nicely @Jako! Thanks!

**Pull request merged**
