### PR TITLE
Fixed sorting in user management

### LINKED ISSUE #14614: Error sorting users by id in the list of users
### Summary
Sorting users by id in the list of users not work

### Step to reproduce
Go to menu **Manage** -> **Users**

### Observed behavior
Attempting to sorting users by id in the list of users hides an existing user.

users

The error log is as follows:

```
[2019-06-26 23:48:54] (ERROR @ /Volumes/HDD Data/web/refactoring/core/vendor/xpdo/xpdo/src/xPDO/Om/xPDOObject.php : 227) Error 42000 executing statement: 
Array
(
    [0] => 42000
    [1] => 1064
    [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\Revolution\modUser.id ASC LIMIT 20' at line 1
)

[2019-06-26 23:48:57] (ERROR @ /Volumes/HDD Data/web/refactoring/core/vendor/xpdo/xpdo/src/xPDO/Om/xPDOObject.php : 227) Error 42000 executing statement: 
Array
(
    [0] => 42000
    [1] => 1064
    [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\Revolution\modUser.id DESC LIMIT 20' at line 1
)

[2019-06-26 23:48:57] (ERROR @ /Volumes/HDD Data/web/refactoring/core/vendor/xpdo/xpdo/src/xPDO/Om/xPDOObject.php : 227) Error 42000 executing statement: 
Array
(
    [0] => 42000
    [1] => 1064
    [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\Revolution\modUser.id ASC LIMIT 20' at line 1
)
```

### Environment
MODX 3 with the latest commit https://github.com/modxcms/revolution/commit/26430024e33db91b599e57a5b9c530b19cd6be31
PHP 7.1.2
MySQL 5.7.23

### PR DESCRIPTION
**Pull request by alroniks**
### What does it do?
It introduces a new method that takes FQCN and returns only short form for representing this class name to the SQL query.

### Why is it needed?
It fixes sorting function in the grid with users.

### Related issue(s)/PR(s)
Closes #14614

### CODE REVIEW

**Comment by alroniks** [comment]
Hold on. It's a common issue, I will fix it for all processors by common code.

**Review by opengeek — CHANGES_REQUESTED** [review]
You don't need this. `xPDOQuery->getAlias()` works fine.

**Comment by alroniks** [comment]
@opengeek even better, but need to fix in all processors, there are a lot of such places

**Comment by opengeek** [comment]
Solved in cf168774db948c96488845e49ddcfe5eb2c7da88

**Pull request closed without merging**
