### PR TITLE
Fire event on one resource cache update

### PR DESCRIPTION
**Pull request by faitno**
This event need for speed up extension "statcache" http://modx.com/extras/package/statcache from opengeek, that delete only one file from static cache, and provides freshness it

### CODE REVIEW

**Comment by Mark-H** [comment]
It looks like a commit from #13163 made it into this pull request.

The `OnResourceCacheUpdate` event also isn't added in _build/data/transport.core.events.php. Other than that I can see this as a useful event for certain cases.

**Comment by sdrenth** [comment]
@soulcreate Are you planning on working on this PR and fixing the feedback provided by Mark?

**Comment by OptimusCrime** [comment]
The origin repository is unknown, so it has to be recreated. 

I could do it, it adding it to the transport core file is the only other thing that needs to be done?

**Comment by Mark-H** [comment]
Closing in favour of #13590.

**Pull request closed without merging**
