### PR TITLE
Fix margin .modx-page-header

### PR DESCRIPTION
**Pull request by Ibochkarev**
### What does it do?
Corrects indents at heading

### Why is it needed?
Fix header indents - add margins property

Before fix:
Before

After fix:
After

### Related issue(s)/PR(s)
Not know

### CODE REVIEW

**Review by JoshuaLuckers — DISMISSED** [review]

**Review by Mark-H — APPROVED** [review]

**Review by Mark-H — CHANGES_REQUESTED** [review]
While this fixes the positioning on the _dashboard_, it makes the positioning wrong in most other places (e.g., package manager, system settings). It looks like there's some margin being added on the dashboard blocks that cause this one to look out of place.

**Comment by Ibochkarev** [comment]
@Mark-H I am fix styles #modx-panel-welcome

**Review by Jako — CHANGES_REQUESTED** [review]
Since this is sass, it could be changed to:
```
/* panel stylings */
.modx-page-header, .modx-page-header div {
  background-color: transparent !important;
  #modx-panel-welcome & {
    margin: 0 1rem 1rem 1rem;
  }
}
```

**Review by Jako — APPROVED** [review]

**Comment by opengeek** [comment]
@Mark-H are the updates satisfactory now?

**Comment by Ibochkarev** [comment]
@Mark-H Hi! Please check this PR

**Review by Mark-H — APPROVED** [review]
Yep, works better now :)

**Comment by Mark-H** [comment]
Thanks @Ibochkarev!

**Pull request merged**
