### PR TITLE
Allow safe html in system setting description

### PR DESCRIPTION
**Pull request by Jako**
### What does it do?
Create a safeHtml method in MODx.util, that strips all not allowed html tags, html attributes and javascript in the href attribute.

### Why is it needed?
Allow a reduced set of html attributes in the system setting grid.

It should be checked carefully, wether there could get some executable script though this.  

### Related issue(s)/PR(s)
#14437

### CODE REVIEW

**Review by JoshuaLuckers — DISMISSED** [review]

**Comment by Mark-H** [comment]
Because the regex assumes valid markup, it's possible to evade this filter with a string that isn't valid markup:

```
<<SCRIPT>img src=/ onerror=alert('gotcha')</SCRIPT>>
```

(Added to the setting description, it does require the description to be expanded, but a better security researcher may know ways around that.)

I'm thinking it may be needed to call the filter recursively, but after just spinning my browser into an infinite loop I think it's getting too late for me to suggest an actual implementation :p

**Comment by Jako** [comment]
Grr! But thanks for the test.

**Comment by Jako** [comment]
The replacing iterates now. 

It misses a detection for attributes without a quote sign. I hope this could be handled.

**Comment by Jako** [comment]
Those html attributes without a quote sign can't be stripped without deeper parsing. Now the html event attributes are invisible masked. I hope this is enough.

**Comment by OptimusCrime** [comment]
Would it not be better to just encode all the special characters? Regexing "safe" content is next to impossible, and I bet there are more than a few ways to get around the stip function still.

**Comment by Jako** [comment]
Some system settings have links and formatted text inside of the description. That is no more possible at the moment. The script is quite harsh against all invalid tags and I don’t think that an attack through this is possible (but I am not absolutely sure).

**Comment by OptimusCrime** [comment]
Hm, okey. Well, I guess, if you really wanted to make it secure you would have to remove all the enhanced text then. This is by definition still exposed to XSS vulnerabilities, but I am sure this fix works good enough.

**Comment by Jako** [comment]
What do you mean with enhanced text?

**Comment by Jako** [comment]
The script strips all tags that are not allowed, it strips all tag attributes, that are not allowed. It removes javascript links in the href attribute and it inserts an invisible space in text with `onwhatever=` to make not stripped event attributes (because of a missing quote) invalid.

**Comment by Ibochkarev** [comment]
@opengeek Please check this PR

**Review by Mark-H — APPROVED** [review]
I've not been able of bypassing this filter, good job 👍

**Review by JoshuaLuckers — APPROVED** [review]

**Pull request merged**
