### PR TITLE
Update phpThumb 1.7.21-202307141720

### PR DESCRIPTION
**Pull request by Maef**
### What does it do?
Update phpThumb 1.7.21-202307141720

### Why is it needed?
PHP 8.2 fixes

See changes https://github.com/JamesHeinrich/phpThumb/compare/v1.7.19...v1.7.21

### CODE REVIEW

**Comment by Omeryl** [comment]
@cla-bot check

**Comment by Ibochkarev** [comment]
@modxbot check

**Comment by Ibochkarev** [comment]
@cla-bot check

**Comment by Maef** [comment]
@cla-bot check

**Pull request merged**
