### PR TITLE
Uberbar improvements, makes room for site information in the header (site name / MODX version)

### PR DESCRIPTION
**Pull request by pixelchutes**
Based off ideas from #11850

### CODE REVIEW

**Comment by jaygilmore** [comment]
Is this PR still being considered? It's not been closed and this seems like there is some value to at least parts of it.

**Comment by pixelchutes** [comment]
I'd hope so, @jaygilmore -- My original motivation was purely reintroduction of site name / version, which many still seem on the fence about, but ended up improving / fixing a few minor issues along the way.

Also, this is an attempt at creating just a little more room in an already cramped space...especially on smaller devices, like @gpsietzema has illustrated above.

**Comment by OptimusCrime** [comment]
I +1 for this merged in the 2.4-branch

**Comment by Mark-H** [comment]
This was just merged into develop for 2.4. Great work @pixelchutes :)

**Comment by theboxer** [comment]
The search doesn't close when you click somewhere else or on `esc` key press, so you have to hit the search icon again...

**Comment by pixelchutes** [comment]
It's been awhile since I've tested that, but I was pretty sure it was accounting for `esc` / clicking outside. I believe in the animated gifs above you can even see results go away when I am pressing escape (hard to illustrate).

**Comment by pepebe** [comment]
This is colliding with my current refurbishing of the uberbar. 

bildschirmfoto 2015-06-30 um 16 09 41

I agree that the site information should be shown in a prominents space as I tend to work in more than one MODX project at the same time and it is very hard to tell them apart.

I'll have a look how to integrate this. PR will hopefully be coming up in the next hours.

**Comment by pixelchutes** [comment]
@theboxer I'm not sure why yet (or if it has to due with merging to `develop`) but it doesn't seem like the original `Ext.KeyMap` is being applied, so the following is not being triggered as it should:
```javascript
Ext.getCmp('modx-uberbar').hideBar();
```

**Comment by pixelchutes** [comment]
Not sure if it's related, but it may conflict with this change: https://github.com/modxcms/revolution/commit/5aae7ea6fc3a1ef61ce3e91b667d4a6e1d1859e3#diff-13ba45e0161390fbee6c1a566a7d4a88

**Comment by pixelchutes** [comment]
This was just fixed in `develop` via 1e37e91da0c0820a004ed80663cf46f79239680d

The aforementioned PR (previous post) was inadvertently disabling _both_ keymap listeners instead of just the offending uberbar keyboard shortcut. The new fix restores the ability to close uberbar via  <kbd>Esc</kbd>

**Pull request closed without merging**
