### PR TITLE
Fatal error: Cannot redeclare class modTemplateV..

### PR DESCRIPTION
**Pull request by Fi1osof**
Related to [#827](https://github.com/modxcms/revolution/pull/827)

### CODE REVIEW

**Comment by TheBoxer** [comment]
Hi @Fi1osof. 
Thanks for trying to help with this issue. From my understanding, your PR simply hides the error, but doesn't solve the underlying problem. Can you confirm?

**Comment by Fi1osof** [comment]
@TheBoxer you understood it wrong. This PR excludes error. Hide error - when error exsists. Here error not exsists. Is there not class_exists in MODX? Check it here: https://github.com/modxcms/revolution/search?utf8=%E2%9C%93&q=class_exists&type=Code

**Comment by TheBoxer** [comment]
Let's step back,
can you please update the PR to follow contributing guide and provide steps how to reproduce this problem?

I don't consider wrapping a class in class_exists method as a proper solution (and you will not find that in the link you provided), because in an edge case you can do that with all classes to prevent their in-proper inclusion.

**Comment by Fi1osof** [comment]
@TheBoxer Looks like already fixed. IF note mistake again, I will inform you.

**Comment by TheBoxer** [comment]
Ok, closing then. Reopen if you'll need to.

**Comment by Fi1osof** [comment]
@TheBoxer OK

**Comment by Fi1osof** [comment]
I have error again. I think it`s because text.class.php is included for different methods [if class is not found] (https://github.com/modxcms/revolution/blob/master/core/model/modx/modtemplatevar.class.php#L448-L450).
MODX 2.2.16
I think it`s actual for MODX 2.3 too

**Comment by pixelchutes** [comment]
Interesting, does changing to `include_once` solve the issue for you?

**Comment by Fi1osof** [comment]
@pixelchutes Not, because $TV will not know $className without including (https://github.com/modxcms/revolution/blob/master/core/model/modx/modtemplatevar.class.php#L449). 
In modTemplateVar exists method [checkForRegisteredRenderMethod](https://github.com/modxcms/revolution/blob/master/core/model/modx/modtemplatevar.class.php#L466), but i think it`s work not correctly.

**Pull request closed without merging**
