### PR TITLE
Add renderEditableColumn to LocalGrid

### LINKED ISSUE #14939: 3.x Editing icon in FC and ACL grids does not appear
### Summary
Editing icon in FC and ACL grids does not appear:
- in the _Form Customization_ section (**all tabs of the Sets**)
- in the _Access Control Lists_ section **(the Access Policies editing form and the Policy Template editing form**).

Perhaps in other similar sections where there is a checkbox in the grid, as it seems to me.

### What does it look like
For example, Sets of the Form Customization section.

fc_sets

### Expected behavior
The appearance of the pen icon on the column.

### Environment
MODX 3.x

### PR DESCRIPTION
**Pull request by theboxer**
### What does it do?
Adds functionality to display the pencil icon in editable columns to the LocalGrid.

### Why is it needed?
Right now is the functionality only in the Grid, so in LocalGrid the pencil icon won't show up.

### Related issue(s)/PR(s)
Closes #14939

### CODE REVIEW

**Comment by Ruslan-Aleev** [comment]
Unfortunately, the icon did not appear in the media source and on TV (maybe somewhere else):

source_grid

**Comment by Ruslan-Aleev** [comment]
There was another problem:
Now for "Yes / No" parameters there is no output, only when editing.

source_grid_2

p.s. In the form of TV, for media sources, the icon did not appear.

**Comment by theboxer** [comment]
@Ruslan-Aleev try it now please

**Review by Ruslan-Aleev — APPROVED** [review]
Visually everything works as it should :) Thank you!

**Review by Ibochkarev — APPROVED** [review]
Its work

**Comment by theboxer** [comment]
@JoshuaLuckers What kind of documentation it needs? It's fixing an issue where functionality added in #14748 was not added to all grid types

**Comment by JoshuaLuckers** [comment]
My mistake!

**Review by JoshuaLuckers — APPROVED** [review]

**Pull request merged**
