### PR TITLE
Lexicon check for the core

### PR DESCRIPTION
**Pull request by Jako**
### What does it do?
Add a lexicon check for the core. Cross check the core files with the existing lexicon entries for the usage of a lexicon entry.

### Why is it needed?
To detect easier, which lexicon entries are used.

The script creates 3 files in the _build/lexicon folder. The files are containing missing and superfluous entries and the third one collects usages of the lexicon with variable generated keys (not all are currently collected - only the ones starting with a single/double quote key). The lexicon with variable generated keys can't be copied to a lexicon, so this generated code does not have to be valid - the other ones could be copied.

### Related issue(s)/PR(s)
#14512

### CODE REVIEW

**Comment by Jako** [comment]
At the moment the variable object type errors of the core processors are not cross checked i.e. created by `$this->objectType.'_err_ns'` code. The used object types of the core processors could be collected and the the lexicon entries could be cross checked afterwards.

**Comment by Jako** [comment]
The check is currently created on 2.x. It should be valid for 3.x too with a few changes.

**Comment by JoshuaLuckers** [comment]
If connecting to the database fails the script will continue to execute. I don't think this is supposed to happen.
Afterwards 3 new files are created:
- _missing.php
- _superfluous.php
- _variable.php

It's a bit unclear to me what the content of each file means. The syntax of the generated content of `_variable.php` is invalid:
```
<?php
$_lang['area_'.$object->get('area'] = '';
$_lang['area_'.$object->get('area'] = '';
$_lang['db_info_' + MODx.config.dbtype)+'</p>'] = '';
$_lang['refresh_' . $partition) . ': ' . $this->modx->lexicon('refresh_' . ($result ? 'success' : 'failure'] = '';
$_lang['refresh_' . ( $result ? 'success' : 'failure'] = '';
$_lang['refresh_' . ($ctxResult ? 'success' : 'failure'] = '';
```

**Comment by Jako** [comment]
The script crosschecks only files, so there is no need for a DB connection.

The three files are containing missing and superfluous entries and the third one collects usages of the lexicon with variable generated keys (not all are currently collected - only the ones starting with a single/double quote key). The lexicon with variable generated keys can't be copied to a lexicon, so this generated code does not have to be valid - the other ones could be copied.

**Comment by JoshuaLuckers** [comment]
It would be nice to have this documented in the script and/or files it generates.

**Comment by Mark-H** [comment]
@cla-bot check

**Pull request closed without merging**
