### PR TITLE
Add ACL "set_sudo" to prevent non-sudo users from elevating themselves or others to "sudo"

### PR DESCRIPTION
**Pull request by labr1005**
### What does it do?
- adds a new permission "set_sudo" ("To make any User sudo"), enabled for Access Policy "Administrator" by default
- shows/hides the checkbox "Sudo User" on the user create/update page
- checks for "set_sudo" permission on create/update user

### Why is it needed?
To prevent non-sudo users from elevating themselves or others to 'sudo'.

### Related issue(s)/PR(s)
#13806

### CODE REVIEW

**Comment by ghost** [comment]
I have a problem with this particular way of handling the sudo issue. Should non-Sudo users _ever_ be able to manipulate the Sudo property of any other users? What is the use case of such an ability? ACL permissions are for optional abilities, aren't there some actions that should never be allowed? For example, unpublishing or deleting the site_start page comes to mind.

**Comment by labr1005** [comment]
With this ACL in place a non-sudo user can't change any user's sudo status - including their own status.

Without an ACL, if you disable sudo for yourself, how could you ever enable it again for yourself? You would become a non-sudo user without the permission to change the status for any user...

**Comment by Bruno17** [comment]
+1 for this solution (didn't test it, yet)
It should be possible to give set_sudo - permission to groups at will.

**Comment by Mark-H** [comment]
This approach looks good as a way to limit users from assigning themselves sudo without permission (hah!), and passes my code review 👍

**Review by Mark-H — DISMISSED** [review]

**Review by opengeek — CHANGES_REQUESTED** [review]
Can you please remove this merge from the pull request? You should never merge the base branch back into a pull request branch. If you want to update the pull request, use `git rebase upstream/2.x` (assuming the remote for the `modxcms/revolution` repository is named `upstream`) and do a forced push of the branch to your fork to update the pull request.

**Comment by labr1005** [comment]
@opengeek Done. Can you please have a look and sorry for this. My purpose was to include the `"events":true` from #13830 which is now missing again in my PR... https://github.com/modxcms/revolution/pull/13807/files#diff-65f2d46431c4fd7a2cdb261551bf9fe7

**Comment by opengeek** [comment]
@labr1005 if it is dependent on something in another PR it should probably be added to that PR. If that PR is already merged, just rebase on top of the latest code and force push, as I explained.

**Comment by labr1005** [comment]
@opengeek I did a rebase and force push, but that long one-liner made trouble. Fixed now.

**Review by opengeek — DISMISSED** [review]

**Comment by opengeek** [comment]
Somehow, after merging this and running upgrade, my Administrator policy has 0 of 175 permissions. Investigating…

**Comment by labr1005** [comment]
I confirm and will look into this.

**Comment by labr1005** [comment]
Found it.
`...,"events":true,export_static":true,...`
`...,"events":true,"export_static":true,...`

**Comment by opengeek** [comment]
Thanks for taking a look @labr1005 — I'll test again shortly and get this merged.

**Comment by opengeek** [comment]
Hmm, I'm not sure this is enough to be a practical solution to the problem. If I can edit users, I can put myself in the Administrators group and in this way I can essentially just give myself access to edit sudo on any user.

**Comment by labr1005** [comment]
You're right. But IMO that's a different problem that you show up here - the missing possibility to define for users/groups what groups they're allowed to set when creating/editing users.

**Review by bezumkin — APPROVED** [review]
Works as expected.

Of course, if you have enough permissions you can just enable `set_sudo` permission to you group and make yourself sudo user. 
But, anyway, it is better than nothing.

**Pull request merged**
