### PR TITLE
Fix unpacking

### PR DESCRIPTION
**Pull request by gvozdb**
### What does it do?
Fixing unpacking in MODX 2.5.2

### Why is it needed?
Describe the issue you are solving.

### Related issue(s)/PR(s)
Let us know if this is related to any issue/pull request (see https://github.com/blog/1506-closing-issues-via-pull-requests)

### CODE REVIEW

**Comment by Mark-H** [comment]
From the changes it looks like this is related to #13170 where the _path settings are removed from the config object?

**Comment by gvozdb** [comment]
Yes.

**Comment by Jako** [comment]
Is a full path really needed? Could the source path not be used?

**Comment by gvozdb** [comment]
Now in version 2.5.2 does not unpack archives. With this patch unpack.

**Comment by Jako** [comment]
I meant, that a full path does not have to be used in the connector. The media source and a relative path should be enough for identifying the unpack path.

**Comment by gvozdb** [comment]
OK. My code is based on this:
`,path: MODx.config.base_path + node.attributes.directory`

**Comment by OptimusCrime** [comment]
Fixed in alternate PR #13238

@modxbot close

**Comment by OptimusCrime** [comment]
Hmm, it looks like I don't have permissions to close this. @Jako mind closing this pending PR?

**Pull request closed without merging**
