### PR TITLE
[WIP]Run travis without running bash scripts

### PR DESCRIPTION
**Pull request by OptimusCrime**
### What does it do?
Not currently functional. Hold on!

### CODE REVIEW

**Comment by Mark-H** [comment]
You do realize you can have Travis run from your fork, too, right? :P

**Comment by OptimusCrime** [comment]
@Mark-H really? I was unable to get it to run on the commits. Does it work if I open a PR in my own fork?

**Comment by alroniks** [comment]
@OptimusCrime You have to set up Travis for your repo, that means go to Travis and grant rights to the repository. And maybe configure webhook.

**Comment by OptimusCrime** [comment]
Yeah, I know I could set up Travis on my own. I was just hoping I would get this to work soon enough that I did not have to do that. I'll close this and come back when everything is green.

**Pull request closed without merging**
