### PR TITLE
Widget: Recently edited resources, date/time from system settings

### PR DESCRIPTION
**Pull request by devlanda**
### What does it do?
Dashboard widget: 'Recently edited resources'. It takes the date and time format from the system settings:

- manager_date_format
- manager_time_format

Instead of using a fixed format, '%B %d, %Y' which is defined in recentlyeditedresources.tpl.

### Why is it needed?
Date and time formatting should be in line with the system settings as preferences differ per geographical area.

### Related issue(s)/PR(s)
N/A

### CODE REVIEW

**Comment by OptimusCrime** [comment]
I think this PR will have to wait (or be recreated) because of [PSR-4 / xPDO 3.x Model Refactor](https://github.com/modxcms/revolution/pull/14534)

**Comment by Mark-H** [comment]
Hey @devlanda, could you rebase/recreate this PR now that the massive refactor has been merged? Thanks :)

**Comment by JoshuaLuckers** [comment]
@devlanda if you have time to solve the conflicts that would be great 😄.

**Comment by Mark-H** [comment]
Ping @devlanda

**Comment by devlanda** [comment]
@JoshuaLuckers @Mark-H I made a new PR for this: https://github.com/modxcms/revolution/pull/14693

**Pull request closed without merging**
