### PR TITLE
Enable popper for the submenu too (opens on hover)

### PR DESCRIPTION
**Pull request by Jako**
### What does it do?
Apply Popper on subsubnav elements. Change the CSS to be used with Popper. The nav on System Settings is opened below of the entry on mobile. ~~A CSS rule avoids the subsubnav to grow larger than the viewport. The subsubnav content is scrollable.~~

### Why is it needed?
Fix a position out of the viewport for subsubnav elements. The use of Popper avoids the subsubnav be moved partly out of the viewport. Currently large subsubnavs are cut of at the bottom of the screen. Scrolling can be a future option for this (see https://github.com/modxcms/revolution/pull/16041#issuecomment-1036260889).

### How to test
Before: Reload the dashboard page with a viewport height of 700px. Open the 'manage' menu and look for the subnav of Reports. It is cut off on the bottom.
After: Run `grunt build` and do the same. The subnav of Reports is not cut off on the bottom.

### Related issue(s)/PR(s)
#16029 

### The following desktop issues are fixed

Language before (subsubnav: 86vh):
Language Before
Language after (subsubnav: 100vh - 12px):
Language After
Reports before:
Reports Before
Reports after:
Reports After
Long extras before:
Long Extras Before
Long extras after:
Long Extras After

### The following mobile issues are fixed

Language Before:
Language Before
Language After:
Language After
Long Extras Before:
Long Extras Before
Long Extras After:
Long Extras After

System Settings Before:
System Settings Before
System Settings After:
System Settings After

### CODE REVIEW

**Comment by smg6511** [comment]
Can you provide a couple screenshots showing the issue. I'm trying to replicate it (testing on Chrome) and can not get the menu to cut off (looking at a previous beta release). I feel like I've seen issues with the submenus before, but just can't seem to make it happen now.

**Comment by Jako** [comment]
Please look into the linked issue. If that's not enough, I can provide some extra examples.

**Comment by smg6511** [comment]
Sorry about that @Jako I thought I'd looked back at the issue, but had not (a second time, that is — I'd commented on the very issue you pointed me to!). Lot's going on ;-)

At any rate, would it be accurate to say it's an issue affecting certain browsers? I didn't see it on Chrome, but will take a look on Firefox and Safari.

**Comment by Jako** [comment]
I have added some screenshots to the PR description. The screenshots are created with Chrome. I don't think thats only affecting certain browsers.

**Comment by smg6511** [comment]
@Jako - Thanks for the images. You're right—it's all browsers. Whatever is causing the issue was introduced _after_ beta-1. In the current 3.x repo I see the problems.

**Comment by Jako** [comment]
Maybe it was introduced with https://github.com/modxcms/revolution/pull/15970

**Review by Ruslan-Aleev — CHANGES_REQUESTED** [review]
If the level is greater than 2, then the menu does not work.

Here is the menu I created:
menu_level_3

What it looks like:
menu_level_3_2

**Comment by Jako** [comment]
@Ruslan-Aleev Thanks, that occured after setting overflow-y for all submenus. It can be solved like this: https://css-tricks.com/popping-hidden-overflow/, but the current CSS of the sub(sub)menus is annoying complicated and I need some time to prepare that later. I will reset the overflow only to the language list.

**Comment by Jako** [comment]
It works now. Long subsubnavs are currently not scrolling, but this issue was there before. It can't be fixed fast (see the comments above), but it is better than the current state.

**Review by Ruslan-Aleev — APPROVED** [review]
Thank you, works better than what we have now.
But in the future, we should think about something with `overflow: hidden;` and `position: absolute;`

**Comment by JoshuaLuckers** [comment]
There is a horizontal scroll in the language toggle, otherwise it works as described! Great work.

Screen Shot 2022-02-19 at 09 47 06

**Comment by Jako** [comment]
@JoshuaLuckers I can't reproduce this here in Chrome + Firefox. Did you resize the window before without reloading the page? The position of the user menu seems wrong too.

**Comment by JoshuaLuckers** [comment]
@Jako yeah I did resize the screen, the menu opens in the right position after refreshing the manager.
The horizontal scrollbar still appears.

If I remove the width from the `#modx-footer .modx-subnav li a` selector the horizontal scrollbar disappears. 
Screen Shot 2022-02-19 at 14 53 10

 
P.s: I'm using Safari (desktop)

**Comment by Jako** [comment]
@JoshuaLuckers Thanks, Safari did indeed show the scrollbar. It is removed with the last change. Can anyone test this on Edge?

**Comment by JoshuaLuckers** [comment]
Chromium Edge? Or the "old" Edge?

**Comment by Jako** [comment]
The one I can't test because I am on a Mac.

**Comment by JoshuaLuckers** [comment]
@Ruslan-Aleev @Ibochkarev you guys use Windows right?

**Comment by Ruslan-Aleev** [comment]
> you guys use Windows right?

@JoshuaLuckers Yes, I am using Windows OS.

**Comment by Jako** [comment]
Can you test this PR on Edge please?

**Comment by Ruslan-Aleev** [comment]
> Can you test this PR on Edge please?

There are no extra scrolls, it works similarly to Google Chrome (in Edge Cromium is inside).

**Review by JoshuaLuckers — APPROVED** [review]

**Pull request merged**
