### PR TITLE
Changing old documentation links to current ones

### PR DESCRIPTION
**Pull request by Ibochkarev**
### What does it do?
Changing old documentation links to current ones

### Why is it needed?
For relevance of information

### Related issue(s)/PR(s)
NA

### CODE REVIEW

**Comment by theboxer** [comment]
@Ibochkarev Is the `/current/` in the URL a correct way for doing this? I suppose after 3.x will go out as PL, the `current` in docs will reference the 3.x release and all these links will be invalid.

**Comment by Ibochkarev** [comment]
> @Ibochkarev Is the `/current/` in the URL a correct way for doing this? I suppose after 3.x will go out as PL, the `current` in docs will reference the 3.x release and all these links will be invalid.

You can make similar changes for version 3.

**Comment by theboxer** [comment]
No, my point is, that when 3.x will go PL, these links in 2.x won't be correct and it will require another PR to fix them

**Comment by Mark-H** [comment]
Structure of 2.x and 3.x docs are the same, at least as far as these particular links are concerned, so docs wise I'd say current is fine.

**Review by Mark-H — APPROVED** [review]

**Pull request merged**
