### PR TITLE
Fix wrong width of textarea and text TVs when moved

### PR DESCRIPTION
**Pull request by OptimusCrime**
### What does it do?
If you are moving textfields and textareas to `modx-resource-main-left` or `modx-resource-main-right`, they are slightly too wide on the right side, breaking the bounderies of their surrounding columns.

Please note that this is untested! I copied the code from @pepebe 's original PR.

### Test case
Please see original issue #13323

### Why is it needed?
Fixes issue with styling.

### Related issue(s)/PR(s)
Issue ##13323
PR #13344
Local PR [pepebe/revolution/#2](https://github.com/pepebe/revolution/pull/2)

### CODE REVIEW

**Comment by Jako** [comment]
This PR should be enhanced, since the width and the box-sizing rule is applied only to textarea template variables. Other rules seems to be missing (input etc.).

**Comment by OptimusCrime** [comment]
@Jako Care to elaborate how you tested this? I can take it for a spin and check if some of the other classes needs to be adjusted too.

**Comment by Jako** [comment]
I just have read the scss code. There is no width adjustment for a text TV. Only a textarea TV has a `width: 100%!important;`, which should do the job.

**Comment by OptimusCrime** [comment]
I'll try to test this properly. I am still a bit unsure how this works.

**Comment by Mark-H** [comment]
This habit of yours to submit PRs that other people made, without knowing how to test it, is interesting @OptimusCrime ;)

**Comment by Mark-H** [comment]
This does not fix the problem reported in #13323. The built CSS resolves to this:

```
  .x-form-item #modx-resource-main-columns .modx-tv textarea {
    box-sizing: border-box;
    width: 100% !important;
    min-width: 200px; }
  .x-form-item #modx-resource-main-columns .modx-tv input[type="text"] {
    line-height: 20px;
    height: auto; }
  .x-form-item #modx-resource-main-columns .modx-tv .x-superboxselect-input-field {
    min-width: 200px; }```

while the `#modx-resource-main-columns` should be at the front of the definition. 

Would you like to correct this @OptimusCrime or should the PR be closed?

**Pull request closed without merging**
