### PR TITLE
Fix #13382 - Checking for blocked user on password reset

### LINKED ISSUE #13382: Forgot password inactive user
### Summary
When an inactive user requests a new password he receives the email.
He we only get the notice that his account is inactive when he tries to login with his new credentials.

### Step to reproduce
Deactive an user and request new password by Forgot login

### Observed behavior
- Getting notice email send, email received, trying to login with new credentials, getting notice of inactive user.

### Expected behavior
Showing the inactive notice at the Forgot login request with: This account is inactive, please contact your administrator. 

### Environment
Every modx revolution install.

### PR DESCRIPTION
**Pull request by ilyautkin**
### What does it do?
In manager login page checking if user is blocked and show error message

### Why is it needed?
Don't need to reset password for inactive and blocked users

### Related issue(s)/PR(s)
Issue #13382

### CODE REVIEW

**Comment by ilyautkin** [comment]
The Travis build failed because of the settings error. Problem not in PR.

**Comment by opengeek** [comment]
This is essentially a new feature because it adds a new function to modUser not available in previous releases of 2.5.x. This needs to target 2.x branch. Can you please edit the PR to target 2.x @ilyautkin?

**Comment by ilyautkin** [comment]
Method checkIsBlocked is restored in login-processor. Maybe someone call it method from own code.

**Comment by theboxer** [comment]
Seems like more changes - irrelevant to this feature - are part of this PR. Could you clean the PR so it contains only relevant commits, or close this one and submit new one?

**Comment by Mark-H** [comment]
Any thoughts on @theboxer's comment @ilyautkin?

**Comment by OptimusCrime** [comment]
@ilyautkin Are you going to fix the remaining issues, or can I open up a new PR for this?

**Comment by ilyautkin** [comment]
@OptimusCrime I couldn't find a solution for this problem. Can you close this PR, maybe?

**Comment by Mark-H** [comment]
Closing per your request @ilyautkin - if you need help with some git-fu, please feel free to ask in the MODX community slack.

**Pull request closed without merging**
