### PR TITLE
Fixing container urls and redirecting index.php to home url #12465

### PR DESCRIPTION
**Pull request by sdrenth**
### What does it do?
Redirects /index.php to site start URL and container resources URL's without trailing slash are now being redirected to container resource URL with trailing slash.

For example:
- https://www.example.com/index.php will be redirected to: https://www.example.com/
- When visiting https://www.example.com/container the URL will become https://www.example.com/container/

### Why is it needed?
Container resources could be visited on both url's, for example:
- https://www.example.com/container
- https://www.example.com/container/

And a user was able to visit the homepage with following URL, where it would be nicer if the user was redirected to the site start url instead of visiting the page as index.php:
- https://www.example.com/index.php

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/issues/12465

### CODE REVIEW

**Comment by Mark-H** [comment]
Aside from the test failure on PHP 5.3 (which is still supported, sorry! :P), wouldn't this be better when done as a plugin?

**Comment by sdrenth** [comment]
@Mark-H What do you mean by doing it as a plugin? Making some kind of extra for it or shipping a default plugin with a fresh modx install or am I missing something? ;)

Has there been talked about upping the minimum PHP version for MODX 2.6 to 5.4? I'm asking this in relation to issue https://github.com/modxcms/revolution/issues/13289 and PR https://github.com/modxcms/revolution/pull/13581

**Comment by Mark-H** [comment]
As an extra is what I meant ;)

I don't think the PHP version is planned to go up in 2.6? For the zero byte stuff we can update the minimum from 5.3.3 to 5.3.4, that's no big deal, but AFAIK there's no decision on moving to 5.4 in 2.6 yet.

**Comment by sdrenth** [comment]
I think it should be in the core and should not be an extra, but I'd like to hear some more opinions about this ;)

If more people think this should be fixed in the core then I'll fix the PR to be compatible with 5.3

**Comment by OptimusCrime** [comment]
I think this is a pretty cool feature. Inconsistent slashes are terrible. +1 from me.

**Comment by rthrash** [comment]
I'm a fan of this also. Great job!

**Comment by OptimusCrime** [comment]
Fix the test and I'll take a look at it :)

**Comment by shamarin** [comment]
It should be in core by default.

**Comment by sdrenth** [comment]
I've fixed the code to pass the tests

**Comment by shamarin** [comment]
Great. For me it works now on php 7.1. On container resources it gives 301 redirect without slash and 302 redirect on index.php.

**Comment by opengeek** [comment]
It is expected behavior with strict URL handling for containers to be redirected to the URL with the container_suffix, so that is technically a bug fix to the core if it were to depend on the setting. I'm not convinced on the index.php handling and am wondering if we could somehow separate that into a separate PR, perhaps with its own configuration setting? Those are my thoughts.

**Comment by shamarin** [comment]
Why this fix is not included to 2.6.0 version and is moved to 2.7.0?

**Comment by opengeek** [comment]
Because there have been some suggestions made and we are awaiting feedback from the author. It needs additional work before being accepted.

**Comment by shamarin** [comment]
Maybe to include container resources bug fix in 2.6.0 version as it has long lasting high priority bug and redirect from index.php as an option to include in next release? That's my thoughts about this.

**Comment by sdrenth** [comment]
@opengeek Sorry for my late reply, I could also add a system setting for redirecting the index.php and set it default to no, so that the default behaviour will not change and why cant we keep these changes in this PR instead of creating a separate PR for the index redirect?

**Comment by Mark-H** [comment]
Unfortunately, this isn't ready to get merged, as it causes an infinite redirect if friendly_urls is disabled. 

> why cant we keep these changes in this PR instead of creating a separate PR for the index redirect?

It's best to keep PRs as small as possible. In this case, I can't accept any of the PR because the index.php redirect breaks non-friendly url usage. Had you sent 2 different PRs, one for the index.php and one for the container fix, I could've at least merged the container one ;)

Would you like to update the PR to fix the index.php infinite redirect @sdrenth? If not I'll go ahead and close it and wait for a new one.

**Comment by Mark-H** [comment]
#13142 also fixes the container suffix handling, as does #13142.

**Comment by Mark-H** [comment]
Closing as #13142 has been merged that resolves the container issue - please submit a new PR for other issues.

**Pull request closed without merging**
