### PR TITLE
Adding linting styles

### PR DESCRIPTION
**Pull request by Ibochkarev**
### What does it do?
Adds basic config for stylelint with Prettier rules, AirBnB code guide and rational order.

### Why is it needed?
For style linting that not only catches errors, but also helps you adhere to conventions on coding style and practices. Also added a Git hook to run the linter only for changed files when creating a commit.

Example report:

``` shell
sass/components/_primary-button.scss
  2:3  ✖  Replace "··transition:·background-color·" with "transition:·background-color·0"   prettier/prettier     
  3:1  ✖  Delete "··"                                                                       prettier/prettier     
  3:5  ✖  Expected "background" to come before "transition" in group "Visual"               order/properties-order
  4:3  ✖  Delete "··"                                                                       prettier/prettier     
  5:1  ✖  Delete "··"                                                                       prettier/prettier     
  5:5  ✖  Expected "color" to come before "box-shadow" in group "Typography"                order/properties-order
  7:1  ✖  Replace "····" with "··"                                                          prettier/prettier     
  8:1  ✖  Delete "··"                                                                       prettier/prettier     
  9:1  ✖  Delete "··"                                                                       prettier/prettier     
 10:1  ✖  Delete "····"                                                                     prettier/prettier     
 11:5  ✖  Delete "····"                                                                     prettier/prettier     
 12:1  ✖  Delete "····"                                                                     prettier/prettier     
 12:9  ✖  Expected "color" to come before "box-shadow" in group "Typography"                order/properties-order
 13:1  ✖  Delete "··"                                                                       prettier/prettier     
 15:3  ✖  Delete "··"                                                                       prettier/prettier     
 16:1  ✖  Delete "··"                                                                       prettier/prettier     
 17:1  ✖  Delete "····"                                                                     prettier/prettier     
 18:1  ✖  Replace "········" with "····"                                                    prettier/prettier     
 19:1  ✖  Delete "····"                                                                     prettier/prettier     
 19:9  ✖  Expected "color" to come before "box-shadow" in group "Typography"                order/properties-order
 20:3  ✖  Delete "··"                                                                       prettier/prettier     
 22:1  ✖  Replace "····" with "··"                                                          prettier/prettier     
 23:1  ✖  Delete "··"                                                                       prettier/prettier     
 24:1  ✖  Delete "··"                                                                       prettier/prettier     
 25:1  ✖  Delete "····"                                                                     prettier/prettier     
 26:5  ✖  Delete "····"                                                                     prettier/prettier     
 27:1  ✖  Delete "····"                                                                     prettier/prettier     
 27:9  ✖  Expected "color" to come before "box-shadow" in group "Typography"                order/properties-order
 28:1  ✖  Replace "········opacity:·" with "····opacity:·0"                                 prettier/prettier     
 29:1  ✖  Delete "····"                                                                     prettier/prettier     
 30:1  ✖  Delete "··"                                                                       prettier/prettier     

sass/components/_secondary-button.scss
   7:3   ✖  Expected "color" to come before "box-shadow" in group "Typography"                       order/properties-order
   9:3   ✖  Expected "display" to come before "cursor" in group "Box Model"                          order/properties-order
  12:3   ✖  Expected "padding" to come before "line-height" in group "Box Model"                     order/properties-order
  13:3   ✖  Expected "position" to come before "padding" in group "Positioning"                      order/properties-order
  15:32  ✖  Insert "0"                                                                               prettier/prettier     
  27:5   ✖  Expected "color" to come before "background-repeat" in group "Typography"                order/properties-order
  29:5   ✖  Expected "font-size" to come before "cursor" in group "Typography"                       order/properties-order
  32:5   ✖  Expected "height" to come before "line-height" in group "Box Model"                      order/properties-order
  33:5   ✖  Expected "min-width" to come before "height" in group "Box Model"                        order/properties-order
  45:5   ✖  Expected "position" to come before "padding-right" in group "Positioning"                order/properties-order
  45:14  ✖  Insert "·"                                                                               prettier/prettier     
  49:7   ✖  Expected declaration to come before at-rule                                              order/order           
  51:7   ✖  Expected "font-size" to come before "content" in group "Typography"                      order/properties-order
  52:7   ✖  Expected "margin-top" to come before "font-size" in group "Box Model"                    order/properties-order
  53:7   ✖  Expected "position" to come before "margin-top" in group "Positioning"                   order/properties-order
  53:26  ✖  Replace "·top:·50%;" with "⏎······top:·50%;⏎·····"                                       prettier/prettier     
  59:7   ✖  Expected "border-right-width" to come before "border-right-style" in group "Visual"      order/properties-order
  60:7   ✖  Expected "padding-right" to come before "border-right-width" in group "Box Model"        order/properties-order
  70:5   ✖  Expected "color" to come before "box-shadow" in group "Typography"                       order/properties-order
  81:5   ✖  Expected "color" to come before "box-shadow" in group "Typography"                       order/properties-order
  98:5   ✖  Expected "color" to come before "background-color" in group "Typography"                 order/properties-order
 100:14  ✖  Insert "0" 
```

Before:

``` scss
@mixin shaded-box($borderW:3px,$borderC:$lighterGray) {
	border:$borderW solid $borderC;
	border-radius:$borderW;
	padding:0;
}

%shaded-tab-box {
	#modx-tv-tabs {
		.x-tab-panel-header { 
			border-width:0 !important; /* #shame */
		}
	}
	.x-tab-panel-bwrap {
		.x-tab-panel-bwrap {
			border-width:0 !important; /* #shame */
		}
	}
}
```

After:

``` scss
@mixin shaded-box($borderW: 3px, $borderC: $lighterGray) {
  border: $borderW solid $borderC;
  border-radius: $borderW;
  padding: 0;
}

%shaded-tab-box {
  #modx-tv-tabs {
    .x-tab-panel-header {
      border-width: 0 !important; /* #shame */
    }
  }
  .x-tab-panel-bwrap {
    .x-tab-panel-bwrap {
      border-width: 0 !important; /* #shame */
    }
  }
}
```

### How to test
The `npm run stylelint` command will launch the linter and print a list of errors to the console, and `npm run stylelint:fix` will additionally fix the errors available for auto-correction.

**Configuring VS Code**

In order for VS Code to highlight errors in styles in accordance with the stylelint configuration, you need to install the stylelint plugin in VS Code, as well as add settings for the workspace in VS Code `.vscode/settings.json`:

``` json
{
   "scss.validate": false,
   "css.validate": false,
   "less.validate": false,

    "editor.codeActionsOnSave": {
      "source.fixAll.stylelint": true
    },
  }
```

**Configuring phpStorm**: https://www.jetbrains.com/help/phpstorm/using-stylelint-code-quality-tool.html

### Related issue(s)/PR(s)
#14311

### CODE REVIEW

**Comment by JoshuaLuckers** [comment]
I have some concerns about husky 5's license:
> For a limited time, husky 5 will be released under[ License Zero's Parity](https://paritylicense.com/) License. It will be MIT again later.

Source: https://dev.to/typicode/what-s-new-in-husky-5-32g5

Screen Shot 2021-03-12 at 11 51 34

> To use this new version at work, you can become a sponsor on GitHub Sponsors or Open Collective

@rthrash @opengeek  can you guys check out the licensing?

**Comment by Mark-H** [comment]
Looks like Husky is only used for a local pre-commit hook. If we add the validation into github actions so it fails on things that aren't properly formatted, that would also work wouldn't it?

**Comment by Ibochkarev** [comment]
> Looks like Husky is only used for a local pre-commit hook. If we add the validation into github actions so it fails on things that aren't properly formatted, that would also work wouldn't it?

https://github.com/marketplace/actions/lint-action for example

**Comment by JoshuaLuckers** [comment]
> Looks like Husky is only used for a local pre-commit hook. If we add the validation into github actions so it fails on things that aren't properly formatted, that would also work wouldn't it? 

Yes, using GitHub actions has my preference for this.

**Comment by Ibochkarev** [comment]
@Mark-H @JoshuaLuckers I can send a PR with the addition of an action for checking and automatic fixing according to the written error rules.  this will be a good start, then it can be added for js and php formatting.

**Comment by theboxer** [comment]
I like this PR, lints are good! 

I'd say it's better to use both - husky & github action. The local precommit hook will prevent you from even committing a code that's not well-written. The github action is there as a safety check - in case you get around a local check.

@Ibochkarev To autoinit husky, you'll have to add `"prepare": "husky install"` to the package.json scripts

**Comment by JoshuaLuckers** [comment]
> I like this PR, lints are good! 
> 
> 
> 
> I'd say it's better to use both - husky & github action. The local precommit hook will prevent you from even committing a code that's not well-written. The github action is there as a safety check - in case you get around a local check.
> 
> 
> 
> @Ibochkarev To autoinit husky, you'll have to add `"prepare": "husky install"` to the package.json scripts

Husky might be an issue because of the license.

**Comment by theboxer** [comment]
@JoshuaLuckers in the license they state it's free for open source so I believe we qualify

**Comment by JoshuaLuckers** [comment]
> @JoshuaLuckers in the license they state it's free for open source so I believe we qualify

Yes it's free, but I have some concerns about compatibility with the license MODX uses. Also what this license means for third party's that develop commercial stuff for MODX.

> This license allows you to use and share this software for free, but you have to share software that builds on it alike.


Especially the "alike". See also the "contribute" part: https://paritylicense.com/versions/7.0.0

**Comment by JoshuaLuckers** [comment]
@Ibochkarev can you upgrade Husky to 6.0.0? https://github.com/typicode/husky/releases/tag/v6.0.0

**Comment by theboxer** [comment]
@Ibochkarev or to version 7, lol

**Comment by theboxer** [comment]
and just for a note, the license discussion is not relevant anymore, as husky is back to MIT license for everyone.

**Comment by JoshuaLuckers** [comment]
Thanks @Ibochkarev for taking the first steps. I think it's better to do things step by step and therefore I think PR #16321 is a better way to move forward.

I do appreciate your work and I would love to see your input/opinion on PR #16321

**Pull request closed without merging**
