### PR TITLE
Reordered the navigation tabs in the "User Group"

### PR DESCRIPTION
**Pull request by Ruslan-Aleev**
### What does it do?
1) Reordered the navigation tabs in the "User Group".

Made them more logical:
- You first create a group
- Then configure permissions for group
- Then add users to the group, if it need
- Other settings

**After:**
users_groups_tab_2

Before:
users_groups_tab_1

2) Changed lexicons to more specific

users_groups_lexicons

### Why is it needed?
UI/UX fix

### CODE REVIEW

**Review by JoshuaLuckers — APPROVED** [review]

**Comment by rthrash** [comment]
This is a really nice improvement and _much_ more logical. Thanks! For those looking to find/reproduce this, it's done by right-clicking on an existing user group in the ACL list: Settings (cog) at the lower left > Access Control Lists > right-click Administrator (or other ACL group name). 

I would suggest, though, we rename the Permissions top tab to Access Permissions. The vertical tabs wrap awkwardly on that tab, and "Access" is redundant here (and inconsistently capitalized). As a general rule, anywhere "Here you can…" is encountered, as in the screenshot below, it can be written more directly/clearly, usually by simply eliminating "here you can": 

> Set the Contexts this User Group can access. 

User Group: Administrator | MODX Revolution 2020-07-23 22-49-41


While the following potentially expands the scope of this PR from its original intention … I also wonder if the parent menu could use some UX love itself. There's a lot of extra bling here that distracts from the UI, and a lot of hidden functionality. 

Access Control Lists | MODX Revolution 2020-07-23 22-38-30

First, suggested new title/description so people will know what to expect and how to use this section without having to visit the documentation:

> Click the group names to manage membership and the gear-icon to update its settings. (User counts in parenthesis. Anonymous means any visitor without a login.)

If we adopt this suggested lexicon change, the "(anonymous)" group should have the parenthesis removed from around it. If anything, it should have an infinity symbol or asterisk in parenthesis beside it, and possibly re-labeled "Unauthenticated". Since "Administrator" is capitalized, I vote for also capitalizing "Anonymous" for consistency.

> Anonymous (*)

Next, the drop-down triangle in the header doesn't function; the up/down arrows above it that do are a strange deviation from most conventions. But … why would you want to collapse a single list in the first place? 

The title above the groups is redundant with the tab itself. 

I wonder what state would ever require using the refresh tree icon, though it appears to work as advertised. I vote for eliminating it. People can ctrl-r to refresh if needed.

Losing five icons/buttons/action items/distractions, and clarifying the language should make working in this complex part of Revo a little bit simple.

With losing all the redundant header stuff, the "new user group" button could be moved to the description row/top-right.

Finally—and most importantly IMO—each User Group row should have a clearly visible edit icon. Otherwise, it's hard to figure out how to edit existing user groups because it's hidden behind a right-click _which doesn't exist on mobiles/tablets_. And while not shown on the markup screenshot below, do we need to collapse the sidebar also? I vote to eliminate its collapsibility.

Access Control Lists | MODX Revolution 2020-07-23 22-43-55

**Comment by Ruslan-Aleev** [comment]
@rthrash Thanks for the detailed comment. You are right, for "User Groups" I will correct the tab names and descriptions later.

As for renaming `(anonymous)` to something else, then the question arises: How to call it more clearly? Maybe `(unauthorized)`? The name `Unauthenticated` is not very clear to me. Also, I would leave parentheses and lowercase letters (to draw attention), since the MODX manager has similar entities that are displayed in a similar way, for example, an empty resource template - `(empty)`.

As for the output of groups in the form of a tree, we already had a discussion and even some fixes, see https://github.com/modxcms/revolution/issues/15148 and https://github.com/modxcms/revolution/pull/15159 :)

**Comment by opengeek** [comment]
I've attempted to rebase these changes on the latest and there are too many other changes to this js for me to work out easily. If you have time, can you take a look @Ruslan-Aleev and push it if you can work it out?

**Comment by Ruslan-Aleev** [comment]
Yes, I'll deal with it later. But here the strange behavior of github, I just move the tab in the file, at first everything is fine, but after a while github sees these changes as conflicting.
I have already redone twice, why the changes are marked as conflicts is not clear for me.

**Comment by Ruslan-Aleev** [comment]
@opengeek Done

**Review by rthrash — COMMENTED** [review]
Adding a second review based on my comments here: https://github.com/modxcms/revolution/pull/15149#issuecomment-663341168 (and ultimately for a how to do a review article) … All in all I think it's a net positive and can go.

**Pull request merged**
