### PR TITLE
cleanAlias on base of context settings

### PR DESCRIPTION
**Pull request by Jako**
### What does it do?
Add the `friendly_alias_translit` context/system setting as option to the filterPathSegment call.

### Why is it needed?
Before this patch, the cleanAlias method called the filterPathSegment method without the `friendly_alias_translit` context/system setting. That way always the system setting was used. 

This patch will add a possible `friendly_alias_translit` context setting to the filterPathSegment method call. Since requesting a context setting will default to the system setting, if no context setting is available and the `friendly_alias_translit` context setting could be overridden by the options of the cleanAlias method, there occurs no BC with the patch.

### Related issue(s)/PR(s)
#13046

### CODE REVIEW

**Comment by OptimusCrime** [comment]
Nice work, but the tests are broken.

**Comment by Jako** [comment]
I have noticed that too. Fixed now.

**Comment by opengeek** [comment]
Should this not just merge all context settings and pass those as options so all of the various options could favor context-specific overrides?

**Comment by Jako** [comment]
You are right. I will add that to the PR.

**Comment by Jako** [comment]
Done and tested well here.

**Pull request merged**
