### PR TITLE
Files tree, when the directory is empty the arrow wont appear (13309) #modxbughunt

### PR DESCRIPTION
**Pull request by Oetzie**
### What does it do?
Files tree, when the directory is empty the arrow wont appear

### Why is it needed?
The arrow in the file tree was visible on empty directories, changed it so it wont appear any more on empty directories

### Related issue(s)/PR(s)
n/a

### CODE REVIEW

**Comment by rtripault** [comment]
Thanks for the contribution!

I'm just not sure that's something we want (performance wise)... otherwise :+1: for the UX

**Comment by Mark-H** [comment]
That's a good point.. especially for remote media sources like S3 this might make it much slower. Hmm, difficult trade-off speed vs usability..

**Comment by gpsietzema** [comment]
#13166

**Comment by opengeek** [comment]
Any additional input on this from anyone?

**Comment by gpsietzema** [comment]
I'm not sure if it is actually impacting performance. Checking the code it looks like one simple file-check. Not sure how heavy 'getContainerList' is though.

**Comment by Mark-H** [comment]
getContainerList on every single result is going to request the contents of all subdirectories... try browsing a S3 media source and tell me again that this wont affect performance ;) 

It would probably be better to patch this directly in the media source getContainerList method. That way it could be handled differently for non-file media sources that are much slower than the file one.  

Given the small impact this has on the user (the negative aspect being that they might click on an empty directory to see it is empty), I'm going to propose this does not gets merged unless the performance impact, especially on remote media source types, is minified by not calling getContainerList just to count the children.

**Comment by OptimusCrime** [comment]
I would be in favor of implementing this for file system media sources and NOT the other types.

**Comment by Mark-H** [comment]
I'm going to close this for now for the reasons in my earlier comment, but feel free to suggest alternative approaches in a new PR.

**Pull request closed without merging**
