### PR TITLE
Enhancement of branding in Setup

### PR DESCRIPTION
**Pull request by mindeffects**
### What does it do ?

Changes the logo PNG to SVG and removes the grayscale shade which makes the logo look dull
### Why is it needed ?

Because: NEVER TOUCH THE LOGO! :-D

### CODE REVIEW

**Comment by OptimusCrime** [comment]
+1 for svg, but it is missing the copyright icon?

**Comment by mindeffects** [comment]
Nope. 1:1 like the one from modx.com
Actually, it is identical because I took it from there. ;-)

**Comment by OptimusCrime** [comment]
Ah, okey, I guess that should be okey then ;)

**Comment by TheBoxer** [comment]
Cherry picked to master & merged to develop.

**Pull request closed without merging**
