### PR TITLE
Bug 12542 getTVValue/setTVValue consider numeric TV names as IDs #modxbughunt

### PR DESCRIPTION
**Pull request by pbowyer**
### What does it do?
Previously any strings received by getTVValue/setTVValue were considered to be the name of a template variable. This caused problems when an identifier like `"240"`. 

### Why is it needed?
As PHP users are used to typecasting on the fly, and as users are unlikely to name TVs as numbers, I've made it check for numeric TV names and treat them as strings.

### Related issue(s)/PR(s)
Let us know if this is related to any issue/pull request (see https://github.com/blog/1506-closing-issues-via-pull-requests)

#12542

### CODE REVIEW

**Comment by OptimusCrime** [comment]
Good! You can write the line 

```
$byName = (is_numeric($pk)) ? false : true;
```

as 

```
$byName = !is_numeric($pk));
```

Which I find more readable.

**Comment by pbowyer** [comment]
Do the MODX coding standards have anything to say? I prefer to be explicit, but happy to change to whatever fits.

**Comment by OptimusCrime** [comment]
There is none. I just saw the original issue and @wshawn suggested code. I prefer avoiding conditional operator in cases where the value can be directly inferred from the original call. All you really do here is negate the original value.

**Comment by pbowyer** [comment]
There we go, I've modified the code

**Comment by OptimusCrime** [comment]
Awesome @pbowyer :)

**Comment by Mark-H** [comment]
Thanks @pbowyer!

**Pull request merged**
