### PR TITLE
fix issue Duplicating a context with a a lot of resources may trigger php memory error ( #13217)

### PR DESCRIPTION
**Pull request by FerX**
### What does it do?
replace getCollection with getIterator

### Related issue(s)/PR(s)
Duplicating a context with a a lot of resources may trigger php memory error #13217

### CODE REVIEW

**Comment by OptimusCrime** [comment]
Awesome contribution @FerX :) 

However, in the issue it was reported that just changing this did not solve the problem. If I recall correctly from the conversation at Slack it was due to the amount of template variables assigned to each resource. Looking through the code that does the `modResource->duplicate` I see that that logic is wrapped in xPDOs `getMany` method which is not that easy to change. It might be a bigger job fixing that too, and perhaps outside the scope of this PR.

I'll leave this here for the core members to see. Perhaps they know better.

**Comment by FerX** [comment]
Thanks @OptimusCrime.
I did not see the comment.
I reviewed the code.
I do not think the problem are the TVs, but all children of resource.
if you look at this code recursively
https://github.com/modxcms/revolution/blob/2.x/core/model/modx/modresource.class.php#L1066-L1076
if resources have many sons charge them all in memory.
We have to implement even here iterations...

**Comment by OptimusCrime** [comment]
@FerX I thought so too, but during testing and troubleshooting at Slack, changing the `getCollection` to `getIterator` alone did not solve the problems. Despite that, I still think this improvement is smart to avoid similar problems in the future, but as far as I've understood it did not solve the particular problem reported in issue #13217 .

**Comment by FerX** [comment]
last commit resolve the problem. (I think)

**Comment by OptimusCrime** [comment]
Confirmed to solve the reported problem.

**Comment by FerX** [comment]
What do I do accept this pull request?

**Comment by OptimusCrime** [comment]
@FerX You dont need to do anything at this point. The people that run this repository will test your PR and merge it.

**Comment by OptimusCrime** [comment]
@FerX You should still keep the PR open :)

**Comment by FerX** [comment]
How can I fix the problem checks failed ?
not look like a problem of my change.

**Comment by OptimusCrime** [comment]
There is nothing you need to do. The unit tests are currently broken.

**Comment by rtripault** [comment]
Well, if you force push to your branch (like after squashing your commits), the tests should pass...
But the errors are not related to your changes, indeed

**Comment by OptimusCrime** [comment]
Oh, I was not aware that the tests were fixed. Rebasing and force pushing would fix the failing checks, but it is not that important.

**Comment by FerX** [comment]
This is a bug. Why wait for v2.6.0?

**Comment by OptimusCrime** [comment]
Can this not be merged? I agree that this should be included in the 2.5.x release.

**Comment by opengeek** [comment]
@FerX have you signed the CLA? Can you provide your username for login at modx.com if so? Or can you sign it by logging in and going to https://develop.modx.com/contribute/cla/ if not?

**Comment by FerX** [comment]
@opengeek mi username in modx.com is: `ferx77`

**Comment by opengeek** [comment]
@FerX I found your username, but there is no indication that you have signed the CLA. This is required for us to accept your contributions to the project. Please let me know when you have signed it and I will finish testing this PR.

**Comment by FerX** [comment]
Ok. sorry.
I have sign  now in https://develop.modx.com/contribute/cla/

**Comment by Mark-H** [comment]
Thank you @FerX for your contribution :)

**Pull request merged**
