### PR TITLE
Clean up legacy core/model files

### PR DESCRIPTION
**Pull request by JoshuaLuckers**
### What does it do?
Clean up legacy core/model directories and files.

### Why is it needed?
When upgrading from 2.x to 3.x most people merge directories and replaces files. 
To prevent issues down the road it's best to clean up the old core/model directories and files.

### Related issue(s)/PR(s)
none

### CODE REVIEW

**Comment by Mark-H** [comment]
That's a recursive function, so just specifying `core/model/modx` should do fine (and be easier to grasp).

**Comment by rthrash** [comment]
This pull request has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/modx3-nightly-installed-now-manager-displays-error/1705/9

**Comment by JoshuaLuckers** [comment]
@Mark-H there is 1 file that should stay there, modx.class.php. That’s why I didn’t delete the whole folder.

**Comment by Mark-H** [comment]
Ah, right. Forgot about that.

**Review by Mark-H — APPROVED** [review]

**Review by opengeek — APPROVED** [review]

**Pull request merged**
