### PR TITLE
Disable actionsColumn on grids without context menu

### LINKED ISSUE #14862: 3.x The context menu with a gear is shown in a grid in which it should not be
### Summary
Unfortunately, the new and cool menu is shown on almost all grids, even in which there are no actions, for example (`/manager/?a=source`):

gear-menu

This is very confusing. Need additional check.
We partially discussed this in PR - https://github.com/modxcms/revolution/pull/14806#issuecomment-545055982, created a separate issue, so that the bug is not lost.

### Environment
MODX 3

### PR DESCRIPTION
**Pull request by theboxer**
### What does it do?
Disables actions column on grids without context menu.

### Why is it needed?
Clicking the gear icon has no effect on these...

### Related issue(s)/PR(s)
Resolves #14862

### CODE REVIEW

**Comment by Ruslan-Aleev** [comment]
Are you sure about this file https://github.com/modxcms/revolution/blob/7b3d2be5fd51e09e3a321f84897342baac3d806f/manager/assets/modext/widgets/source/modx.panel.sources.js?
Isn't this a list of file sources in a` /manager/?a=source` section?

**Comment by Mark-H** [comment]
Why the removed file?

**Comment by theboxer** [comment]
Ha, sorry about that... should be separate PR but it sneaked there. It's deprecated for ages and was used nowhere...

**Review by JoshuaLuckers — DISMISSED** [review]
Please remove the file in a separate commit

**Comment by JoshuaLuckers** [comment]
In addition to my request for change: This makes it easier down the road to figure out why it was relived.

**Review by Mark-H — APPROVED** [review]

**Review by opengeek — CHANGES_REQUESTED** [review]
There are a couple of conflicts with this now that some other JS-related commits have been merged. I've asked @theboxer to revisit these conflicts tomorrow.

**Review by opengeek — APPROVED** [review]

**Pull request merged**
