### PR TITLE
Login lexicon - Good Night changed to Good Evening

### PR DESCRIPTION
**Pull request by muzzwood**
Redoing this PR as the last one had an extra commit unintentionally.

### What does it do?
Changes the word night to evening

### Why is it needed?
Good night is used as a farewell rather than a greeting.

### Related issue(s)/PR(s)
PR: #14471
Issue: #14470

### CODE REVIEW

**Review by JoshuaLuckers — APPROVED** [review]

**Comment by Mark-H** [comment]
Hey @digitalpenguin, GitHub is listing you as a first-time contributor. Have you signed the CLA for MODX before, and if not can you please do that? https://develop.modx.com/contribute/cla/

If you have please let me know your MODX.com username :)

**Review by Mark-H — APPROVED** [review]

**Comment by muzzwood** [comment]
Hi @markh, yes I've signed it and have had a couple of PRs merged previously. I've also noticed I'm not labeled as a contributor so perhaps it's a related issue.
My MODX username is muzzstick and on slack I'm known as Murray. ;)

**Comment by Mark-H** [comment]
Interesting. Maybe that's because you contributed to 3.x and 2.x is still set as the primary branch, so GitHub doesn't check other branches?

I also recalled seeing other things from, so just wanted to make sure :)

**Comment by muzzwood** [comment]
Right! That's a good possibility, I've only contributed to 3.x I think.

**Pull request merged**
