### PR TITLE
Enhancement: Add package events

### PR DESCRIPTION
**Pull request by exside**
### What does it do?

Adds 3 system events that are fired when interacting with the package manager: **OnPackageInstall** (also fired when a package is updated), **OnPackageUninstall** and **OnPackageRemove**

Added these events to the build script for proper setup as well.
### Why is it needed?

Can be helpful to trigger additional scripts when interacting with packages.
### Related issue(s)/PR(s)

None that I knew of.

### CODE REVIEW

**Comment by Mark-H** [comment]
This would be nice for Gitify to use :)

**Comment by rtripault** [comment]
While i'm not seeing any use case (please, feel free to shed some light), nothing against the idea.

Just some "concerns" : 

1. events appears to be triggered when actions have been performed, so i would rather go event names like `OnPackageInstalled`, `OnPackageRemoved`, `OnPackageUninstalled`
2. `OnPackageInstall` is also occurring on upgrades. Could be "interesting" to distinguish the events (`modTransportPackage::previousVersionInstalled()` could be helpful i guess)
3. why passing the `modTransportPackage` as an array instead of the object ?

**Comment by Mark-H** [comment]
The use case for Gitify that came to mind is that it could keep better track of installed by packages. It has a list of packages in its `.gitify` file of packages that should be installed when deploying. This could be kept up to date easier when these events are added. 

Concern 1 seems to be inconsistent with existing naming patterns (e.g. the first in the file are OnPluginEventBeforeSave and OnPluginEventSave, not OnPluginEventSave and OnPluginEventSaved). Agreed on the other two concerns though, any thoughts @exside?

**Comment by exside** [comment]
Updated the PR based on the feedback, not sure if that 'action' thing in the install event acutally does what it's intended to, didn't have time to test yet...or should I just make an "update": true||false from that?

**Comment by rtripault** [comment]
Woops, sorry for the late reply here... you are absolutely right Mark, better keep the existing naming pattern.

@exside if we want to be consistent, i guess a `mode` key would be best (that's the one used for existing `On*Save` events)

**Comment by Mark-H** [comment]
Thanks @exside, merged into 2.x for inclusion in 2.6. 

Also added documentation stubs at https://docs.modx.com/revolution/2.x/developing-in-modx/basic-development/plugins/system-events/onpackageremove, https://docs.modx.com/revolution/2.x/developing-in-modx/basic-development/plugins/system-events/onpackageinstall and https://docs.modx.com/revolution/2.x/developing-in-modx/basic-development/plugins/system-events/onpackageuninstall

**Pull request merged**
