### PR TITLE
Make MODX Revolution to work with SQLite3

### PR DESCRIPTION
**Pull request by Alexij2**
### What does it do?
Make MODX Revolution to work whith SqLite v3.

### Why is it needed?
Using MODX Revolution whithout mysql server.
## Information
It is still necessary to test, because there are errors in the logs.
(I have successfully installed on version 2.8.)
**Install as usual /setup.**

- When setting up the database, select - sqlite.
- Do not enter anything into the connections - click to check the connection.
test the connection in the database.
- If everything is successful, enter the data for the admin as usual and set it to the end.
- Log in to the admin panel if there are no errors.
- the database file will be located in the core/data/ folder and be closed from unexpected guests through htpasswd. Or move this file outside of www. The path of the file is written in the core/config config.

### CODE REVIEW

**Comment by Alexij2** [comment]
@cla-bot check

**Review by JoshuaLuckers — CHANGES_REQUESTED** [review]
**Thank you** for taking time to help make MODX better.

Adding support for a new database engine is a _major change_, something that we cannot add in a minor release (2.x) but we can add in a _new version_ (3.0). 

To increase the chances of your changes being approved:
- Make your changes work in 3.x.
- Use multiple commits (e.g a commit to group changes related to the schema/model changes, one for setup changes etc). 
- Keep the copyright headers in existing code and add them to new files.

If the PR needs additional work it’s better to create a draft PR and add a task list.

We are happy to help if needed, don't hesitate to ask for help if needed!

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to create this PR. ~Recently we decided to drop support for MSSQL therefore I'm closing this PR as well.~

Recently we decided to drop support for sqlsrv in 3.x for several reasons, one being us unable to maintain it.
I'm closing this issue because it's a) targeting 2.x and b) we most likely won't add support for sqlite in 3.x. for similar reasons as why we dropped support for sqlsrv.

**Comment by opengeek** [comment]
> Thanks for taking time to create this PR. ~Recently we decided to drop support for MSSQL therefore I'm closing this PR as well.~
> 
> Recently we decided to drop support for sqlsrv in 3.x for several reasons, one being us unable to maintain it. I'm closing this issue because it's a) targeting 2.x and b) we most likely won't add support for sqlite in 3.x. for similar reasons as why we dropped support for sqlsrv.

I'm hoping we **will** add sqlite and pgsql support in 3.x, to be honest.

**Pull request closed without merging**
