### PR TITLE
Adds a RewriteRule to the example htaccess

### LINKED ISSUE #13925: Add a RewriteRule for blocking hidden directories to the example htaccess
### Summary
Block hidden directories (except for .well-known) by adding a rewrite rule to the example htaccess.
```
RewriteRule "/\.|^\.(?!well-known/)" - [F]
```

### Step to reproduce
Download/install MODX via Git.

### Observed behavior
Dot directories, also known as "hidden directories" like .git are present at the file system and might be exposed to the public.

### Expected behavior
Hidden directories should not be exposed to the public.

### Environment
MODX 2.\*, MODX 3.0

### PR DESCRIPTION
**Pull request by JoshuaLuckers**
### What does it do?
Adds a RewriteRule to hide dot directories from the public.

### Why is it needed?
To make things a bit more secure.

### Related issue(s)/PR(s)
Fixes #13925

### CODE REVIEW

**Comment by Jako** [comment]
IMHO it makes more sense not to deploy those folders to the host.

**Comment by JoshuaLuckers** [comment]
I agree but better be safe then sorry.

**Comment by alroniks** [comment]
I think it does not something dangerous for usual websites but makes the website a bit more secured. So I vote for this.

**Comment by Jako** [comment]
Maybe it should be disabled by default.

**Comment by Mark-H** [comment]
It's in an example file that people need to copy to use, so, it's indeed disabled by default ;)

**Comment by Jako** [comment]
Yep, but the rule itself not. Since it is a BC it should either be disabled or targeted to 3.x.

**Comment by JoshuaLuckers** [comment]
When updating an existing install the .htaccess file (if any is present) will not be overwritten. It's a manual operation.

**Review by Mark-H — APPROVED** [review]
Before this is merged someone the integrator should do a double check to make sure it behaves as expected (mostly, does `.well-known/foo.txt` remain accessible, but is `.git/foo.text` locked down), but from a code review point of view I'm happy to give this my stamp of approval. 

Thanks Joshua!

**Comment by JoshuaLuckers** [comment]
@Mark-H I did a double check myself and it seems to work fine. 
@Alroniks if you have time, will you also took a look at this? :)

**Comment by alroniks** [comment]
@JoshuaLuckers Need to find Apache anywhere at first :) Everywhere nginx used.

**Comment by OptimusCrime** [comment]
@Alroniks If you have Docker, then my [docker setup](https://github.com/OptimusCrime/modx-development-docker) might help you.

**Review by alroniks — APPROVED** [review]
Tested with Apache web server, all works fine. The content of .well-known folder ignored by rules, so scripts that requires this folder will work.

**Pull request merged**
