### PR TITLE
[3.x] Clean up some styles, less borders -> more depth, better emphasis

### PR DESCRIPTION
**Pull request by Mark-H**
### What does it do?

With this PR I'm tweaking the 3.x styles a little. This PR is focused on the overall manager frame and a little bit on the resource panel. I worked mostly on the tabs, trees, and header area. 

The primary thing I tried to do was get rid of all.the.borders. There were so many, especially in the tree and the header area, all begging for your attention, causing the manager to feel really confusing and cluttered. Where appropriate, I replaced those with more subtle shadows to convey some more depth/hierarchy instead. 

In some places (like the breadcrumbs) I just removed backgrounds and borders entirely to let it sit against the background. 

All in all, I think this simplifies and focuses the design a bit more. There are still other areas I'd like to work on (grids and introducing some more color), but that's for another day.

### Why is it needed?

The redesign is one of the key features in MODX3, but it wasn't exactly sitting right with me just yet. The early designs by Rinze were much simpler and cleaner than the latest 3.x, so while I didn't actually look up those earlier designs I did try to bring it more in line again with the simplicity that stood out to me about those designs.

### Related issue(s)/PR(s)

N/a.

### CODE REVIEW

**Comment by Mark-H** [comment]
Some screenshots for quick comparison:

## Resource update before

resource-before

## Resource update after

resource-after

## Template update before

template-before

## Template update after
template-after

**Comment by JoshuaLuckers** [comment]
I'm in favour of removing the amount of borders!

Two things I would like to note:
- I do miss the distinction in tabs after applying these changes. 
- It would also be a good idea to make the breadcrumb separator a little darker.

**Comment by Ruslan-Aleev** [comment]
Thank you, MODX becomes more beautiful :)
@Mark-H look at the styles of resources hidden from the menu and unpublished resources, in my opinion, they should be reversed, here in more detail - https://github.com/modxcms/revolution/issues/13969

**Review by JoshuaLuckers — DISMISSED** [review]

**Comment by SnowCreative** [comment]
Much better use of space. Thanks.

**Review by JoshuaLuckers — DISMISSED** [review]

**Comment by Mark-H** [comment]
Rebased to resolve a conflict.

**Review by JoshuaLuckers — APPROVED** [review]

**Comment by Jako** [comment]
Is there enough space on less wide screens (between the tabs and the buttons topright)? Otherwise the buttons could be less high.

**Comment by Mark-H** [comment]
I'm not sure if I fully understand what you're asking, but the overall layout is responsive (in a weird extjs way), and not affected by this PR. If there are responsive issues I'd be happy to take a look at that in a different PR.

**Review by opengeek — APPROVED** [review]

**Pull request merged**
