### PR TITLE
Change of the name and description in the top menu of Form Customization

### PR DESCRIPTION
**Pull request by Ibochkarev**
### What does it do?
Change of the name and description in the top menu of Form Customization

### Why is it needed?
Fix lexicon keys for name and description Form Customization in the top menu

### Related issue(s)/PR(s)
#14352

### CODE REVIEW

**Review by JoshuaLuckers — COMMENTED** [review]
I think the lexicon `bespoke_manager` and `bespoke_manager_desc` can be deleted as well.

**Comment by Ibochkarev** [comment]
@JoshuaLuckers Indeed, these lexicons are not used anywhere else.

**Review by JoshuaLuckers — DISMISSED** [review]

**Comment by Ibochkarev** [comment]
@markh please check.

**Review by Mark-H — CHANGES_REQUESTED** [review]
The [primary key for installing menu items is the `text`](https://github.com/modxcms/revolution/blob/6bae073eddcdd3f340ac066b9dd77789f05caf8f/_build/transport.core.php#L192). I think that means that the current "Manager Customization" menu item would be left in-place, without its lexicon as that's also removed, alongside a new item for FC. That seems to call for an upgrade script that removes the old bespoke_manager menu item on upgrade.

I also think this should be targeting 3.x, not 2.x?

**Comment by Ibochkarev** [comment]
This PR I close and create a new 3.x base

**Pull request closed without merging**
