### PR TITLE
Add Font Awesome 5 Solid

### PR DESCRIPTION
**Pull request by wax100**
### What does it do?
Fix some FontAwesome icons

### Why is it needed?
U can see it in Minishop2 products grid
http://prntscr.com/payxkv

After css fix http://prntscr.com/payxxr

### CODE REVIEW

**Comment by Mark-H** [comment]
The index.css file should not be edited; the source files for that are in _build/templates/default.

**Comment by wax100** [comment]
> The index.css file should not be edited; the source files for that are in _build/templates/default.

Yes, I see... look like bug in FA or I am mistaken)

**Comment by Mark-H** [comment]
It might just need to integrated differently through the sass files. Perhaps another `@import` specific for the solid icons? I'm not sure.

**Comment by Ibochkarev** [comment]
This font is already included
https://github.com/modxcms/revolution/blob/3.x/_build/templates/default/sass/index.scss#L9

image

**Pull request closed without merging**
