### PR TITLE
Fix url parameter for the config.js processor

### PR DESCRIPTION
**Pull request by Jako**
### What does it do?
Get the url parameter with $this->getProperty/$this->getProperties instead of using the not existing $scriptProperties array.

### Why is it needed?
During wrapping the code in the class in #14161, the $scriptProperties variable was not changed. It does not exist in the method process.

### Related issue(s)/PR(s)
#14161, #14802

### CODE REVIEW

**Comment by opengeek** [comment]
Thanks for taking care of this one!

**Comment by opengeek** [comment]
FWIW, this could not be applied to 3.x. If you have time and can prepare a version of this on 3.x, that'd be great. If not, I'll try and get to it later this week.

**Comment by Jako** [comment]
This was already done in 2247e4d52f393598286077e63484eee118d40e69

**Comment by opengeek** [comment]
> This was already done in [2247e4d](https://github.com/modxcms/revolution/commit/2247e4d52f393598286077e63484eee118d40e69)

Oh. Great! Thanks!

**Pull request merged**
