### PR TITLE
Add .less, .scss and .css.map as default allowed upload file types

### PR DESCRIPTION
**Pull request by OptimusCrime**
### What does it do?
Add .less, .scss and .css.map files to the default upload file types in the build process.

### Why is it needed?
Allow more trivial file types to be uploaded in the manager interface.

### Related issue(s)/PR(s)
#13574

### CODE REVIEW

**Comment by Alroniks** [comment]
@OptimusCrime Not sure but maybe it makes sense to add also `.sass`?

**Comment by OptimusCrime** [comment]
I guess. I can add it to the PR.

**Comment by Jako** [comment]
Merged into 2.x

**Comment by OptimusCrime** [comment]
I never got around to add the `sass` filetype. If there is a need for this, open a new issue.

**Comment by Jako** [comment]
I have added it to your PR, but for some reason this change was not merged (maybe I forgot to fetch it).

**Comment by OptimusCrime** [comment]
Yeah, It is missing from the merge commit: ec11f6d69681b19f4a75e91a4038a253ee82e5c8

**Pull request closed without merging**
