### PR TITLE
Move resource_uri and resource_uri_overide to page-settings-right-box-left region

### LINKED ISSUE #11854: [2.2.15] [2.3.1] [FC]  "modx-page-settings-right-box-left"  region bug?
Looking at a form customization set grid, you see that _uri_override_ and _uri_ fields are in the _"modx-page-settings-right-box-left"_ region.
modx-page-settings-right-box-left

This is the normal view when editing a resource:
modx-page-settings-right

Good, now let's disable _"modx-page-settings-right-box-left"_ region:
no-modx-page-settings-right-box-left

Hmmm, _uri_override_ and the hidden _uri_ fields are still visible, plus they are disaligned.

It seems that those fields don't really belong to the _"modx-page-settings-right-box-left"_ region as reported in FC... am I wrong? They disappear only when disabling the main region _"modx-page-settings-right"_.

### PR DESCRIPTION
**Pull request by GulomovCreative**
### What does it do?
1. Move resource_uri and resource_uri_overide to page-settings-right-box-left region on resource page
2. Fix right column margin when not displayed a left column

### Why is it needed?
If we hide the page-settings-right-box-left on fc, then the page-settings-right-box-right will have margin left

**Before:**
Screenshot from #11854

51419365-7dce8980-1bbc-11e9-907b-e0c901b65a53

**After:**

51419392-b40c0900-1bbc-11e9-81f7-85a9907f99ba

### Related issue
Closes #11854

### CODE REVIEW

**Comment by Jako** [comment]
Please don't include the compiled css/js next time.

**Comment by GulomovCreative** [comment]
> Please don't include the compiled css/js next time.

@Jako Ok, got it

**Comment by GulomovCreative** [comment]
I revert css files

**Comment by Ruslan-Aleev** [comment]
Everything works for me.

uri_check

**Review by Mark-H — APPROVED** [review]
LGTM 👍 

@GulomovCreative Have you signed the CLA before? If not, could you please do so via https://develop.modx.com/contribute/cla/, and if you have, could you please let me know the MODX.com username you signed it with? Thanks! :)

**Comment by GulomovCreative** [comment]
> LGTM 👍
> 
> @GulomovCreative Have you signed the CLA before? If not, could you please do so via https://develop.modx.com/contribute/cla/, and if you have, could you please let me know the MODX.com username you signed it with? Thanks! :)

@Mark-H No, i did not. but i signed today :) Here is my username: **gulomov**

**Comment by Mark-H** [comment]
Thanks @GulomovCreative :) Just needs at least one other integrator to approve it now.

**Review by alroniks — APPROVED** [review]

**Pull request merged**
