### PR TITLE
use sans-serif font for TV textareas (resolves #2845)

### PR DESCRIPTION
**Pull request by christianseel**
### What does it do?

Changes `font-family` for TVs of type `textarea` to `inherit` (so the default font-family of the manager, similar to normal text fields).
### Why is it needed?

Make the look of TVs whether of type text or textarea similar.
### Related issue(s)/PR(s)

Resolves #2845

Note: I didn't use grunt to make this change, because I got updated Font Awesome assets and new autoprefixer stuff which I didn't want to commit. But I took best care to integrate the code nicely.

### CODE REVIEW

**Comment by OptimusCrime** [comment]
Pretty sure you dont need to (or should) commit the changes to the .css files. These are generated for each new build and causes lots of merge conflicts.

However, I might be wrong.

Anyways, nice contribution!

**Comment by christianseel** [comment]
Wouldn't that kind of break the git version of MODX? Through I understand the potential merge conflicts…

Just let me know if I should remove the css changes before any merge.

**Comment by Mark-H** [comment]
Integrators build the assets when merging, which is a lot less of a hassle than constant merge conflicts ;)

**Comment by christianseel** [comment]
PR updated and changes on css files reverted

**Comment by pixelchutes** [comment]
This PR appears to have broken 3PC RichText TVs (e.g. `textarea` > Ace)

See #13070 for more detail.

**Pull request merged**
