### PR TITLE
Added functionality to allow javascript in the user-nav #modxbughunt

### PR DESCRIPTION
**Pull request by Oetzie**
### What does it do?
Added functionality to allow javascript in the user-nav

### Why is it needed?
Wasn't possible to use JS in the usernav.

### Related issue(s)/PR(s)
#13094

#modxbughunt

### CODE REVIEW

**Comment by Mark-H** [comment]
Do you have some suggested steps to test this? E.g. some code that couldn't run before that can be run now?

**Comment by Oetzie** [comment]
Before this fix you could not place the actions 'clear cache' or something like that under the usernav menu. Because the eval (smarty) and { triggered a php error.

**Comment by gpsietzema** [comment]
#13094

**Comment by Mark-H** [comment]
Thanks @Oetzie, merged into 2.x for 2.6.0.

**Pull request merged**
