### PR TITLE
Output filters date/strftime now accept text-formatted datetime #modxbughunt

### PR DESCRIPTION
**Pull request by pbowyer**
### What does it do?
The :date output filter/modifier needs a UNIX timestamp, which in some cases need the user to prepend the strtotime output filter, and sometimes it doesn't depending on the input.

This PR changes that so the :date output filter checks the input to see if it is a unix time stamp (integer) or a other format, and use strtotime when it is in the wrong format.

### Why is it needed?
Added flexibility. Particularly now, we don't always store dates as Unix timestamps.

### Related issue(s)/PR(s)
Let us know if this is related to any issue/pull request (see https://github.com/blog/1506-closing-issues-via-pull-requests)

#8161

### CODE REVIEW

**Comment by OptimusCrime** [comment]
Nice, but you are doing some pretty wizard-ish weak type casting here. Instead of doing ```$value = 0 + $output;``` what about the more readable ```$value = intval($output);```

**Comment by pbowyer** [comment]
@OptimusCrime That's original MODX code that is! https://github.com/modxcms/revolution/pull/13338/commits/deaee44533a3b30fc7c3fc4b8478d9c438a110b2#diff-3b43f92f730c95fab1bd225d72f76928L443

**Comment by Jako** [comment]
Maybe it is better to have a strict check for an integer with [filter_var](http://php.net/manual/de/filter.filters.validate.php). Numeric is too broad.

```
if (filter_var($output, FILTER_VALIDATE_INT) === false) {
```

**Comment by OptimusCrime** [comment]
@pbowyer Oh, I'm sorry. Still fishy code. The core is filled with weird weak type checking and casting which is prone to errors. I'm trying to get rid of these where we can. @Jako 's idea was good. It would be nice if you could alter your PR.

**Comment by pbowyer** [comment]
> The core is filled with weird weak type checking and casting which is prone to errors.

First time I've worked on a codebase without a fixed coding standard and rules around not changing what's already present 😀 

Here we go - I've expanded the rewrite to simplify down the entire `case` statement. @Jako made a great point and I've switched to `filter_var`.

**Comment by OptimusCrime** [comment]
Very nice. Looks good now :)

**Comment by opengeek** [comment]
@pbowyer Can you edit the base branch of this PR to target 2.x instead of 2.5.x?

**Comment by opengeek** [comment]
Er, nevermind @pbowyer — apparently I can do that myself and didn't realize it until now. 🤦‍♂️

**Comment by pbowyer** [comment]
@opengeek np, it's a nice new(ish) feature of GitHub

**Comment by Mark-H** [comment]
Hey, I requested that feature 5 years ago! I don't remember doing that, but fun that I'm now the one to merge it in 😁 

Thanks @pbowyer, merged for inclusion in 2.6.

**Pull request merged**
