### PR TITLE
Do not remove || from value

### PR DESCRIPTION
**Pull request by Fi1osof**
http://joxi.ru/n2Y87DVh0pRpm6

### CODE REVIEW

**Comment by rtripault** [comment]
The default output renderer basically just removes the separator, which could make the TV value unusable due to being "merged".

A quick workaround would be to use the "delimiter" renderer.

**Comment by Fi1osof** [comment]
@rtripault, thanks for the tip! But i still think it`s bug. TV have value '123||323' and if i got raw data, it`s must be raw date '123||323', not '123323'.

**Comment by rtripault** [comment]
I'm with you on that one (thinking that's a bug too), but i'm not sure what was the original intent behind this `str_replace`, so i was just adding my thought so it could be reviewed by others.

**Comment by Fi1osof** [comment]
@rtripault i think all will be OK :)

**Comment by opengeek** [comment]
I'm not sure I concur that this is a bug, but I do not want to change this without additional time to review the consequences.

**Comment by rtripault** [comment]
Not sure either that is a bug.

After discussing the issue with @TheBoxer, we found a valid use case of the current behavior : holding MODX tags.

Let's say you have a multi select TV with options `My chunk==[[$chunk]]||My other chunk==[[$my-other-chunk]]`, selecting both chunks should produce a TV value like `[[$chunk]]||[[$my-other-chunk]]`.

In that situation, i doubt anyone would expect the separator (`||`) to be part of the output.

When needing a separator, the "delimiter" output type is what we need.

Suggesting to decline the proposal then.

**Comment by Fi1osof** [comment]
@rtripault 
> In that situation, i doubt anyone would expect the separator (||) to be part of the output.

I`m a programmer and i expect there will be a raw value, because in my TV output property are setted "default", not "with convertion".

**Comment by OptimusCrime** [comment]
Close?

**Comment by Fi1osof** [comment]
As you wish.

**Comment by whitebyte** [comment]
-1 for closing. Raw value should be "raw". @rtripault shouldn't you use something like `renderOutput` for mentioned case?

**Comment by Fi1osof** [comment]
@whitebyte +1

**Comment by rainbowtiger** [comment]
When you use "get", you'll get a rendered output. When you don't, you won't, as in your screen capture above. Same difference when you use $modx->resource->get('publishedon'), versus $modx->resource->published. I use the latter when I just want the exact timestamp in the database rather than then "formatted" version MODX sends out when using "get()".

**Comment by Fi1osof** [comment]
@rainbowtiger Problem not in modResource::get/set. Problem in modResource::getTVValue

**Comment by rainbowtiger** [comment]
I'm including "getTVValue" when I said "get" above. In your screen capture, "$modx->resource->related_goods" returns an array, including the raw value. That's what I'm talking about. $modx->resource->getTVValue() returns a processed version of the data, which seems to be how this is designed. So, it is "expected" that people will use the output tab when defining a TV to specific exactly what gets returned by getTVValue, unless those in the know have something different to say about this.

**Comment by Fi1osof** [comment]
@rainbowtiger 

> Raw value should be "raw"

**Comment by rainbowtiger** [comment]
The question is whether get() or getTVValue() are SUPPOSED to return raw values or not. get('publishedon') certainly doesn't, and getTVValue() doesn't either. I've had a hard time finding any definitive answer to this in the documentation. I'd love to hear the reasoning of any developers who have created MODX concerning the difference between $modx->resource->[fieldname] and $modx->resource->get([fieldname]), and the same for getTVValue() or any other "get"ting.

**Comment by rainbowtiger** [comment]
Maybe for TVs we need another option for output, "raw".

**Comment by OptimusCrime** [comment]
This PR is from january of 2015. Time to decide what to do with this.

**Pull request closed without merging**
