### PR TITLE
Bug 13511 - Delete this please

### PR DESCRIPTION
**Pull request by Finetuned**
### What does it do?
hide the User Group tree panel splitbar when the centre panel is hidden (no group selected or group is empty).

### Why is it needed?
This circumvents a ui bug which incrementally decreased the size of the split panel if the centre region was hidden. Each time the user clicked on the splitbar, it jumped further to the left obscuring the tree and could not be dragged out to the right.

### CODE REVIEW

**Comment by rtripault** [comment]
Closing in favor of #13520

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @rtripault 

#3points to @Finetuned

**Comment by rtripault** [comment]
Awarded twice for the same PR ? Nice of you @gpsietzema ^^

**Comment by gpsietzema** [comment]
Whoops (L)

**Comment by sonicpunk** [comment]
@gpsietzema Very BAD. FAKE POINTS!

**Pull request closed without merging**
