### PR TITLE
Fixed a broken MODX browser for mobile screens

### PR DESCRIPTION
**Pull request by Ruslan-Aleev**
### What does it do?
Fixed the broken MODX browser and fixed some styles for mobile screens.
The browser styles, of course, is not perfect, but at least it works.

b

a

### Related issue(s)/PR(s)
None

### CODE REVIEW

**Review by JoshuaLuckers — APPROVED** [review]

**Comment by opengeek** [comment]
Is this really fixing behavior that once worked but no longer does? Or is this making the MODX browser work on mobile screens for the first time?

**Comment by Ruslan-Aleev** [comment]
Browser did not work in my opinion, from the first versions where the adaptive appeared, 2.6 or earlier. Browser started working for the first time, at least I don’t remember that it worked at all.

**Comment by JoshuaLuckers** [comment]
@opengeek is it ok with you if we merge this into 2.x? :)

**Comment by Ruslan-Aleev** [comment]
@JoshuaLuckers , I adjusted the styles of the icons in the tree, did it more correctly than before. Test please.

**Review by Ibochkarev — APPROVED** [review]

**Pull request merged**
