### PR TITLE
"inherit_parent_template" Fix for #5980

### PR DESCRIPTION
**Pull request by matdave**
Add option to turn off inheriting parent templates by default, and add a system setting called "inherit_parent_template" to override it.

### CODE REVIEW

**Comment by sottwell** [comment]
If I recall correctly, Evo has such a setting, to always use default, to use parent, or to use sibling.

**Comment by rthrash** [comment]
Sibling inherit is/was useful—recall working on that back in the day. Taking a property value set on each container to toggle between those settings might be interesting. Great stuff Matt and suggestion Susan.

**Comment by matdave** [comment]
If anyone wants to take on or show me where to add the "inherit_parent_template" to the system settings list, that would help

**Comment by sottwell** [comment]
It's in one of the _build files, I forget which one right now, but there's one with all of the system settings.

**Comment by sottwell** [comment]
_build/data/transport.core.system_settings.php

**Comment by sottwell** [comment]
I just copy one of the existing ones in the same general area where I think the new one should go, then edit the relevant bits.

**Comment by sottwell** [comment]
Not sure what its x-type should be, though.

**Comment by inreti** [comment]
+1 for that. Regarding the child template behaviour: additionally an option per resource & template where you can list the ids of allowed templates as child resources. And a tree context menu respecting that setting and showing only those Templates/ResourceTypes instead of "Create new" everything and selecting the template then.
I don't want my customers to create a Gallery or Articles Resource anywhere in the tree (ResourceType), and I don't want them to create any Resource (Template) at places my tree setup was not expected to have them created. You can control the template selection somehow by Forms (Manager) customization, but this is a mess.

**Comment by Mark-H** [comment]
Hey @matdave could you please follow the template from https://github.com/modxcms/revolution/blob/2.x/CONTRIBUTING.md#template-1 in your pull request? Thanks!

**Comment by Mark-H** [comment]
Also it looks like you haven't added the setting to the build yet, if you need help with that just let me know.

**Comment by Mark-H** [comment]
I'm tempted to close due to lack of response/follow-up, missing the data in the build, and that one line of code being so horrifically long with nested nested ternaries that I don't want to touch it with a ten foot pole. :P 

I can see some real benefit to this improvement, but it could really use some tidying up. 

@matdave think you'd be up for improving the PR a bit?

**Comment by OptimusCrime** [comment]
Damn, that line should be fixed either way :(

**Pull request closed without merging**
