### PR TITLE
Port modPackageBuilder, modTransportManager and modTransportVehicle

### PR DESCRIPTION
**Pull request by theboxer**
### What does it do?
Ports modPackageBuilder, modTransportManager and modTransportVehicle classes from 2.x to 3.x

### Why is it needed?
They were missing and they are used in a lots of build scripts :)

### CODE REVIEW

**Review by alroniks — CHANGES_REQUESTED** [review]
File names do not compatible to PSR-4. Could we avoid `.class` postfix here?

**Comment by theboxer** [comment]
Ouch, sorry. Will update it

**Comment by theboxer** [comment]
Adjusted

**Review by JoshuaLuckers — CHANGES_REQUESTED** [review]
To keep the code consistent with the rest of the code base please apply the PSR-2 code style.

**Comment by theboxer** [comment]
Tried my best :)

**Comment by JoshuaLuckers** [comment]
> Tried my best :)

Thanks, if you could also add the copyright notice that would be great! 😄

**Review by opengeek — APPROVED** [review]

**Pull request merged**
