### PR TITLE
Fixes bunch of various XSS issues in the manager

### PR DESCRIPTION
**Pull request by AgelxNash**
### What does it do?
Fix XSS

### Why is it needed?
Security reason

### Related issue(s)/PR(s)
#14102 #14103 #14104 #14105

### CODE REVIEW

**Review by alroniks — APPROVED** [review]

**Review by Ibochkarev — APPROVED** [review]

**Comment by Ibochkarev** [comment]
Related #14094

**Review by Mark-H — APPROVED** [review]
Thanks for working on this, @AgelxNash.

**Comment by Ruslan-Aleev** [comment]
Some recent PR, affecting XSS, broke the generation of the tree, we need to test it more carefully.

resource_tree

**Comment by Ibochkarev** [comment]
@AgelxNash I ask you once again to check the changes in this PR - I also confirm the incorrect operation after applying these changes.

In the resource tree, the code is added - which was inserted for verification and it does not disappear even after cleaning in the place where I inserted it for testing.

Overwriting files from the distribution kit fixes this bug.

**Comment by Mark-H** [comment]
Sounds like a new issue for that is in order, that definitely needs to get fixed.

**Comment by Ruslan-Aleev** [comment]
@Mark-H  The problem was found, here is - https://github.com/modxcms/revolution/pull/14335/files#diff-5f9a4ceb2f6f68d22416f98adcc4fdb5R250

**Pull request merged**
