### PR TITLE
Make the input fields for imageTVs and fileTVs use all the available space AKA 100% width

### PR DESCRIPTION
**Pull request by mindeffects**
### What does it do ?

Making fields for imageTVs and fileTVs 100% wide lets you use the full available space. And it adepts the width when the window is resizes are the tree-panel gets hidden.
image
### Why is it needed ?

There are [really complex filenames](http://www.manice.net/index.php/component/content/article/2-news-display/152-a-new-dcp-naming-convention) and longer paths (or a combination of both ;-) which need as much width as they can get. Since the space is there it shall be available for usage.
### Related issue(s)/PR(s)

The DIV creates creates a duplicate ID and is not needed anayway #12339

Thanks to the patients and efforts of Romain and John, this simple task (which turned out to be insane to do) finally worked out.

### CODE REVIEW

**Comment by mindeffects** [comment]
Sorry for messing arround in the pull request for different issues (– this setup/branding thing). I am still in "1st grade mode" when it comes to GitHub AKA "learning by doing (it wrong)". ;-)

**Comment by TheBoxer** [comment]
Closing this one as the PR contains a lot of not related commits.

Create new branch every time before sending PR to prevent submitting unrelated stuff.

**Comment by mindeffects** [comment]
I am sorry for the extra work, @TheBoxer. It was my first commit to "dev" and I got a little confused. My learning ment your trouble. Sorry! Won't happen again, since I now know how to to it.

**Comment by mindeffects** [comment]
Does this mean the improvement is not implemented? I think @Mark-H did some changes, too?

**Comment by TheBoxer** [comment]
No it's not merged. You need to grab changes only for this improvement and submit it correctly ;)

**Pull request closed without merging**
