### PR TITLE
Better handling of reverse HTTPS proxies

### PR DESCRIPTION
**Pull request by OptimusCrime**
### Note

[Better diff here](https://github.com/modxcms/revolution/pull/13594/files?w=1).

### What does it do?
Does a better job at attempting to identify HTTPS requests before MODX decides if it should serve over HTTP or HTTPS.

### Why is it needed?
As reported in the original issue #13259, the current checks have problems with handling reverse proxies for some providers (such as Cloudflare).

### Details
Note that I took great care negating the original expression:

```
defined('PHP_SAPI') && (PHP_SAPI == "cli" || PHP_SAPI == "embed")
```

Into:

```
!defined('PHP_SAPI') || (PHP_SAPI != "cli" && PHP_SAPI != "embed")
```

I have actually verified that these are opposites of each other using a [online truth table generator](http://web.stanford.edu/class/cs103/tools/truth-table-tool/).

The first expression would be `a && (b || c)` while the latter is `~a || (~b && ~c)`. These are opposites of each other.

_Also note that I have been unable to test this as I have no providers that set these server variables/serve requests this way._

### Related issue(s)/PR(s)
#13259

### CODE REVIEW

**Comment by meshkov** [comment]
I`m test on my site on hosting https://beget.com/ and it don`t solve the problem.
Hosting use nginx+apache.

**Comment by OptimusCrime** [comment]
@meshkov Care to elaborate more? How is data proxied in your environment? What if you dump the content of `$_SERVER` (and remove the sensitive information), how can we figure out that your request is proxied?

**Comment by meshkov** [comment]
@OptimusCrime I can provide access to the site for testing.
Now I have added the following lines to .htaccess:
`RewriteCond %{HTTP:X-Forwarded-Proto} !https
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]`
And now site is working fine

**Comment by meshkov** [comment]
current values:
PHP_SAPI - apache2handler
$_SERVER['HTTPS'] - on
$_SERVER['SERVER_PORT'] - 443
$_SERVER['HTTP_X_FORWARDED_PROTO'] - https
$_SERVER['HTTP_FRONT_END_HTTPS'] - empty

**Comment by opengeek** [comment]
If the diff is not working without special parameters, it is going to mess up merging. Please make the changes without changing white space or line endings or whatever is causing the entire file to diff.

Also, why are you negating that SAPI check? I don't understand why that was necessary and it doesn't seem correct negated like this. It should only skip the other checks if it meets the original logic.

**Comment by OptimusCrime** [comment]
I can fix the diff, but the if is correct. The default value of `$isSecureRequest ` is `false`, [here](https://github.com/modxcms/revolution/pull/13594/files?diff=split&w=1#diff-5dc55a39a3ad90626e446e88d85c08abR49). Doing this (and negating the expression) removes the need for the if/else.

**Review by JoshuaLuckers — CHANGES_REQUESTED** [review]
See the comment from @opengeek 😊

**Comment by Ibochkarev** [comment]
@OptimusCrime Hello! Please continue to work on this fix. Thank!

**Comment by OptimusCrime** [comment]
Fixed now, thanks @ily

**Comment by ilyautkin** [comment]
@JoshuaLuckers Can you approve changes you requested, please? Or the changes still not enough?

**Review by Jako — APPROVED** [review]

**Review by JoshuaLuckers — APPROVED** [review]

**Comment by alroniks** [comment]
It seems this one should be targeted to the proper branch (now 2.5.5) and formally (even when it is ready for merge) we have to ask opinion of code owners @Mark-H or @opengeek

**Comment by OptimusCrime** [comment]
I will have to rebase this.

**Pull request closed without merging**
