### PR TITLE
Implement X-Powered-By header to send "MODX Revolution 2.x" on all requests

### PR DESCRIPTION
**Pull request by Mark-H**
### What does it do ?

Allows MODX to respond to all requests with a "X-Powered-By" header, with the value of `MODX Revolution 2.x` (or `MODX Revolution 3.x` once that is out). It is controlled by a new setting send_poweredby_header. 

The setting is disabled by default. 

On new installations, the checkbox (pictured below) will be _checked by default_, allowing a swift opt-out if they wish not to do that. 

On upgrades, the setting value is not changed (either from the default disabled, or enabled if the user changed the setting). So the site builder is in complete control over wether this is sent or not. 

screen shot 2016-01-28 at 17 09 47
### Why is it needed ?

MODX is considered to be a small contender in the CMS market by people from outside our community, because it rarely shows up in services that track technology usages across the top X websites, like builtwith.com and w3techs.com. As I believe MODX is a lot bigger than those sites seem to indicate, this pull request will allow sites like those to more accurately track when a site is MODX. 
### Related issue(s)/PR(s)

More background and discussion of this change took place in issue #12882.

### CODE REVIEW

**Comment by jpdevries** [comment]
Do these checkboxes get ticked to indicate if their current values? For example, if Send X-Powered-By is true in the databse will the box be initially ticked to reflect that?

**Comment by Mark-H** [comment]
The checkbox is only available on a new installation, where no existing value is set.

**Comment by ckburnett** [comment]
I'm not a fan of exposing this information at all (and would really hate for it to ever be anything but opt-in), and I understand "security by obscurity is no security at all" but it is _part of_ defense-in-depth... 

but all of that set aside...

Food for thought - what about offering a bit more granularity of choice? Let the site generate:
1. No x-powered-by header
2. A header with just the code name (i.e. "Revolution") only
3. A header with both the code name and the version number as you have it now

Of course, you could have options for all the choices provided by getVersionData(), but I think adding in 2 above gives a bit more flexibility that could be desirable to some.

**Comment by rthrash** [comment]
This is a great idea. Thanks Mark! :+1:

**Comment by jaygilmore** [comment]
After rethinking this, I wonder if anyone will ever check this box. It seems to me that since we've left the technical term in place that almost everyone will leave it unchecked as they attempt to fill or change only the necessary fields as quickly as possible to get to the finish line. 

I feel we've compromised all the way to no point to include at all. It should be opt out nor negatively phrased. 

`Disable Powered-By Headers` with the default empty state, if for new installs. This is a new feature, and a non-breaking-change.

**Comment by Mark-H** [comment]
To clarify, on new installations, the checkbox controlling the setting ("Send X-Powered-By Header") is checked by default (= opt-out on new installs). 

On updates, there is no checkbox, and the setting is disabled by default (= opt-in on upgrades).

**Pull request merged**
