### PR TITLE
Make the error_handler_class available as service

### PR DESCRIPTION
**Pull request by JoshuaLuckers**
### What does it do?
- Deprecates the public $errorHandler property
- Loads the error handler as a service 
- Use a anonymous function as callback for the PHP error handler using the new services container
- Use the error handler provided by MODX as fallback.

### Why is it needed?
Makes it easier to load a custom PHP error handler without the need to define it as system setting.
It also solves an issue that would break MODX when the error handler defined in the system settings was unable to load.

### Related issue(s)/PR(s)
Inspired by issue #15001

### CODE REVIEW

**Comment by opengeek** [comment]
Is there a reason it could not just have been converted to `errorHandler` instead of `error_handler`?

**Comment by JoshuaLuckers** [comment]
@opengeek I decided for the snake case variant because it appears to be the default naming convention for Pimple. 
It also makes more sense in terms of what it's used for: set_error_handler

**Comment by opengeek** [comment]
But the service has always been called `errorHandler` inside MODX. MODX service naming conventions have always been camel case, and I don't see why we would want to abandon it here. `set_error_handler` is just the PHP function—not the service class inside of MODX.

**Comment by JoshuaLuckers** [comment]
You should have told me immediately 🙈. I'm wrong in the naming of the service and I'll change it in the next 24 hours.

**Comment by JoshuaLuckers** [comment]
@opengeek I changed the name of the service.

**Review by Jako — APPROVED** [review]

**Comment by JoshuaLuckers** [comment]
@opengeek ping

**Pull request merged**
