### PR TITLE
Generate new file if file already exists

### PR DESCRIPTION
**Pull request by sdrenth**
### What does it do?
When uploading a file it checks if a file already exists with the same file path. If so, it will generate a unique filename and upload it as a new file instead of overwriting the existing file.

**Example:**
- A file /directory/image.png already exists
- When uploading a new image.png file to the /directory/ it will upload the file as /directory/image-01.png

### Why is it needed?
This will prevent files from being overwritten if an image already exists with the same file name.

### Relevant issue(s)

#8371

### CODE REVIEW

**Review by alroniks — CHANGES_REQUESTED** [review]
I don't like such hidden and silence behavior. It would be much better to show confirm window and as a user what to do and suggest create new but also leave the ability to override. As it works on operation systems (windows, mac os, etc.)

**Comment by gpsietzema** [comment]
I agree, that was what we were also aiming for. We're working on multiple usability improvements for 3.x this week, but the ideal situation (multiple choice - let the user choose) was impossible to do in the amount of time we have at our hands this week. So we settled for this solution, which is still a huge improvement for the ultra-silent-just-overwrite-the-shit-out-of-it current situation.

**Comment by Mark-H** [comment]
What about simply refusing the upload (file already exists)? Plugins can implement whatever business logic best suits the specific user without this necessarily being something we have to get right for everyone in the core. 

(That's implemented in #14514)

**Comment by Jako** [comment]
@gpsietzema If it would be not a degression (you can't upload the same file again to overwrite it), I would be comfortable with this patch.

**Comment by sdrenth** [comment]
@gpsietzema What are your thoughts on this one?

**Comment by JoshuaLuckers** [comment]
It's all about telling users what action to take to solve the issue or/and inform them about what decisions the system has made for them instead. I don't mind if the file gets another name if I'm being told what and why. 

The best solution would be to ask the user what action to take when a file with the same name exists:
1. Cancel the upload
2. Overwrite the old file
3. Keep both

**Comment by gpsietzema** [comment]
I agree to what you're saying, but for us it's not an option to make this work now, because it requires a ton of work and possible rewrite of half of that media browser. So I'd go with this first as an improvement to the current way it works...

**Review by Mark-H — CHANGES_REQUESTED** [review]
If a file already exists the upload should be rejected, generating a new file name should be left to plugins (which is already possible).

**Comment by gpsietzema** [comment]
Fine, we'll just use this in our own amazing MODX-install.

**Comment by sdrenth** [comment]
Since this PR won't be merged into the core I'll close this PR. The ultimate fix was described in this issue by @JoshuaLuckers and I agree that that would be the best solution, but we are unable to fix the issue as described. Therefor I created a new issue for this one and added the described solution by @JoshuaLuckers there and hopefully somebody finds the time to fix the issue as described

**Pull request closed without merging**
