### PR TITLE
patch edit action for S3 media source

### PR DESCRIPTION
**Pull request by goldsky**
**### What does it do ?**
Manager's URL to edit file

**### Why is it needed ?**
Different "action" parameter directive between MODX 2.2.X and 2.3.x

### CODE REVIEW

**Comment by TheBoxer** [comment]
@goldsky Can you update the PR to follow https://github.com/modxcms/revolution/blob/master/CONTRIBUTING.md?

**Comment by goldsky** [comment]
Ok. About adding what does it do?

**Comment by goldsky** [comment]
there

**Comment by rtripault** [comment]
Pardon my ignorance, but given the change you are submitting will be in 2.3+, why is that needed ?

**Comment by goldsky** [comment]
Sorry for my confusion, how does actually modx update 2.2.x branch?

**Comment by TheBoxer** [comment]
From PRs that goes into release-2.2 branch

**Comment by goldsky** [comment]
ok then, I've changed it to 2.3.x only.

**Comment by TheBoxer** [comment]
Cherry picked to master & merged to develop.

**Pull request closed without merging**
