### PR TITLE
Added editedon column for elements and prevent overwriting outdated elements

### PR DESCRIPTION
**Pull request by sdrenth**
### What does it do?
Added editedon column for all elements and on update the editedon is being updated. Also added a check on editedon field to see make sure you are not saving an outdated element overwriting previous changes to the element. If this is the case, an error is shown and the element is not being saved.

The confirmation window has not yet been implementen. But I also question if that would even be desirable behaviour, because then you don't know what values you'll be overwriting. So I think when you receive this error you should manually open a new tab, check the changes in the current element and the changes you wanted to save and then manually merge these changes?

### Why is it needed?
It helps to prevent overwriting changes when working on the same element in for example multiple tabs (As described in issue #13626).

### Related issue(s)/PR(s)
Issue #13626

### NOTE
I've already added the migration scripts, but these are untested and I don't really know how to properly test these. Is this tested when creating a new version of MODX?

### CODE REVIEW

**Comment by Mark-H** [comment]
Please use a better title @sdrenth ;)

**Comment by sdrenth** [comment]
@Mark-H haha you're quick, I was still finishing my PR  👍

**Comment by OptimusCrime** [comment]
This is awesome. I am currently working on a extra that does this, but having it in the core is much better.

**Review by opengeek — CHANGES_REQUESTED** [review]
This cannot be accepted as is. All changes to map files *must* be made through the schemas.

**Comment by bezumkin** [comment]
Closing this in favour of #13857

**Pull request closed without merging**
