### PR TITLE
Rename manager actions

### PR DESCRIPTION
**Pull request by bezumkin**
### What does it do?
This PR renames all actions in ExtJS files to new processors names format.

### Why is it needed?
It will fix problems in manager on all case-sensitive file systems - 99% of GNU\Linux

### Related issue(s)/PR(s)
#14662
#14639

If someone have a questions, how I did it - here is my rename script:
```php
<?php

$base = dirname(__FILE__) . '/';
$processors = $base . 'core/src/Revolution/Processors/';
$manager = $base . 'manager/assets/modext/';

$Directory = new RecursiveDirectoryIterator($processors, FilesystemIterator::SKIP_DOTS);
$Iterator = new RecursiveIteratorIterator($Directory);
$actions = [];
/** @var SplFileInfo $info */
foreach ($Iterator as $info) {
    $actions[] = str_replace($processors, '', str_replace('.php', '', $info->getPathname()));
}

$Directory = new RecursiveDirectoryIterator($manager, FilesystemIterator::SKIP_DOTS);
$Iterator = new RecursiveIteratorIterator($Directory);
/** @var SplFileInfo $info */
foreach ($Iterator as $info) {
    $file = $info->getPathname();
    $replace = str_ireplace($actions, $actions, file_get_contents($file));
    file_put_contents($file, $replace);
}
```

### CODE REVIEW

**Comment by JoshuaLuckers** [comment]
I just wondering but what’s wrong with my draft PR?

**Comment by bezumkin** [comment]
@JoshuaLuckers Nothing wrong, it is just in Draft status, so I thought it is not ready yet.

You can close my PR and merge yours - no problems, really.

**Comment by JoshuaLuckers** [comment]
It's still in draft because it's, indeed, not ready yet (I am/was going to do that in the upcoming days). The same counts for this PR because not all processors can be found based on the filename. 

I don't mind which one will be merged eventually but I it's a waste of both our time if we do the same work.

**Comment by JoshuaLuckers** [comment]
Some of the "missed" actions can be found by using this search query in PhpStorm (match case, regex and file mask set to *.js): `'(browser|context|element|resource|search|security|source|system|workspace)\/[a-z]+(.*)'`

For example, the new TV processor: `core/src/Revolution/Processors/Element/TemplateVar/Create.php` will not replace `'element/tv/create'` (which it does in my PR).
There are also some other processors that are renamed. I can name them all but then I could have easily done it myself while typing it out haha. 

Feel free to continue the work but it would be great if you would let me know so we don't do the same thing! :)

**Comment by bezumkin** [comment]
No problem, I close this one and hope somebody will merge your current PR asap, because current state of 3.x branch is "not ready for work" because many actions in manager are wrong.

**Pull request closed without merging**
