### PR TITLE
System settings: change default value

### PR DESCRIPTION
**Pull request by Ibochkarev**
### What does it do?
- Automatic Template Assignment (`automatic_template_assignment`) - `parent` changed to `sibling`, Because more often, resources with the same template are siblings pages, for example, news or articles.
- FURL Alias Character Restriction Method (`friendly_alias_restrict_chars`) - `pattern` changed to `alphanumeric`. Because It happens that in the current variant can stay incorrect characters in url, but with "alphanumeric" there is no such problem and this option will is suitable for most users.
- Manager Time Format `manager_time_format` Is set to US-version `am/pm`, changed to `24h format`
- Week start `manager_week_start` Is set to `0 (sunday)` right now, changed to to `1 (monday)`
- Published default (`publish_default`) - `no`, changed to `yes`. Resources are published more often than not published. 
- Resource Tree Node Fallback Field `resource_tree_node_name_fallback` Is set to `pagetitle`, changed to `alias` 
- Preserve Menu Index When Duplicating Resources `preserve_menuindex`  Currently `True`, Changed to `False`
- Manager Favicon URL (`manager_favicon_url`) - `empty`. Added file favicon.ico and registered path `/manager/templates/default/images/favicon.ico`

### Why is it needed?
A clean install of MODX is currently too clean. It's missing some very essential things, which will make the install more tailored to our needs.

### Related issue(s)/PR(s)
#14273 #13876

### CODE REVIEW

**Comment by ghost** [comment]
I'm pretty sure that each enhancement should have its own PR.

**Comment by Ibochkarev** [comment]
@sottwell What is specified in #13876  - will be decided by a separate PR when we rewrite the installation page.

Here I combined, only that which can already be specified.

**Comment by JoshuaLuckers** [comment]
I agree with @sottwell that some changes are better off in separate PR’s (I.e. the favicon).

**Comment by JoshuaLuckers** [comment]
To clarify: separate PR's for the different enhancements makes it easier to accept and test them. It also prevents stalling enhancements that don't need discussion/changes.

**Comment by Ibochkarev** [comment]
This PR will be divided into several. For ease of discussion and decision on confirmation.

**Pull request closed without merging**
