### PR TITLE
mb functions

### PR DESCRIPTION
**Pull request by Fi1osof**
Broke JSON on cyrrilic

Array
(
    [0] => Array
        (
            [name] => login-updprof-btn
            [id] => login-updprof-btn
            [iconCls] => icon-terminal
            [text] => login-updprof-btn - <i>Редактировать п�...</i>
            [leaf] => 1
            [value] => Редактировать профиль
        )

)

### CODE REVIEW

**Comment by TheBoxer** [comment]
@Fi1osof can you please update this PR to follow https://github.com/modxcms/revolution/blob/master/CONTRIBUTING.md

**Comment by Fi1osof** [comment]
### What does it do ?
use multibyte string functions

### Why is it needed ?
Broking JSON with cyrillic

**Comment by Fi1osof** [comment]
[It seems that this is due](https://github.com/modxcms/revolution/blame/master/manager/controllers/default/security/user/update.class.php#L133)

**Comment by Mark-H** [comment]
Hi @Fi1osof, thanks for catching this and sending a pull request! That's really appreciated and sorry we've not been doing a great job keeping up with the PRs.

Given #12484 and this PR both fix the same issue, but that #12484 checks if the multibyte functions are available and that the use_multibyte setting is enabled, I'm going to close this one and mark #12484 for inclusion in the next patch release. 

If you think some of the other changes in this pr are also needed or if you have concerns about 12484 please do let me know.

**Comment by Fi1osof** [comment]
Hi @Mark-H, why this multibyte functions checks in present days? :) But as you wish))

**Comment by Mark-H** [comment]
Can't hurt to be extra careful, especially with the old version support we still have ;)

**Comment by Fi1osof** [comment]
In the furnace the old versions. Progress forever!
Sorry for offtop. Yes, it`s may be closed.

**Pull request closed without merging**
