### PR TITLE
Lock setup after it is successfully executed

### PR DESCRIPTION
**Pull request by opengeek**
### What does it do?
Writes a .locked/ directory in the setup/ folder upon successful completion of running installation or upgrade.

### Why is it needed?
To prevent unauthorized users from unexpectedly running setup/ if the folder is left in place (or even renamed).

### Related issue(s)/PR(s)
#14568

### CODE REVIEW

**Comment by Mark-H** [comment]
It seems to be working _so well_ that it even prevents the redirect to the manager login (`/setup/index.php?action=login` => `FATAL ERROR: MODX Setup cannot continue.`).

**Comment by Omeryl** [comment]
@Mark-H Is there a reason it needs to hit that specific URL for the redirect to the manager? Can we just embed the manager link on that template, skipping the need for the 3xx redirect?

**Comment by Mark-H** [comment]
Just doing some testing, when moving `$install->lock()` to `setup/controllers/login.php` it does work as expected:

```
if ($install->settings->get('cleanup')) {
    $install->removeSetupDirectory();
}
else {
    $install->lock();
}
```

@Omeryl The `login` controller actually does the cleanup of the `setup/` folder and temporary settings cache file before the redirect. While it does seem like something that could be handled in `complete`, it does serve a purpose.

**Comment by Omeryl** [comment]
@Mark-H So, the problem then becomes that unless someone clicks that login button we'd never lock the setup though?

**Comment by Mark-H** [comment]
It's a hard button not to press, and is also currently responsible for removing the setup if that was checked, so I don't have a problem with that. ;) 

Schermafbeelding 2019-08-23 om 00 52 40 1

**Comment by Omeryl** [comment]
@Mark-H I guess the problem is, the only reason we're in this situation is because of the edge cases where people don't delete the setup and shoot themselves in the foot. So if you don't do it on set up complete, and still require user action, we'd still be letting people shoot themselves here. I feel like it'd be beneficial to perhaps continue this lock, refactor the login stuff out to somewhere else (perhaps manager first login if it detects the lockfile, prompt the sudo user?), and embed a link to the manager.

**Comment by opengeek** [comment]
@Mark-H I had wanted to do it when they click proceed after successful installation, but yeah. Duh. I could move the check out of the preloadChecks to solve the problem with doing it before the login controller.

**Comment by donShakespeare** [comment]
>the **only reason** we're in this situation is because of the **edge cases** where people don't delete the setup and shoot themselves in the foot.

not quite the only reason as many have attested. Plus, this safety measure or similar is implemented by other respectable CMSes as discussed earlier. Just saying that a solution in general is (would have been) the default way to go.

This is awesome.

**Comment by Omeryl** [comment]
@donShakespeare The problem I'm arguing is that if we only put the lockfile in place _after_ the user clicks the "Login" button, there's still going to be a good number of cases where setup is left open. But if this is the way we want to do it, and leave that edge case, I'm fine with it. Just putting my two cents in, the CMSes you list put that lock file in as soon as the setup is completed, not after clicking some "login" button.

**Comment by donShakespeare** [comment]
Yes, you are absolutely correct.
Locking the folder upon user interaction defeats the purpose of this noble pursuit.

**Comment by opengeek** [comment]
Alright. I tried a different approach. It should be a lot better this way, locking right after the sessions are cleared. This also blocks CLI install, though I'm wondering if that is even necessary. Discuss.

**Comment by Ruslan-Aleev** [comment]
I think we should transfer the checkbox with the removal of the "Setup" folder to the "Installation Summary" stage:

install

Or move the checkbox in front of the login button:

install2

_Because at the stage of entering the manager panel, the button blocks all attention (as mentioned above). And below the button, the checkbox looks like the checkbox "Remember me", if you do not pay attention._

**Review by Mark-H — APPROVED** [review]

**Review by JoshuaLuckers — APPROVED** [review]

**Pull request merged**
