### PR TITLE
Fix #5700 & #8371

### LINKED ISSUE #5700: Unable to change label or value of weblink/symlink field with Form Customization on weblinks or symlinks
juro created Redmine issue ID 5700

FC cannot customize label or default value of "weblink", "symlink" etc field for modWebLink, modSymLink etc resources, because there is no such field in FC rules. Both these fields are in fact written to Content field, but customizing Content doesn't work.

### PR DESCRIPTION
**Pull request by webinmd**
Fix form customization for weblink and symlink #5700
Fix identical file names on upload #8371

Related issue(s)/PR(s)
#5700
fc-weblink

#8371
identical_file_names

### CODE REVIEW

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to submit this PR and help make MODX better. Since you are a first-time contributor; please sign the the [Contributor License Agreement (CLA)](https://docs.modx.com/community/contribute/becoming-a-contributor).

**Comment by webinmd** [comment]
Done

**Comment by Mark-H** [comment]
Hey @webinmd, it's best to use separate branches for different fixes/improvements. That allows us to either accept or ask for changes on each fix separately. Now, we only really have the choice to either accept all or none of it.

Right now I'd be happy to approve your fix for #5700 (form customisation label for symlink/weblink field), but #8371 (prevent overwriting files) might need additional discussion as another solution was proposed in #14566. 

Do you think you could send separate pull requests for each of those fixes?

**Comment by webinmd** [comment]
> Do you think you could send separate pull requests for each of those fixes?

yes, close this pr, i will try to divide it by 2

**Comment by Ibochkarev** [comment]
> yes, close this pr, i will try to divide it by 2

Close this PR is not necessary.
 It is necessary to divide the changes into two PR. In this, leave a fix for one of the problems and create a second PR for fixing another problem.

**Comment by Mark-H** [comment]
Thanks @webinmd. If you get stuck with git let me know.

**Pull request closed without merging**
