### PR TITLE
Added hotfix to sanitize MySQL passwords before writing to config fil…

### PR DESCRIPTION
**Pull request by cedwardsmedia**
Fixes Issue #12502.

### CODE REVIEW

**Comment by Mark-H** [comment]
Hey @cedwardsmedia! Could you please visit http://modx.com/cla and sign the Contributors License Agreement? We need that on file in order to merge your contribution :)

Let me know when you did that, and I'll get right on merging this. 

Thanks!

**Comment by cedwardsmedia** [comment]
Done

**Comment by Mark-H** [comment]
Great, thanks @cedwardsmedia :)

**Comment by cedwardsmedia** [comment]
Glad I could help. Hope this prevents some future issues. :D

**Pull request merged**
