### PR TITLE
Fix publishedon field

### PR DESCRIPTION
**Pull request by crystaldaking**
### What does it do?
Fix date generation error for resources created by processors

### Why is it needed?
This fix will allow you to use system time() property and create resources like '12.01.2001'

### CODE REVIEW

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to submit this PR and help make MODX better.

It looks like you're a first-time contributor I welcome you to our community. Before we can accept your contribution please make sign the [Contributor License Agreement (CLA)](https://modx.com/community/contribute/cla/) and share your modx.com username to verify.

**Comment by crystaldaking** [comment]
modx.com username: mynameiscrystal 
@JoshuaLuckers

**Comment by Mark-H** [comment]
I'm confused - how does formatting the date this way change anything about how you can provide the publish date?

**Comment by crystaldaking** [comment]
> I'm confused - how does formatting the date this way change anything about how you can provide the publish date?

1. At this moment, creating a resource using the processor ignores the format specified in the system settings
2. Try to create resource via processor with 'publishedon' => time() w/o this PR.

**Comment by JoshuaLuckers** [comment]
If you create a resource and you want to `publishedon` to be `time()` you should leave the value for `publishedon` empty and set `published` to `1` or `true`. 

The value of `publishedon` should always be a unix timestamp. If you want to provide the value for `publishedon` in the create processor the value should be an English textual datetime description. The processor will parse it into a unix timestamp.

**Comment by Mark-H** [comment]
@cla-bot check

**Pull request closed without merging**
