### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by modxbot**
Enjoy!

### CODE REVIEW

**Review by Ibochkarev — APPROVED** [review]

**Comment by Ruslan-Aleev** [comment]
@opengeek @Mark-H Maybe we should not immediately create PR after minor corrections in the translation? And, for example, once a week, by timer? Less work for reviewers.
And before the release of the new version of MODX, of course.

**Comment by Mark-H** [comment]
As long as the PR is left open, the bot will add to it when more translations are made. We don't have to merge it every single time something is changed.

**Comment by Ruslan-Aleev** [comment]
I see, thanks.

**Comment by theboxer** [comment]
It's actually not the bot who's creating it, but the Crowdin integration for github. I believe it's set to scan for changes once a day.

**Comment by JoshuaLuckers** [comment]
> As long as the PR is left open, the bot will add to it when more translations are made. We don't have to merge it every single time something is changed.

iirc @opengeek mentioned to simply merge them without waiting

**Comment by opengeek** [comment]
> iirc @opengeek mentioned to simply merge them without waiting

No. We can leave it open and merge it periodically. It does not have to be merged every time there are translations added.

**Pull request merged**
