### PR TITLE
Fix: Edit context in grid adds context key multiple #13371

### PR DESCRIPTION
**Pull request by achterbahn**
The name field in the grid was concatenated from context-name and context-key. PR removes the concatenation. Only the context name is shown in the name field.

### CODE REVIEW

**Comment by Jako** [comment]
The getlist processor could be used elsewhere, i.e a combobox could use it. Better create a different column with the concatenated column, search for those getlist occurrences and change the display field to the concatenated column.

**Comment by achterbahn** [comment]
What happens when double-clicking on the name filed in the context grid? Is then the display fileld replaced with the "real" value? 
image
Or should there be two fields?

**Comment by Jako** [comment]
Yes, the 'name' column is changed by the getlist processor, it is displayed in the grid cell and saved with that changed value during inline editing in the grid by the updatefromgrid processor.

Since the name column of the getlist processor better contains an unchanged value, a new column should contain the changed value, which is uses in the combo box (or the combo box could use a template - but that would have a display issue).

**Review by Jako — DISMISSED** [review]
Add a new column (i.e. $contextArray['name_key']) with the concatenated value in the processor, change the combo box displayField and add the new column to the fields array in https://github.com/modxcms/revolution/blob/8ddd6a3e8c9aa43ad3aa32a58c8ee06140673cca/manager/assets/modext/widgets/core/modx.combo.js#L316-L318

**Comment by sottwell** [comment]
Most of the original tables have the "name" field set to 50 chars, and I haven't heard anybody complain about that.

**Review by theboxer — APPROVED** [review]
I agree with this change, the grid should show the real value.

**Pull request merged**
