### PR TITLE
Fix TV field misaligned when moved #4486 #modxbughunt

### PR DESCRIPTION
**Pull request by flowan**
### What does it do?
Fix css when moving TV's to other regions.

### Why is it needed?
Looks better :)

### Related issue(s)/PR(s)
Related issue #4486

### CODE REVIEW

**Comment by pixelive** [comment]
Tested and works.

**Comment by gpsietzema** [comment]
#modxbughunt #3points to @Flowan

**Comment by OptimusCrime** [comment]
Please include print screens for the patch.

**Comment by Mark-H** [comment]
This was already fixed for 2.x in #13344 based on reported issue #13318 so I'm going to propose we close this in favor of what's already integrated.

**Comment by rtripault** [comment]
Agreed, so closing.

But feel free to comment/reopen if needed.

Thanks

**Pull request closed without merging**
