### PR TITLE
Adding shortcuts dashboard widget

### PR DESCRIPTION
**Pull request by sdrenth**
### What does it do?
Adds a shortcuts widget to the dashboard with an overview of all MODX related shortcuts.

### Why is it needed?
Provides a handy overview for every MODX user to speed up their workflow with MODX.

**Note:** I've added the newObject in dashboard_widgets.php with array key 9 instead of 8 so it can be easily merged together with PR: https://github.com/modxcms/revolution/pull/14569 

Screenshot 2019-04-25 at 14 41 14

### CODE REVIEW

**Comment by gpsietzema** [comment]
❤️ on this post if you also didn't know about the cache clearing shortcut lol :-D

**Comment by Ruslan-Aleev** [comment]
Oooh, this is a really useful UX thing, thanks!
And this gives a reminder that new shortcuts can be created in MODX.

**Comment by JoshuaLuckers** [comment]
This widget is very useful! Are there more shortcuts that are not yet listed here available?

**Comment by Ruslan-Aleev** [comment]
However, need to consider that the combinations in Mac OS and Windows are different, maybe should write this:

`Ctrl / Cmd + Shift + U`
...

**Comment by JoshuaLuckers** [comment]
That’s already the case @Ruslan-Aleev 👍

**Comment by Ruslan-Aleev** [comment]
Yes, I apologize, I saw in the code, at first I did not pay attention :)

**Comment by sdrenth** [comment]
@Mark-H @opengeek Can you please review this PR so we can get this PR merged?

**Review by Mark-H — CHANGES_REQUESTED** [review]
This PR needs to be rebased so it doesn't include unrelated commits.

**Comment by sdrenth** [comment]
I'll just create a new PR for this one.

**Comment by sdrenth** [comment]
@Mark-H Please see and merge PR: https://github.com/modxcms/revolution/pull/14625

**Pull request closed without merging**
