### PR TITLE
Update file.inc.php

### PR DESCRIPTION
**Pull request by FerX**
### What does it do?
Removed leading space in tags

### Why is it needed?
tags modx not parsed

### CODE REVIEW

**Comment by sottwell** [comment]
Isn't there another place for dealing with lexicon files?

**Comment by FerX** [comment]
@sottwell opss.. sorry.

**Comment by sottwell** [comment]
I'm not sure if that's where fixes to established translations get done, that's why I asked.

**Comment by Mark-H** [comment]
Yes Susan is correct, translation changes go in crowdin. Only source file changes go directly in github.

**Pull request closed without merging**
