### PR TITLE
Version number fix Smarty, PHPMailer

### PR DESCRIPTION
**Pull request by CrazyBoy49z**
### What does it do?
Version number fix Smarty, PHPmailer

### Why is it needed?
This fix is necessary for the correct display of information.

### Related issue(s)/PR(s)
#14515

### CODE REVIEW

**Review by Jako — DISMISSED** [review]

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to submit this PR and help make MODX better. Since you are a first-time contributor; please sign the the [Contributor License Agreement (CLA)](https://docs.modx.com/community/contribute/becoming-a-contributor).

**Comment by CrazyBoy49z** [comment]
> Thanks for taking time to submit this PR and help make MODX better. Since you are a first-time contributor; please sign the the [Contributor License Agreement (CLA)](https://docs.modx.com/community/contribute/becoming-a-contributor).

Already signed

**Comment by Mark-H** [comment]
What's your MODX.com username please @CrazyBoy49z? I'm not seeing you as having signed yet.

**Comment by opengeek** [comment]
He has signed the CLA.

**Review by JoshuaLuckers — DISMISSED** [review]

**Comment by CrazyBoy49z** [comment]
Please help me delete the last commit.

**Review by Mark-H — APPROVED** [review]

**Review by Jako — APPROVED** [review]

**Pull request merged**
