### PR TITLE
Fix styles for search button and error messages

### PR DESCRIPTION
**Pull request by Ruslan-Aleev**
### What does it do?
Fixed the indent of the search button and set the minimum width for error messages (for example in TV) in index.css and index-min.css.

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/issues/14142

### CODE REVIEW

**Comment by jonleverrier** [comment]
Thanks for this PR.

Could you remove the generated css files and only commit the sass files you have changed.

**Comment by alroniks** [comment]
Also, not required, but for tasks with styles is good to have two screenshots - before and after. It will help people who want to test the pull request.

**Review by Jako — CHANGES_REQUESTED** [review]
Please remove the changes in the compiled css files (index.min.css and index.css) to avoid merge issues.

**Comment by Jako** [comment]
BTW: Is there a GitHub setting that could help to avoid committing those changes by non-integrators?

**Comment by Jako** [comment]
Sorry, maybe my message was a bit confusing. Please remove the changes in the files and not the files.

**Comment by Ruslan-Aleev** [comment]
@Jako Unfortunately, I can't remove the changes, can I close the PR and create another one?

**Comment by Jako** [comment]
Yes, another way would be to download the latest files [here](https://github.com/modxcms/revolution/archive/2.x.zip) and copy the two files to your repo.

**Comment by Ruslan-Aleev** [comment]
@Jako Thanks for clarifying

**Pull request closed without merging**
