### PR TITLE
Update phpThumb 1.7.15-202004301145

### PR DESCRIPTION
**Pull request by Ibochkarev**
### What does it do?
v1.7.15-202004301145
  ¤ PHP 7.4 curly brace substring compatibility
  ¤ add basic support for WebP
  * [bugfix: G18] fopen() fails when using remote images from SSL
  * [bugfix: G65] ImageMagick -flatten vs PNG transparency
  * [bugfix: G75] improved InitializeTempDirSetting
  * [bugfix: G76] fix memory limit detection
  * [bugfix: G78] AllowOutputEnlargement and Zoom-Crop
  * [bugfix: G90] missing $PHPTHUMB_CONFIG
  * [bugfix: G91] missing config_ prefix in allow_local_http_src
  * [bugfix: G93] ImageMagick unsharp amount/threshold
  * [bugfix: G94] cannot declare class phpthumb_functions
  * [bugfix: G96] language level migration fixes
  * [bugfix: G108] add 'line-height' for text in image
  * [bugfix: G113] fix PNGs losing transparency
  * [bugfix: G123] improved default thumbnail filename
  * [bugfix: G126] overlay on transparent image
  * [bugfix: G133] fix 'wmi' and 'wmt' filters
  * [bugfix: G134] fix fsockopen http status text
  * [bugfix: G140] parse_url return user/pass
  * [bugfix: G142] allow transparent background when using 'far'
  * [bugfix: G144] fix class_exists
  * [bugfix: G149] magic quotes deprecated in PHP 7.4.2
  * bugfix: ImageMagick v7+ parameter order (in, op, out)

### Related issue(s)/PR(s)
NA

### CODE REVIEW

**Comment by Ibochkarev** [comment]
@opengeek Tell me, please, is this file needed to be added? https://github.com/JamesHeinrich/phpThumb/blob/master/phpThumb.php

**Comment by JoshuaLuckers** [comment]
Link to official release: [phpThumb 1.7.15-202004301145](https://github.com/JamesHeinrich/phpThumb/releases/tag/v1.7.15)

**Comment by Ibochkarev** [comment]
> Link to official release: [phpThumb 1.7.15-202004301145](https://github.com/JamesHeinrich/phpThumb/releases/tag/v1.7.15)

Yes, I took it from this release. The question is whether this file is needed above.

**Comment by Jako** [comment]
phpThumb.php does not have to be included. The functionality should be covered by modphpthumb.class.php

**Comment by opengeek** [comment]
Why is this a draft? Can I merge this?

**Comment by Jako** [comment]
@opengeek Ivan was not sure, which files should be included in the PR. So he created a draft.

**Comment by opengeek** [comment]
@jako I know, but after you answered the question, it was still in draft status. A better use for drafts is when doing work on something you want to show before it is complete—i.e. you know you will be doing more work on it before it is to be reviewed. Being unsure if something should be included in a dependency update is not really in that category as it could be resolved during the review process.

**Comment by Ibochkarev** [comment]
@Jako @opengeek Thanks guys for the help :v:

**Pull request merged**
