### PR TITLE
Option to supply waitMsg on submit in window

### LINKED ISSUE #11963: Make Windows "waitmsg" configurable
By default when a window is submitted, the "waiting" dialogue is appearing. This always say "Saving...".. Since you also can do other stuff when you hit the submit button, like exporting records, or anything else, it is would be nice you can change the "waitmsg" for this.
Now you only can do to totally overwrite the submit function of a window, but this is way to much if you only want to change that little text ;-).

Adding a "waitMsgText: '...', " configuration option would be nice to have.

### PR DESCRIPTION
**Pull request by BertKooij**
### What does it do?
This PR adds an option to supply a waitMsg on a 'MODx.Window' object in ExtJS which will be used for the waitMsg on the progress window.

**Example:**
```js
package.window.form = function(config) {
    config = config || {};
    config.id = config.id || Ext.id(),
        Ext.applyIf(config,{
            title: _('package.window.title'),
            fields: [{
                            xtype: 'numberfield',
                            name: 'field',
                            allowBlank: false,
                            minValue: 0,
                            maxValue: 9999999999,
                            value: 0,
                        }],
            waitMsg: _('package.window.saving') // Added option
        });
    package.window.form.superclass.constructor.call(this,config);
};
Ext.extend(package.window.form,MODx.Window);
```

### Why is it needed?
Currently the default message for the progressbar is 'saving'. While often the submission of the form is not really 'saving' something but executing a different task. With this option you can provide a custom message and 'saving' will still be used as default/fallback.

### Related issue(s)/PR(s)
Fixes #11963

### Build required
Yes

### CODE REVIEW

**Review by Jako — CHANGES_REQUESTED** [review]
Could you please remove the manager/assets/modext/modx.jsgrps-min.js from the commit and add a 'Build required' note to the commit. The combined scripts are created by the integrators after the merge to avoid such merge conflicts.

**Comment by BertKooij** [comment]
Thank you for letting me know, I was already unsure about committing that file. I reverted the change and the merge conflict should now be resolved. 

Do you happen to know how to build the modx.jsgrps-min.js file? Because that will make testing the changes way easier :)

**Comment by Jako** [comment]
https://docs.modx.com/revolution/2.x/getting-started/installation/git-installation#GitInstallation-RuntheBuild

**Review by Mark-H — APPROVED** [review]

**Comment by Mark-H** [comment]
@Jako It looks like you may need to update your review. Thanks! :)

**Review by Jako — APPROVED** [review]

**Comment by alroniks** [comment]
Hi @beko1997 Just to be sure that we are following the process. Did you sign up CLA here https://develop.modx.com/contribute/cla/? If yes, could you provide your username on modx.com?

**Comment by BertKooij** [comment]
@Alroniks I believe that we already had submitted the CLA, but I just (re)submitted it. Please note the pull request comes from the CensusNL organisation. The CensusNL organisation has signed up for the CLA with the username 'census'.

**Pull request merged**
