### PR TITLE
Unify element already exist lexicon

### PR DESCRIPTION
**Pull request by OptimusCrime**
### What does it do?
Unifying lexicon used when element already exists. This includes templates, template variables, chunks, snippets and plugins. Keys for these lexicon entries are changed in all languages.

The processors:

- processors/element/create.class.php
- processors/element/update.class.php

Are adjusted to using the new lexicon keys.

### Why is it needed?
As described by @Alroniks, there are two ways MODX handles checking for duplicate elements. These two ways use different lexicon keys. Throughout almost the entire core, the format ``[type]_err_ae`` is used, as you can see [here](https://github.com/modxcms/revolution/search?utf8=✓&q=_err_ae).

Element duplicate processors all inherit from [one of the processors that use this naming format](https://github.com/modxcms/revolution/blob/5f59848ab1f1805ba09f03fae35bee5b7166f37b/core/model/modx/modprocessor.class.php#L977), but at the same time also override checking for duplicates during [creation/update](https://github.com/modxcms/revolution/search?utf8=✓&q=_err_exists_name).

My suggestion is (and what this PR intend to solve):

- Use the format ``[type]_err_ae`` across the board, moving away from ``[type]_err_exists_name``, which is only used for template, TVs, chunks, snippets and plugins.
- Fix ``processors/element/[update/create].class.php`` to use ``[type]_err_ae``.

### Related issue(s)/PR(s)
Reported in #13221

### CODE REVIEW

**Comment by Alroniks** [comment]
Hi @OptimusCrime. I agree with your solution. It better to fix the wrong behavior of the system. I was wondering about current state of translates in Crowdin but I hope John will resolve it :)

**Comment by OptimusCrime** [comment]
@Alroniks I am not sure how Crowdin works like that, but in this scenario the keys are incorrect which I think is solved here(?)

Hopefully someone knows better.

**Comment by Mark-H** [comment]
In terms of translations, you should only include the English lexicon in pull requests. The others are synced with crowdin.

**Comment by OptimusCrime** [comment]
@Mark-H I am aware of that, but I thought because we change the KEY associated with the entries, they needed to be pulled from GitHub? If I only need to change the keys for the english language I can go ahead and undo the rest of the changes.

**Comment by Mark-H** [comment]
Maybe @theboxer disagrees but the way I normally use crowdin, I let that create the keys in the different languages again. Probably results in them losing their translation though..

**Comment by theboxer** [comment]
Yes, it will result in loosing translations, but I'd go that way too...

**Comment by OptimusCrime** [comment]
That's fine. I'll adjust the PR as soon as I get the time.

**Comment by OptimusCrime** [comment]
Updated as per requested.

**Pull request merged**
