### PR TITLE
Add new config option for number TVs

### PR DESCRIPTION
**Pull request by smg6511**
### What does it do?
Added a new boolean parameter and behavior via and override to Ext.form.NumberField to allow decimal place zero padding for number TVs. Note that this should have no side effects for current installations, as the default value for this new parameter is false (which maintains the current behavior).

### Why is it needed?
Currently it is not possible with the number TV type to save or display a number such as 52.00 or 3.10. Trailing zeros will always be trimmed (yielding 52 and 3.1 respectively). While from a math/technical perspective these are the same value, it's not desirable to lose trailing zeros when working with currency values for example.

### How to test
Clear your caches and remember to run `grunt build` within the __build/templates/default_ directory to compile the changes into the main js file. Create a few TVs with different setting for Allow Decimals, Decimal Precision, and the new parameter Strict Decimal Precision. Create a resource with access to these test TVs and play with saving different values. Observe that these values persist in the editing form and display as expected on the rendered web page.

### Related issue(s)/PR(s)
Provides the requested feature in #15838.

### CODE REVIEW

**Comment by theboxer** [comment]
Why would you care about keeping the decimal precision on the input side? You can force the decimal precision on the output by using an output modifier, or maybe a custom output type for the TV.

**Comment by smg6511** [comment]
@theboxer - Yes, that's how I initially responded to the feature request, but it makes sense that you would want to see a currency value with its full decimal precision. It would be inconsistent and understandably irritating to see, for example, $12 or $4.5 when you're expecting to see $12.00 and $4.50 in the manager interface.

**Comment by Mark-H** [comment]
Wouldn't this be better in 3.x considering we're not planning a 2.9 at this point?

**Comment by smg6511** [comment]
I'd say the change is pretty small, thus easily incorporated now.  But I'll submit the change for 3.x as well.

**Comment by smg6511** [comment]
Closing this for 2.x. A port to 3.x has been merged.

**Comment by smg6511** [comment]
Sorry for the confusion ... was meaning to close a different PR for 2.x.

**Pull request merged**
