### PR TITLE
Fixed date format for resource quick update #13526 #modxbughunt

### PR DESCRIPTION
**Pull request by flowan**
### What does it do?
Skip date format check when using quick update.

### Why is it needed?
The publish and unpublish dates should be the same as before.

### Related issue(s)/PR(s)
Related issue #13526

### CODE REVIEW

**Comment by sonicpunk** [comment]
#modxbughunt #3points to @Flowan

**Comment by pixelive** [comment]
Tested and works.

**Comment by sonicpunk** [comment]
#modxbughunt #1point to @pixelive

**Comment by Mark-H** [comment]
Code looks clear enough, but could you explain _how_ this fixes the issue? What did you find was the underlying problem that is fixed by not formatting the dates in the processor?

**Comment by sdrenth** [comment]
@flowan The fix does work, but the real problem is the formatDates method which isn't working correctly.

The date output when manager_date_format is set to Y-m-d results in:
2017-08-30

If you read this from the strtotime docs:

> Dates in the m/d/y or d-m-y formats are disambiguated by looking at the separator between the various components: if the separator is a slash (/), then the American m/d/y is assumed; whereas if the separator is a dash (-) or a dot (.), then the European d-m-y format is assumed. If, however, the year is given in a two digit format and the separator is a dash (-, the date string is parsed as y-m-d.
To avoid potential ambiguity, it's best to use ISO 8601 (YYYY-MM-DD) dates or DateTime::createFromFormat() when possible.

So in this case the formatDates method is expecting a different notation of the date, thats why the wrong date is being returned.

**Comment by Jako** [comment]
The fix looks well. But I am not sure if the 'resource/get' processor is used elsewhere in the manager  than in https://github.com/flowan/revolution/blob/dfa44ee9c4f88421782d0949e5345fc5b7d2327e/manager/assets/modext/widgets/resource/modx.tree.resource.js#L472 (a search for 'resource/get' returns only that file). So maybe all the date formatting things could be removed from the processor.

**Pull request merged**
