### PR TITLE
[3.x] Add setup upgrade to remove the manager/min/ folder on upgrade

### PR DESCRIPTION
**Pull request by Mark-H**
### What does it do?
Adds an upgrade file that removes the `manager/min/` folder on upgrade. 

### Why is it needed?
`manager/min/` was removed in #12778. These migrations make sure that the related files are also removed when upgrading from 2.x to 3.0. 

### Related issue(s)/PR(s)
#12778

### CODE REVIEW

**Review by alroniks — APPROVED** [review]

**Review by bezumkin — APPROVED** [review]

**Comment by alroniks** [comment]
I've checked it before and now we have approval from @bezumkin too. So, I guess it can be safely merged. @opengeek

**Review by opengeek — COMMENTED** [review]
Is there a reason we did not just use `xPDOCacheManager->deleteTree()` with the `deleteTop` option set to `true`?

**Comment by alroniks** [comment]
@Mark-H Do you have an answer to Jason's question?

**Comment by Mark-H** [comment]
Not really, other than that this appears to have been the way files/folders were cleaned up in the past. That's a terrible reason to do something, I admit that, but that's the only explanation I have at the moment. :P 

Maybe the original years-old reason is that we can't use xPDOCacheManager reliably yet in the setup? That's just a guess though.

**Comment by Mark-H** [comment]
@opengeek Do you feel strongly about this needing to use the xPDOCacheManager or is the current PR acceptable to you?

**Review by JoshuaLuckers — COMMENTED** [review]
Since it's a destructive action I'm in favour of providing a list with the actual files that where deleted instead of deleting everything.  A user/developer may have placed custom files in this directory.

**Comment by Jako** [comment]
I don’t think that placing any code there makes sense without referring the other minify code. But I can be wrong.

**Comment by Mark-H** [comment]
I'm with @Jako - that doesn't make a whole lot of sense to do. 

@opengeek This just needs your stamp.

**Review by opengeek — APPROVED** [review]

**Comment by OptimusCrime** [comment]
Can not believe I lived to see this got merged. Time for celebrations you guys!

**Pull request merged**
