### PR TITLE
Removed limit to getnodes for menu items

### LINKED ISSUE #12244: Only 10 items show up in menu editor
Only 10 items are showing up in the menu editor (Top Menu) underneath any particular menu heading. I've got more than 10 extras installed, but I can't sort them because they don't all show up under the Extras menu. I have to go into the back end and edit the menuindex using a MySQL editor. 

10menuitems

### PR DESCRIPTION
**Pull request by OptimusCrime**
Should fix #12244.

### CODE REVIEW

**Comment by OptimusCrime** [comment]
Edit: tested, so I know it fixes the issue.

**Comment by TheBoxer** [comment]
Heya,

Thanks for the PR, but please next time if it's a bug fix, it should be targeted to a master branch. I'll do cherry pick for this one ;)

**Comment by TheBoxer** [comment]
Cherry picked to master & merged to develop.

**Comment by OptimusCrime** [comment]
@TheBoxer vups, sorry, I should know that. I'll keep in mind the next time.

**Pull request closed without merging**
