### PR TITLE
Use the correct ISO 3166 code‎ for Sint Maarten

### PR DESCRIPTION
**Pull request by JoshuaLuckers**
### What does it do?
Renamed the array key for the Sint Maarten $_country_lang entry.

### Why is it needed?
The name of the key was wrong and also being used for another country. 

### Related issue(s)/PR(s)
#13822

### CODE REVIEW

**Comment by JoshuaLuckers** [comment]
It might be an issue for those who make already use of this value to show "Sint Maarten" instead of "Seychelles".

**Comment by alroniks** [comment]
Hi, @JoshuaLuckers Thank you for your contribution.
In the issue mentioned 2.6.1 version and it means that this PR is a bugfix and it should target 2.6.x branch instead of 2.x. Could you fix it, please?

**Comment by Jako** [comment]
Since there is a 'First-time contributor' sign: Have you signed the [CLA](http://develop.modx.com/contribute/cla/)?

**Comment by JoshuaLuckers** [comment]
@Alroniks Fixed it but did something wrong haha. Made a new pull request: #13836 

@Jako Yes I have! 👍

**Pull request closed without merging**
