### PR TITLE
2.5.x Fix for 500 error after install using STRICT_TRANS_TABLES mode in mySQL

### PR DESCRIPTION
**Pull request by thewhiterabbit**
### What does it do?

Changed the default field values for time based fields to NULL to comply with mySQL strict mode.
### Why is it needed?

Strict mode does not allow "zero" values for time based fields.
### Related issue(s)/PR(s)

https://github.com/modxcms/revolution/issues/12838#issuecomment-217008404

### CODE REVIEW

**Comment by thewhiterabbit** [comment]
Here you go, there should be no conflicts and I have tested this fix with success on mySQL 5.7.10. Should work in all versions of mySQL.

**Comment by thewhiterabbit** [comment]
I updated the pull request name/title to be clear what it is for. Sorry fro being Vague. ^.^

**Comment by pixelchutes** [comment]
@thewhiterabbit @jako what is `core/config/config.inc.tpl` for? Was that intended to be part of this commit?

**Comment by thewhiterabbit** [comment]
@pixelchutes The formatting could be returned to double space, I only did that to make it easier to find a nesting error that ultimately turned out to be a stray single quote. Not sure where the core.config.tpl should reside, was added for good measure. If it's redundant it could be removed.

**Comment by pixelchutes** [comment]
@thewhiterabbit I believe it's in [core/docs/](https://github.com/modxcms/revolution/blob/2.x/core/docs/config.inc.tpl) already.

**Comment by pixelchutes** [comment]
Thanks for your work on this patch and MySQL 5.7 testing. I will also be testing against MySQL 5.6 + strict mode shortly.

**Comment by Jako** [comment]
I have checked and merged this already without that tpl file in 2.5.x branch.

**Comment by OptimusCrime** [comment]
@Jako did you merge the switch from space to tabs, or did you just merge the changes in the models?

**Comment by Jako** [comment]
I merged all local, removed all changes in the map files, edited the schema a bit (removed some issues), built the map files from the schema, updated the changelog, made a commit with the remaining changes and pushed all to 2.5.x

**Comment by Jako** [comment]
See https://github.com/modxcms/revolution/commit/5324f9245a59c07abfa6f39c1d05673483cd89e5

**Comment by OptimusCrime** [comment]
You also included this commit: https://github.com/modxcms/revolution/commit/7250f21a9d54c674c8d7ff6a71523fbae1645992

**Comment by pixelchutes** [comment]
@Jako thank you. I see now the file itself in that commit was not merged.

**Comment by pixelchutes** [comment]
FYI `2.5.x` Git install build passes my tests on MySQL 5.6.30 (w/ Strict Mode enabled) and `explicit_defaults_for_timestamp = 0`. All 71 tables are created, no 500 error on setup. Clean error log.

Nice work!

**Comment by thewhiterabbit** [comment]
@pixelchutes Glad to see it's working in MySQL 5.6.30! :D

**Comment by goldsky** [comment]
```
[2016-05-13 10:14:18] (ERROR @ /var/www/html/test-modx-2.5.0/setup/includes/tables_create.php : 116) Could not create table `modx_manager_log`
SQL: CREATE TABLE `modx_manager_log` (`id` INTEGER unsigned NOT NULL AUTO_INCREMENT, `user` INT(10) unsigned NOT NULL DEFAULT '0', `occurred` DATETIME NULL DEFAULT '0000-00-00 00:00:00', `action` VARCHAR(100) NOT NULL DEFAULT '', `classKey` VARCHAR(100) NOT NULL DEFAULT '', `item` VARCHAR(255) NOT NULL DEFAULT '0', PRIMARY KEY (`id`), INDEX `user_occurred` (`user`,`occurred`)) ENGINE=MyISAM
ERROR: Array
(
    [0] => 42000
    [1] => 1067
    [2] => Invalid default value for 'occurred'
)

[2016-05-13 10:14:19] (ERROR @ /var/www/html/test-modx-2.5.0/setup/includes/tables_create.php : 116) Could not create table `modx_user_messages`
SQL: CREATE TABLE `modx_user_messages` (`id` INTEGER unsigned NOT NULL AUTO_INCREMENT, `type` VARCHAR(15) NOT NULL DEFAULT '', `subject` VARCHAR(255) NOT NULL DEFAULT '', `message` TEXT NOT NULL, `sender` INT(10) NOT NULL DEFAULT '0', `recipient` INT(10) NOT NULL DEFAULT '0', `private` TINYINT(4) NOT NULL DEFAULT '0', `date_sent` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00', `read` TINYINT(1) NOT NULL DEFAULT '0', PRIMARY KEY (`id`)) ENGINE=MyISAM
ERROR: Array
(
    [0] => 42000
    [1] => 1067
    [2] => Invalid default value for 'date_sent'
)
```

**Comment by Jako** [comment]
@goldsky Your issues can't occur after this commit https://github.com/modxcms/revolution/commit/5324f9245a59c07abfa6f39c1d05673483cd89e5 in the 2.5.x/2.x branches. The default value for occured in manager_log is NULL instead of 0000-00-00 00:00:00. Same for date_sent in user_messages.

**Pull request merged**
