### PR TITLE
Improvements for recently edited resources

### LINKED ISSUE #14334: Information is not displayed in the Recently Edited Resources panel.
### Summary
Information is not displayed in the Recently Edited Resources panel.

### Observed behavior
Here is the next bug:
- the resource id is not displayed correctly (if it is a resource)
- resource title is not displayed
- the date of resource editing is not displayed

### Expected behavior
Must correctly display a list with resources.

### Environment
The latest version of MODX 3.0.0pl recruited using composer.

### PR DESCRIPTION
**Pull request by wax100**
### What does it do?
Fix #14334 & #14333

### Why is it needed?
Describe the issue you are solving.

### Related issue(s)/PR(s)
#14334 & #14333

### CODE REVIEW

**Review by Ibochkarev — DISMISSED** [review]
This fix solves problem #14333 and #14334 - tested. Works!
Dashboard | MODX Revolution 2019-03-28 10-16-43

@wax100 Thanks!

**Review by Mark-H — DISMISSED** [review]

**Comment by Mark-H** [comment]
FYI #14540 also includes this fix.

**Review by JoshuaLuckers — DISMISSED** [review]

**Comment by sdrenth** [comment]
@wax100 Could you also add the following permission checks? I think its a neat addition to the fixes you already have done.

Because if you don't the permission "logs" you should not be able to view the view all link at the bottom, because the user has no permissions for viewing this page and will result in an "Access denied page".

### Requested changes ###
**manager/templates/default/dashboard/recentlyeditedresources.tpl**
```
{if $modx->hasPermission('logs')}
    <div class="widget-footer">
        <a href="{$_config.manager_url}?a=system/logs">{$_lang.w_view_all} &rarr;</a>
    </div>
{/if}
```

**webroot/manager/templates/default/dashboard/onlineusers.tpl**
```
{if $modx->hasPermission('logs')}
    <div class="widget-footer">
        <a href="{$_config.manager_url}?a=system/logs">{$_lang.w_view_all} &rarr;</a>
    </div>
{/if}
```

**Comment by sdrenth** [comment]
@wax100 Any thought about my last comment?

**Comment by gpsietzema** [comment]
@wax100 ? :-)

**Comment by wax100** [comment]
@gpsietzema  @sdrenth 
Sorry , I did not see your comments. 
And cant find branch  =) so I edit online. Hope, I did it correct

**Review by JoshuaLuckers — APPROVED** [review]

**Comment by sdrenth** [comment]
@Mark-H Could you maybe take another look at this PR?

**Comment by Ibochkarev** [comment]
пт, 28 июн. 2019 г., 12:39 Sander Drenth <notifications@github.com>:

**Comment by alroniks** [comment]
@sdrenth It should be rebased before next review loop.

**Comment by sdrenth** [comment]
@Alroniks I can't do the rebase. @wax100 Can you make sure the PR gets rebased to it can hopefully be merged in the next review loop?

**Review by Mark-H — APPROVED** [review]

**Comment by Mark-H** [comment]
The majority of this fix was already applied in the processors refactor. I've merged the conflicts which only applied the `logs` permission requirement into 3.x.

Thanks.

**Pull request merged**
