### PR TITLE
Fix issue when sending an internal message to the user

### PR DESCRIPTION
**Pull request by sergant210**
### What does it do?
Fixed a bug with the inability to send a message to the user. Added the option to send messages to user group.

### Why is it needed?
Error "User not found" occurs when trying to send a message to a user or role ("Role not found").

### How to test
Open Messages interface and try to create a message to any user or role.

### Related issue(s)/PR(s)
#15500.

### CODE REVIEW

**Review by Ibochkarev — APPROVED** [review]
https://user-images.githubusercontent.com/2138260/110237273-4de1cc00-7f65-11eb-8cd2-dbead244a44f.mp4

**Comment by alroniks** [comment]
I suggest applying such a fix in 2.x because it is also broken there. And just remove messages in 3.x at all. What do you think @opengeek?

**Comment by sergant210** [comment]
@alroniks There is no problem in 2.x.

**Comment by Ibochkarev** [comment]
> I suggest applying such a fix in 2.x because it is also broken there. And just remove messages in 3.x at all. What do you think @opengeek?

I propose to add this fix, and then in the future it will be possible to take out as a separate component

**Review by alroniks — APPROVED** [review]

**Pull request merged**
