### PR TITLE
Fix rendering of user-entered values in editable listbox-multiple TVs

### PR DESCRIPTION
**Pull request by smg6511**
### What does it do?
Back ports fixes already made and merged into 3.x. See the referenced PRs below for more info.

### Related issue(s)/PR(s)
Alternate to PR #16241; includes back ports of #16242 and #16561

### CODE REVIEW

**Comment by opengeek** [comment]
@smg6511 — I'm assuming that #16424 is not the PR you meant to reference?

**Comment by smg6511** [comment]
> @smg6511 — I'm assuming that #16424 is not the PR you meant to reference?

Oops, yes - it's supposed to be #16242

**Review by theboxer — APPROVED** [review]
thank you :)

**Comment by jenswittmann** [comment]
In my MODX 2.8.8 installation, I need to update the TV. Then the `preserveSelectionOrder` setting is added to the `input_properties` array in the database and the values are sorted as stored in the database. Without resaving after core update (missing entry in `input_properties` array) it will be sorted randomly. Can anyone else confirm this issue?

**Comment by modxcommunity** [comment]
This pull request has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/after-upgrading-to-3-x-log-filled-with-listbox-errors/8987/3

**Pull request merged**
