### PR TITLE
Update updatefromelement.class.php

### PR DESCRIPTION
**Pull request by kundius**
unset default properties

### CODE REVIEW

**Comment by pixelchutes** [comment]
@kundius can you please provide some more context? Is there an issue # describing the problem this PR aims to resolve, or any other additional information you can provide to help elaborate? e.g. Is this a new feature or fixing a specific bug?

**Comment by kundius** [comment]
I think it is a bug. The default parameters are not reset. Watch the [video](https://nimbus.everhelper.me/client/notes/share/610095/mnbzfbyo2i7ru0v5qw68).

**Comment by Mark-H** [comment]
Sorry @kundius that this has been open for so long, but I have no idea what this is fixing - the video shows adding a property set but what's not working as expected?

**Comment by kundius** [comment]
@Mark-H After saving, all default parameters are written to the parameter set.

**Comment by opengeek** [comment]
I had no idea this PR existed when I ran into this bug recently. My apologies. Fixed via #13799.

**Pull request closed without merging**
