### PR TITLE
Corrected styles for right-to-left text direction

### PR DESCRIPTION
**Pull request by Ruslan-Aleev**
### What does it do?
1) Corrected styles for right-to-left text direction.
Basically made the styles symmetrical, like ` margin-right: 10px; ->  margin: 0 10px;`

Before:
manager_direction_rtl

After:
after

2) Changed styles of submenu position.
If the `top`, `right`, `bottom` and `left` css-attributes are set, then these attributes are combined into a single `inset` attribute. I don't know if this is the behavior of new browsers or something else.
But with `inset` the menu is not positioned correctly.
Removed `bottom` and `right` attributes, since and without them the menu is positioned normally.

Before:
m_before

After:
m_after

**See the `manager_direction` setting. To test this you can change the system setting `manager_direction` to `rtl`.**
Please test PR carefully, both with the direction of the text from right to left, and in the opposite.

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/issues/15733

### CODE REVIEW

**Comment by Ruslan-Aleev** [comment]
p.s. as it turned out, in the 2nd branch it is still worse with the direction from right to left :)

**Comment by JoshuaLuckers** [comment]
To test this you can change the system setting `manager_direction` to `rtl`.

**Comment by Ruslan-Aleev** [comment]
@Mark-H when you have time, test the PR.
p.s. Because you added this issue to your "MODX3 Final Sprint" table :)

**Review by JoshuaLuckers — APPROVED** [review]

**Comment by Mark-H** [comment]
Great work 🙌 

It does seem to have a bug where there's a horizontal scroll on the main panel when it's set to rtl:

afbeelding

Seems to go on for like 10x the window size... doesn't show when set to ltr. I'm not immediately seeing where it's coming from, unfortunately :/ 

(Tested on Firefox 90, win10)

**Comment by JoshuaLuckers** [comment]
@Mark-H @Ruslan-Aleev I pushed a commit with a fix for this issue.

**Comment by Ruslan-Aleev** [comment]
@JoshuaLuckers Thank you, I will test it soon :)

**Comment by Ruslan-Aleev** [comment]
Everything seems to work as it should :)

**Pull request merged**
