### PR TITLE
[3.x] Corrected lexicon for media source editing in tree

### PR DESCRIPTION
**Pull request by Ruslan-Aleev**
### What does it do?
Same as in https://github.com/modxcms/revolution/pull/15737, but for 3.x branch

### CODE REVIEW

**Comment by JoshuaLuckers** [comment]
This PR is marked as draft.

**Review by JoshuaLuckers — APPROVED** [review]

**Comment by Ruslan-Aleev** [comment]
I'm still waiting for the https://github.com/modxcms/revolution/pull/15737 merger, as the correct lexicon will appear for the 3.x branch as well. Therefore, while a draft.

**Review by Ibochkarev — APPROVED** [review]

**Comment by theboxer** [comment]
@Ruslan-Aleev the mentioned PR is merged for some time, can you update this PR so we can merge it as well?

**Comment by Ruslan-Aleev** [comment]
@theboxer I thought that the `edit_media_source` lexicon that I added to the https://github.com/modxcms/revolution/pull/15737 will appear for branch 3 as well.
But, apparently, it is necessary to create a separate lexicon.
We can leave the `edit` lexicon, but the `edit_media_source` lexicon would be more appropriate.

**Comment by Ruslan-Aleev** [comment]
Although the question is not very important, we can merge it.

**Review by theboxer — APPROVED** [review]

**Review by opengeek — APPROVED** [review]

**Pull request merged**
