### PR TITLE
Added tabs for manager section templates

### PR DESCRIPTION
**Pull request by Ruslan-Aleev**
### What does it do?
I made the design of the manager sections to one view, adding tabs on top.

template_panel
Removed unnecessary styles for sections without tabs (since there were no tabs, these styles were added).

Slightly fixed the styles for `.panel-desc`:

before
after
There were useless styles, especially for the resource, I simplified them. In the future, styles will be easier to edit, and `.panel-desc` does not look bad with a white background.

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/issues/14663

### CODE REVIEW

**Review by Mark-H — DISMISSED** [review]

**Comment by JoshuaLuckers** [comment]
If your window is a bit smaller then usual these changes will add a vertical scrollbar when viewing system settings.

Before: 
Screenshot 2019-09-01 at 13 17 05

After: 
Screenshot 2019-09-01 at 13 17 18

**Comment by Ruslan-Aleev** [comment]
@JoshuaLuckers Yes you are right. I wanted to make the template in "System Settings" the same as in the "Lexicons", but I did not check the width of the screen.
However, there is also a problem for the "Lexicons", see below:

lexicons

**Maybe it makes sense to remove the explanatory text for both templates?**

@Mark-H what do you think?

**Comment by JoshuaLuckers** [comment]
The labels add value and should stay. Is it possible to place them about the elements they describe?

**Comment by Ruslan-Aleev** [comment]
Another option is to reduce the width of the elements :)
Correcting the layout will not work, because output in tables.
Placing the label inside the lists will not work either, because in the main section controller, the first in the list should be "core" (here I'm not sure).

**Comment by Mark-H** [comment]
@Ruslan-Aleev  I don't know what the best way to solve that is, sorry.

**Comment by Ruslan-Aleev** [comment]
I think we can reduce the elements width. @JoshuaLuckers what do you think?
Although this does not help, because with a minimum screen width, the labels will not fit in any way.

**Comment by JoshuaLuckers** [comment]
If you can solve the conflict I'll approve this PR and we can figure out a solution with a new PR.

**Comment by Ruslan-Aleev** [comment]
Well, in general, the purpose of this PR was to add tabs on top.
I added labels myself, because similar ones were in “Lexicons” and I thought that in “System Settings” labels would be useful.
But this problem does not apply to this PR, it has always been.
How to solve it - I don’t know, I can return it as it was - by deleting the labels from the "System Settings", but the labels in the "Lexicons" always were, and they also did not fit in width.

**Comment by JoshuaLuckers** [comment]
Revert the changes not part of the original intend and create a new issue for the labels (and issues they cause). 😄

**Comment by Ruslan-Aleev** [comment]
@JoshuaLuckers I removed the labels in the "System Settings", but here the problem is in extJS, because all layouts made with tables.
This behavior on all grids of the MODX manager panel, I will create an issue, but in my opinion it is useless as long as there is extJS in the manager panel =)

**Review by JoshuaLuckers — APPROVED** [review]

**Review by Mark-H — APPROVED** [review]

**Comment by Mark-H** [comment]
Thanks @Ruslan-Aleev. 

Just so you know for the next time, an interactive rebase (`git rebase -i upstream/3.x`) is prefered over merging 3.x into your branch to avoid extra commits making their way in. See my comment [here](https://github.com/modxcms/revolution/pull/14572#issuecomment-529673427) for a bit more detail over how you can do that.

**Pull request merged**
