### PR TITLE
Add missing attribute "unsigned" in schema

### PR DESCRIPTION
**Pull request by andchir**
### What does it do?
Added missing attribute "unsigned" in schema and re-generate classes.

### Why is it needed?
See issue description.

### Related issue(s)/PR(s)
#12419 #14745

### CODE REVIEW

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to submit this PR and help make MODX better. Since you are a first-time contributor; please sign the the [Contributor License Agreement (CLA)](https://modx.com/community/contribute/cla/).

**Comment by Ibochkarev** [comment]
> Thanks for taking time to submit this PR and help make MODX better. Since you are a first-time contributor; please sign the the [Contributor License Agreement (CLA)](https://modx.com/community/contribute/cla/).

Signed later https://github.com/modxcms/revolution/pull/14772

**Review by Mark-H — DISMISSED** [review]

**Comment by Jako** [comment]
@andchir Now you have added some other commits to your PR because you did not work on an extra branch for this commit.

**Comment by JoshuaLuckers** [comment]
@andchir If you need any help with fixing this PR/commits please let us know.

**Comment by andchir** [comment]
> @andchir If you need any help with fixing this PR/commits please let us know.

@JoshuaLuckers What should I fix? Do I need to split this PR into two?

**Comment by opengeek** [comment]
@andchir You need to remove the unrelated commits you added.
image

**Comment by andchir** [comment]
@opengeek 
> @andchir You need to remove the unrelated commits you added.

Done.

**Comment by andchir** [comment]
You mean I have to remove "merge" commits? Then you had to point to a specific commit, not write "some other commits" or "unrelated commits". Sorry, it's hard for me to understand you. Can you fix it yourself?

**Comment by Mark-H** [comment]
The process is typically:

```
git rebase -i upstream/3.x
```

Should open an editor; make sure each line with only the target commit starts with `pick` and everything else with `skip` (read the instructions shown). Exit the editor `:wq`, and it will apply the changes.

Then force push your branch.

```
git push --force origin my-feature-branch
```

In this case you used `3.x` instead of a feature branch; in the future it's best to start by creating a new branch: `git checkout -b feature/something-here`, which makes it easier to isolate changes.

**Review by opengeek — CHANGES_REQUESTED** [review]
You have included changes for two different issues into one PR. We prefer to have them separate. That was the point of asking for the two unrelated commits to be removed. I would have loved to get the unsigned attribute changes in for alpha 1, but the changes involving removing columns from the schema are incomplete (this will also need to be accompanied by an upgrade script which removes the columns from the table) and so the whole PR cannot be included for now. In addition, the removal of columns needs thorough testing before being included, and that is going to make it impossible to include this in alpha-1. Moving to alpha-2. It would still be preferable to separate these two unrelated changes into individual PRs.

**Comment by andchir** [comment]
Looks like I have broken everything. Unsuccessful rebase. Can you cancel the PR? I am making a new one.

**Pull request closed without merging**
