### PR TITLE
Added missed target=blank

### PR DESCRIPTION
**Pull request by alroniks**
### What does it do ?

Added missed target=blank for extranl link from system settings. 
### Why is it needed ?

It useful when you see new option and you can go to site with docs for reading in new tab and then you can return to opened tab and set value that needed.
### Related issue(s)/PR(s)

Fix for this https://github.com/modxcms/revolution/issues/12570

### CODE REVIEW

**Comment by theboxer** [comment]
@Alroniks Not sure why, but your PR includes also some other commits, can you please clean it?

**Comment by Alroniks** [comment]
@theboxer Looks like that my mirror repo not synced with current repo and if I try send commit to 2.4.x via github, git add other commits too.

**Comment by Alroniks** [comment]
I've added new commit to 2.x branch https://github.com/modxcms/revolution/pull/12686

**Comment by theboxer** [comment]
Thanks

**Pull request closed without merging**
