### PR TITLE
Replace all hardcoded http versions by $_SERVER['SERVER_PROTOCOL'] va…

### PR DESCRIPTION
**Pull request by alroniks**
### What does it do?
It changes all headers and replaces hardcoded HTTP protocol versions to an actual version that comes from the webserver. 

### Why is it needed?
Webserver can request pages using different http protocol version (1.0, 1.1, 2.0) and backend (MODX) should answer with the same protocol version.

### Related issue(s)/PR(s)
#9751
#modxbughunt

### CODE REVIEW

**Comment by sonicpunk** [comment]
#modxbughunt #3points to @Alroniks

**Comment by Flowan** [comment]
Tested this and can confirm this works! #modxbughunt

**Comment by Mark-H** [comment]
In case anyone wondered about the security of the protocol version with escaping, looks like its reliable as enforced by the web server https://stackoverflow.com/a/6474936

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @Flowan

**Comment by rtripault** [comment]
I did not review all the changed files, but having concerns about accessing `$_SERVER['SERVER_PROTOCOL']` when using the CLI

**Comment by Mark-H** [comment]
Valid concern, but the changes seem to mostly be in request/response/fatal error handlers.. while it won't be available from the CLI, I doubt these would get called from the CLI? 

Adding an isset/array_key_exists could be an option to be safe, but as these are all setting headers that don't have meaning on the CLI anyway, I think we'll be fine without it...

**Comment by Alroniks** [comment]
My main concern about inconsistency in RFC of HTML that could be unknown. In a common way, an application should answer by the same protocol version but I am not sure that it will work always and fine. For CLI yes, it doesn't matter, headers work only with webservers.

**Comment by sdrenth** [comment]
@Alroniks I've found that in /core/model/phpthumb/ some http versions are still hardcoded:

* Line 538
* Line 559
* Line 645

**Comment by OptimusCrime** [comment]
@sdrenth That is an external project. We are unable to rewrite the code there. It would get overwritten when we upgrade PhpThumb to a newer version. I think we have to ignore those occurrences.

**Comment by sdrenth** [comment]
@OptimusCrime I understand, you may ignore my comment ;)

**Comment by OptimusCrime** [comment]
Great work btw!

**Pull request merged**
