### PR TITLE
Version number fix Smarty, PHPmailer

### PR DESCRIPTION
**Pull request by Ibochkarev**
### What does it do?
Version number fix Smarty, PHPmailer

### Why is it needed?
This fix is necessary for the correct display of information.

### Related issue(s)/PR(s)
#14515

### CODE REVIEW

**Review by JoshuaLuckers — APPROVED** [review]

**Comment by JoshuaLuckers** [comment]
It would be great if we if we no longer had to do this manually.
Smarty defines its version using a constant: https://github.com/modxcms/revolution/blob/e73b0adb95ffc003d8f6ef9dfaf467e4be428bd6/core/model/smarty/Smarty.class.php#L115

PHPMailer has a public variable for its version number: https://github.com/modxcms/revolution/blob/bda48ec0189ea6a4ab467f6f9010dc9a79374de3/core/model/modx/mail/phpmailer/class.phpmailer.php#L34

**Comment by Ibochkarev** [comment]
@JoshuaLuckers You can do it in the 3rd branch. But I can not do it myself. There is no knowledge.

**Comment by Jako** [comment]
You could add the smarty/phpmailer version after constructing/initializing their classes in the process method of manager/controllers/default/system/info.class.php to the modx.config array.

i.e. 
```
$this->modx->getService('smarty', 'smarty.modSmarty');
$this->modx->setOption('smarty_version', SMARTY_VERSION);
```

and refer to that  in the info.js

i.e. 
```
        fieldLabel: _('smarty_version')
        ,name: 'smarty_version'
        ,value: modx.config.smarty_version	
```

**Comment by Jako** [comment]
Closing this in favor of #14517

**Pull request closed without merging**
