### PR TITLE
Update MODX logo and icon

### PR DESCRIPTION
**Pull request by Ibochkarev**
### What does it do?
Update MODX logo and icon

### Why is it needed?
Updates to the current state

### How to test
Pick up the changes in this PR and test =)

Before:

2021-03-05 12-36-44 MODX Revolution 3 0 0-alpha3 » Установить - Google Chrome

After:

### Related issue(s)/PR(s)
NA

### CODE REVIEW

**Comment by Ruslan-Aleev** [comment]
Edits from https://github.com/modxcms/revolution/pull/15405 need to be added too :)

**Comment by Ruslan-Aleev** [comment]
By the way, it makes sense for separate PRs to change the green color, because now it does not match the logo, although it used to be.
@rthrash What do you think?

green_1

green_2

**Comment by Jako** [comment]
> By the way, it makes sense for separate PRs to change the green color, because now it does not match the logo, although it used to be.

The new color is more blue than green, so it could stay at that state.

**Comment by Ruslan-Aleev** [comment]
> The new color is more blue than green, so it could stay at that state.

On the spectrum, the new color is more green, hehehe:

green_3_0

But this is the color I would not use - the contrast drops, but I would make it darker to match the logo.

green_3

These are only thoughts so far.

**Comment by JoshuaLuckers** [comment]
It's best to keep the discussion in this PR related to the new logo and to discuss the color changes in a new issue/PR.

**Comment by Jako** [comment]
But that's not a bug.

**Comment by Ruslan-Aleev** [comment]
I will create a feature request, after the merge, to discuss in the future.

**Review by JoshuaLuckers — CHANGES_REQUESTED** [review]
The setup is using the old favicon `setup/favicon.ico`.

**Comment by Ibochkarev** [comment]
> The setup is using the old favicon `setup/favicon.ico`.

Can't get updated in ico format

**Comment by Jako** [comment]
Use the ones from https://modx.com/

**Review by Jako — CHANGES_REQUESTED** [review]
Please use this https://modx.com/favicon.ico

**Comment by Jako** [comment]
The favicon is not the right one. Please use https://modx.com/favicon.ico.

**Comment by Ibochkarev** [comment]
> The favicon is not the right one. Please use https://modx.com/favicon.ico.

Thank you, I will send corrections today.

**Comment by Ibochkarev** [comment]
@Jako done

**Review by JoshuaLuckers — APPROVED** [review]

**Review by theboxer — APPROVED** [review]

**Review by Jako — APPROVED** [review]

**Pull request merged**
