### PR TITLE
Built in replace braces method for MODX tags sanitization

### PR DESCRIPTION
**Pull request by AgelxNash**
Security reason

### CODE REVIEW

**Comment by Mark-H** [comment]
Could you please provide details of security issue to security@modx.com so we know what/how to properly test this?

**Comment by AgelxNash** [comment]
It just a helper method. This method should be used by the developers of snippets.

**Comment by MrRoco** [comment]
Tested & works fine

**Comment by Jako** [comment]
This helper method makes the replacement recursive for array values. Thats nice.

But the naming of the method is somehow strange, since it does not only replace braces.

**Comment by Mark-H** [comment]
I'm happy with adding this helper, but would appreciate @opengeek weighing in.

**Comment by opengeek** [comment]
I agree about the method name, but this otherwise seems solid. Do we have any alternative ideas? I'd be happy to refactor it on merge to address that issue.

**Comment by Jako** [comment]
Maybe it should be called `replaceArrayValues` or `recursiveReplaceArrayValues`

**Review by Mark-H — APPROVED** [review]
Prime example of bikeshedding, but perhaps `sanitizeTags` or `escapeMODXTags` would be more descriptive. Thanks @AgelxNash.

**Comment by opengeek** [comment]
I'm sorry, but coming to agreement on a method name that is added to the main class of the software is not exactly bikeshedding. If it goes on for 10 messages, I would agree, but I was just asking for a few suggestions as I could not think of a good name at the time I reviewed this.

**Comment by alroniks** [comment]
I agree with Jason, current name not the best option. A public method that should be widely used should have a more intuitive name.
My vote for a `escapeMODXTags` or more generic `escapeReservedSymbols`

**Comment by Jako** [comment]
Since it is used without escaping MODX tags in https://github.com/modxcms/revolution/pull/14099/files#diff-b6cd1dec11656d0ae875f625ee8494ef the method could be simply named `escapeTags`

**Comment by AgelxNash** [comment]
Just ```modx::replacements()```

**Comment by opengeek** [comment]
This PR is superseded by #14156.

**Pull request closed without merging**
