### PR TITLE
Prevent E_NOTICE errors from smarty TV templates [13748]

### PR DESCRIPTION
**Pull request by Bruno17**
### What does it do?
Fix bug 13748

### Why is it needed?
Solves undefined-index notices in smarty-TV-templates

### Related issue(s)/PR(s)
see https://github.com/modxcms/revolution/issues/13748

### CODE REVIEW

**Comment by Mark-H** [comment]
@Bruno17 Please use a better PR title next time ;)

**Comment by Bruno17** [comment]
@Mark-H will try, thanks for correcting

**Comment by superspace** [comment]
@Bruno17 I reproduced the notices on the migx-form. After checking out your PR the notices no longer showed up – but they're still on the resource edit-form.

**Comment by Mark-H** [comment]
Thanks @Bruno17 - cleans up quite a few messages!

**Pull request merged**
