### PR TITLE
Allowing empty resource pagetitle. Will be set automatically to "Untitled Resource {id}"

### PR DESCRIPTION
**Pull request by bertoost**
### What does it do ?

It checks if you submit empty pagetitles and when you do, it uses Lexicon "resource_untitled" concatenated with the new ID of the resource and also updates the alias when you create a new resource.
At update, it is checking the pagetitle again to, also updating the title, not the alias.
Also added a system setting "resource_allow_empty_pagetitle" to enable/disable this feature.
### Why is it needed ?

It's not really necessary but it's a cool feature to allow empty pagetitles at creation and updating. Especially for those who sets the pagetitle hidden in FC
### Related issue(s)/PR(s)

Should resolve https://github.com/modxcms/revolution/issues/12239

### CODE REVIEW

**Comment by Mark-H** [comment]
Hiya Bert, thanks for the contribution. 

In create.class.php there is now a preparePageTitle and setPageTitle method.. could that be consolidated? Or is it useful to have both?

**Comment by TheBoxer** [comment]
IMO this should be an extra and not part of the core.

**Comment by bertoost** [comment]
@Mark-H Because mine has a setting it's good to have both I think? And both are fired on different moments :$ setPageTitle() can be out, but I thought not to break existing features :-)

@TheBoxer If that's possible at all; since this is checked in core files? Then you should override the core files or such?

**Comment by TheBoxer** [comment]
@bertoost I was thinking about two options:

1. OnDocFormPrerender plugin, which will set & hide the pagetitle field via JS
2. Combination of FC (hide pagetitle & set some default value - for example XXX) and OnDocFormSave plugin, which will set pagetitle to whatever you wish (GeneratedPagetitle 1)

**Comment by bertoost** [comment]
@TheBoxer But you also need to set "allowBlank" to "false" then.. which of course can be handled with some JS magic...
I leave this up to you.. it's a nice to have and not a must I think :-)

**Comment by TheBoxer** [comment]
In both options I wrote you don't have to worry about allowBlank field, because you'll set the value to that field (so it will not be empty after submitting the form)

**Comment by TheBoxer** [comment]
Closing as it should be an extra :)

**Pull request closed without merging**
