### PR TITLE
Update Template Build Process

### PR DESCRIPTION
**Pull request by smg6511**
### What does it do?
Replaces most legacy dependencies with current versions—with the exception of bourbon, neat, and fontawesome—and drops others that are no longer relevant (such as imageoptim).

### Why is it needed?
Bring 2.x more in line with 3.x, mainly allow use of modern js features.

### How to test

1. Run the rebuild processes, including `npm update` within the `_build/templates/default` directory.
2. Run `grunt build`. 
3. Clear your manager and browser cache, then browse around the manager with your console open to verify all works as expected and no errors are being reported.

Note that grunt build will spit out some warnings, as the versions of bourbon and neat we need to stick with here (for now at least) are ancient and contain some long-deprecated code. I attempted to bring these dependencies up to date (including fontawesome) but there are many breaking changes that make it difficult to unwind and get everything working. Might try that later if there's enough "life" left in the 2.x line and it's deemed beneficial to do so.

### Related issue(s)/PR(s)
Resolves issues with building after including the following PRs: #16493 and #16467.

### CODE REVIEW

**Comment by opengeek** [comment]
Shouldn't this include the updated package-lock.json file? If I run npm update, changes are made to the package-lock.json, which then needs to be committed again.

**Comment by smg6511** [comment]
> Shouldn't this include the updated package-lock.json file?

I may be mistakenly thinking I shouldn't include it, which is why I didn't. I'll add a commit with it in just a bit...

**Comment by opengeek** [comment]
> > Shouldn't this include the updated package-lock.json file?
> 
> I may be mistakenly thinking I shouldn't include it, which is why I didn't. I'll add a commit with it in just a bit...

Well, I am asking. In the PHP/composer world, you want the composer.lock file to set the dependencies to avoid differences when multiple people install the dependencies. I know that we do not include the composer.lock file in the revo project, but that is a special case since revo is essentially a framework. I would think we would want that in the case of the assets build, however. And if we don't, should it be removed from the repo?

**Comment by smg6511** [comment]
I think you're right to want it in there after quick investigation.

**Pull request merged**
