### PR TITLE
3.0.x -> 3.x

### PR DESCRIPTION
**Pull request by Mark-H**
### What does it do?
Describe the technical changes you made.

### Why is it needed?
Describe the issue you are solving.

### How to test
Describe how to test the changes you made.

### Related issue(s)/PR(s)
Provide any issue that's addressed by this change in the format "Resolves #<issue number>", and mention other issues/pull requests with relevant information.

### CODE REVIEW

**Comment by Mark-H** [comment]
@opengeek Any objections to me doing a regular merge fixing the conflicts on this? Or would you prefer to handle this yourself?

**Comment by opengeek** [comment]
I absolutely do NOT want to do merges like this. Most of those changes are already in there. If something specific was merged into 3.0.x and not put into 3.x, that needs to be dealt with individually. I handle this manually with cherry-picks when merging PRs targeting one or the other when the changes need to be in both.

**Comment by Mark-H** [comment]
Alright. It's just confusing that the changelog doesn't list anything past 3.0.3, so I don't know how to make sure all fixes made it into 3.1. Unless all the 3.0.x changes need to be cherry picks from things merged into 3.x? 

For what it's worth I've only done merges into 3.x today.

**Comment by opengeek** [comment]
The changelog isn't updated at all. The commit log is what matters. Whatever you merged into 3.x which needs to go in 3.0.x, should be manually merged into 3.0.x. If you need me to handle this, I will, but I would prefer in the future that this get done for each PR as we go so that we are sure it applies and is tested against each branch individually.

**Comment by opengeek** [comment]
It is critical that each merge is done to both branches. The commit log can then be used to generate the changelog entries at the end of the release cycle with no effort.

**Pull request closed without merging**
