### PR TITLE
Added a empty check for option values in TV

### PR DESCRIPTION
**Pull request by Ruslan-Aleev**
### What does it do?
Added a empty check for option values in TV for which the option values are required.
If the option values are not set, an error message is displayed.
Also, unnecessary scripts are not generated for such TV, if the option values are not set.
Slightly corrected code.

### How to check:
1) Create a TV with an input type for which option values are required, for example, checkbox.
2) Do not set in the option values when TV create.
3) Go to the resource where this TV is and save.

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/issues/14177 
#11823

### CODE REVIEW

**Review by JoshuaLuckers — COMMENTED** [review]
Instead of committing the same type of changes for each file individually it's better to group them together in one commit. This ensures a good history of the changes and makes it easier to, for example, undo the changes if needed.

**Comment by Ruslan-Aleev** [comment]
Thanks for the info, I haven't figured out much with git yet.
Can you give a correct example?

**Comment by Jako** [comment]
The integrators could do a squash commit.

**Comment by JoshuaLuckers** [comment]
Can you provide some more info and steps how we can validate the changes you made? I tested the changes and they do not seem to work for me.

**Comment by Ruslan-Aleev** [comment]
@JoshuaLuckers Added information to the PR description.

**Comment by JoshuaLuckers** [comment]
Thanks, now it makes sense. 

Is there a reason why the presence of "Input Option Values" isn't checked when creating/editing a Template Variable?

**Comment by Ruslan-Aleev** [comment]
Yes, it is odd, in general are a lot of bugs in the form of creating a TV, for example, the "Allow Blank" field does not work everywhere (for some TV it does not exist at all, although it should be for all TV), the "Input Option Values" field is not needed for some TVs, but it is.
I think, checking the "Input Option Values" when creating a TV is a more competent variant.

**Comment by Ibochkarev** [comment]
Guys, we probably forgot about this PR. It is necessary to restore justice and check it. :sunglasses:

**Comment by Ruslan-Aleev** [comment]
Can anyone help with this issue - https://github.com/modxcms/revolution/issues/14424?
Then this PR can be closed, because I did not do it very well here.

**Pull request closed without merging**
