### PR TITLE
Remove unused and outdated xmlrpc and jsonrpc classes

### PR DESCRIPTION
**Pull request by alroniks**
### What does it do?
It removes outdated classes that rarely on never used last time. In this case - `xmlrps` and `jsonrpc` staff.

### Why is it needed?
Because an original refactoring pull request is too big to review it will help to bring fixes a bit faster splitting refactoring into small pieces.

### Related issue(s)/PR(s)
#13900

### CODE REVIEW

**Comment by OptimusCrime** [comment]
This is awesome! Nice work :) I like the diff size:

+0 lines
-7,654 lines

:D

**Review by Mark-H — APPROVED** [review]
Excellent!

**Review by Mark-H — CHANGES_REQUESTED** [review]
There's actually even more we can remove here that should probably be removed at the same time. `modXMLRPCResource` and `modJSONRPCResource` resource classes + their mysql/sqlsrv variants + the references to it in the schemas. That's where those responses classes were used.

**Comment by alroniks** [comment]
@Mark-H I added 9 new lines (I had to :/) and removed yet 133 :)

**Review by Mark-H — APPROVED** [review]
Awesome!

**Comment by ilyautkin** [comment]
PR is tested. Everything works as usual. Nothing was broken.

**Comment by alroniks** [comment]
Hi @opengeek Could we delete this files? Yes, I am asking for approve :)

**Review by opengeek — APPROVED** [review]

**Pull request merged**
