### PR TITLE
Rewrite to fix duplicates of the main page

### PR DESCRIPTION
**Pull request by Ibochkarev**
### What does it do?
The same content on the main page of your site should not be placed on different URLs (index.php, index.html, index.htm, etc.), because search engines will index each page and will not treat duplicate content well.

### Why is it needed?
Added example redirect to fix duplicates of the main page

### Related issue(s)/PR(s)
NA

### CODE REVIEW

**Comment by JoshuaLuckers** [comment]
Can you provide more information about how search engines index the "main" page of a website? 

To quote @Mark-H https://github.com/modxcms/revolution/issues/14244#issuecomment-524105576
> I think it's best to trim down the default to only cover the essentials, and put additional stuff in the docs. [..]

**Comment by theboxer** [comment]
@Ibochkarev can you please provide the requested details?

**Comment by Ibochkarev** [comment]
> @Ibochkarev can you please provide the requested details?

@JoshuaLuckers @theboxer 
https://www.seo.com/blog/3-common-url-problems-and-how-to-fix-them/ Problem #2: Duplicate Home Page URLs
https://www.contentkingapp.com/academy/duplicate-content/  Index pages (index.html, index.php)

**Comment by theboxer** [comment]
After reviewing these links and some other PRs for editing htaccess, I'd vote for putting all of this to docs and include also a way how to achieve this for nginx.

**Comment by JoshuaLuckers** [comment]
I agree with @theboxer and therefore I'm closing this PR. Thanks for taking time to submit this PR @Ibochkarev!

**Pull request closed without merging**
