### PR TITLE
Detectable license

### PR DESCRIPTION
**Pull request by JoshuaLuckers**
### What does it do?
As a best practice the full license file should be placed in the root of the repository. It also makes it better detectable by automation tools.

### Why is it needed?
If this PR is accepted:
- GitHub will be able to detect the license and people who visit the repository will see it at the top of the repository page. 
- This repository will show up when search results are being filtered based on their license.

### Related issue(s)/PR(s)
#14023

### CODE REVIEW

**Comment by alroniks** [comment]
Copyright of MODX missed in the new license file. I guess it's an issue.

**Comment by JoshuaLuckers** [comment]
@Alroniks the MODX copyright is in the README file. The license actually prohibits changing the content of the license file.

**Review by Mark-H — DISMISSED** [review]

**Comment by opengeek** [comment]
I suppose this change would necessitate a slight change to the headers we just changed throughout the codebase which indicate the full copyright and license information are in the LICENSE file.  🤪

**Comment by JoshuaLuckers** [comment]
It's easier to change now 🤣. To what can I change the header?

**Comment by OptimusCrime** [comment]
It should not have the .md file ending as well. This applies markdown syntax, which ruins the license: https://github.com/modxcms/revolution/blob/3b7998d5191e812318667b1a2afb08e71bfdf83e/LICENSE.md

Have it without the file ending, just LICENSE

**Pull request closed without merging**
