### PR TITLE
Enhance textarea tv type

### LINKED ISSUE #5512: TV input type "textarea" not high enough
mindeffects created Redmine issue ID 5512

TV input type "textarea" is not high enough. RTFM says "about 15 lines", I count only about 8 lines (Chromium 15.x and FF5).

I will also write a feature request for textareas with editable height. Don't want to mix bugs and features. ;-)

### PR DESCRIPTION
**Pull request by smg6511**
### What does it do?
Adds new input options to control input height.

### Why is it needed?
Currently this input type is restricted to its default size of 140px.

### How to test

1. Rebuild the manager template (cd to `_build/templates/default` and run `grunt build`)
2. Clear MODX caches
3. Create a few textarea type TVs to test the three new options (height, auto grow, and resize)

### Related issue(s)/PR(s)
Resolves #5512

### CODE REVIEW

**Comment by jaygilmore** [comment]
@smg6511  This does seem to function and it's a nice add. 

One note, however, upon creation, until you change the values set for the Grow or Resizable input options, Revo throws a warning about undefined keys but once you change the input values the first time, this resolves.

```
[2024-05-31 13:59:15] (ERROR @ core/src/Revolution/Processors/Element/TemplateVar/Configs/mgr/inputproperties/textarea.php : 19) PHP warning: Undefined array key "textareaGrow"
[2024-05-31 13:59:15] (ERROR @ core/src/Revolution/Processors/Element/TemplateVar/Configs/mgr/inputproperties/textarea.php : 20) PHP warning: Undefined array key "textareaResizable"
```

 It shouldn't require changing of the values as many people may not want to or need to change the values.

**Comment by smg6511** [comment]
@jaygilmore Ok, got that covered. Thanks for taking a look.

**Review by jaygilmore — APPROVED** [review]
Looks good to me. :)

**Review by theboxer — APPROVED** [review]
looks good!

**Review by jaygilmore — APPROVED** [review]

**Pull request merged**
