### PR TITLE
(Enhancement + Code) Manager doesn't show users fullname in header 

### PR DESCRIPTION
**Pull request by JaWe09**
https://github.com/modxcms/revolution/issues/12457

### CODE REVIEW

**Comment by OptimusCrime** [comment]
Is this system setting already implemented in the setup?

**Comment by wuschigesetwas** [comment]
@OptimusCrime nope sorry. But it's failsave if there is no setting it will take login as usual

**Comment by Mark-H** [comment]
Hi @wuschigesetwas! Thanks for sending a pull request with that improvement. I've got a few questions/tips/feedback. 

1) Have you signed the MODX CLA before? If not, please visit http://develop.modx.com/contribute/cla/ and sign the agreement in order for us to accept your contribution. Please let me know your MODX.com username too. 

2) Please follow the contribution guidelines (see https://github.com/modxcms/revolution/blob/master/CONTRIBUTING.md#submit-a-pull-request) when sending a pull request. This includes a simple template to use for the pull request description to make sure all relevant information is there.

3) I would recommend creating separate feature branches on your fork for each pull request. Right now you committed directly to your master branch which will make it harder for you to send other pull requests if a pull request is not accepted or merged into another branch. Which brings me to.. 

4) This looks like a new feature rather than a bug fix, so this will need to go into develop (targeting 2.4) rather than master (targeting 2.3.x). 

5) The system setting will need to be added to the build so it is created on install. As it's a new setting, just adding it in `_build/data/transport.core.system_settings.php` will do the trick. Please also add a name and description for the setting to the English lexicon (English only - other languages are managed via translate.modx.com) in `core/lexicon/en/setting.inc.php`. 

6) Finally (sorry this became a longer list than I thought), does it make sense to use "manager_use_fullname" instead of "manager_use_realname"? A fullname doesn't have to be a real name, and the used field is called fullname too.

**Comment by wuschigesetwas** [comment]
@Mark-H thank you a lot for all these helpfull tips. I wasn't aware of that all :).
CLA ist signed now modx.com username is "dunklertempler" (i known strange usernames ... ).

i think it would be better if i would reset my fork to upstream and create a new feature branch considering all you've mentioned above and after that create a new pull request ?!

Best Regards,

Jan

**Comment by Mark-H** [comment]
Thanks for signing the CLA, Jan! Starting with a new branch and sending a new PR might indeed be the best option :)

**Comment by wuschigesetwas** [comment]
@Mark-H okay so we'll close this one ... :) and i'll come back on that with a new pull request :)

**Comment by wuschigesetwas** [comment]
Hello @Mark-H,

is #12527 okay that way ?

**Comment by Mark-H** [comment]
From a first look that seems great (though there seems to be a merge conflict, which is odd, but I can't immediately see why).

**Comment by wuschigesetwas** [comment]
mhm different bases may be but i think that's unlikely the reason.

**Pull request closed without merging**
