### PR TITLE
Bugfix: issues#131 in Gitify

### PR DESCRIPTION
**Pull request by tyllo**
https://github.com/modmore/Gitify/issues/131

### CODE REVIEW

**Comment by Mark-H** [comment]
Hi @tyllo! Could you use the template from https://github.com/modxcms/revolution/blob/2.x/CONTRIBUTING.md#template-1 in the pull request, and explain a bit how this fix works?

**Comment by tyllo** [comment]
Google translate:
This patch fixes an oversight. When row [$url =$this->downloadUrl](https://github.com/tyllo/revolution/blob/2.x/core/model/modx/transport/modtransportprovider.class.php#L234) sought url, then the method [protected functiondownloadUrl](https://github.com/tyllo/revolution/blob/2.x/core/model/modx/transport/modtransportprovider.class.php#L321) "port" setting $ this->xpdo, because when you assign [$rest =$this->xpdo->getService('rest','rest.modRestClient');](https://github.com/tyllo/revolution/blob/2.x/core/model/modx/transport/modtransportprovider.class.php#L324) - Assigned to the link, and not copied to the variable $rest.
When downloading a single package, this error does not climbs, and for batch downloading - she climbs.

Russian:
Этот патч исправляет оплошность. Когда в строке [$url = $this->downloadUrl](https://github.com/tyllo/revolution/blob/2.x/core/model/modx/transport/modtransportprovider.class.php#L234) ищется url, то в методе  [protected function downloadUrl](https://github.com/tyllo/revolution/blob/2.x/core/model/modx/transport/modtransportprovider.class.php#L321) "портится" настройка $this->xpdo, потому что при присваивании [$rest = $this->xpdo->getService('rest','rest.modRestClient');](https://github.com/tyllo/revolution/blob/2.x/core/model/modx/transport/modtransportprovider.class.php#L324) - присваивается по ссылке, а не копируется в переменную $rest.
При единичном скачивании пакета эта ошибка не вылазит, а при пакетном скачивании - она вылазит.

**Comment by graphiclunarkid** [comment]
I've tested this pull request on my Vagrant image and it fixes issue modmore/Gitify#131 for me :smile_cat:

**Comment by OptimusCrime** [comment]
Any reason this is not merged yet?

**Comment by graphiclunarkid** [comment]
Just checking in to see if there's any more testing I can do, or help I can give, to get this fix merged?

**Comment by hansek** [comment]
I got into same troubles with latest **Gitify** and **MODX 2.4.2-pl**, after this fix `install:package --all` working fine again.

**Comment by hansek** [comment]
Latest Gitify works fine with **MODX 2.3.6-pl**, there is no need for this fix.

**Comment by pixelchutes** [comment]
Hi @tyllo! Any update on this? Just want to understand the how/why behind the solution.

*(See @Mark-H's request above about updating to use the [PR contribution template](https://github.com/modxcms/revolution/blob/2.x/CONTRIBUTING.md#template-1))*

**Comment by Mark-H** [comment]
It does fix the issue we've been seeing with Gitify's batch package install, I've since tested this on several sites.

I think @tyllo might not speak a lot of English and after a bit more digging, I understand what this is doing as well, so if you'd allow me (as the developer responsible for Gitify :P), here's the template and description of what this does: 

### What does it do
Ensures the responseType is set correctly on the rest service. In the downloadUrl method of the provider object, the responseType is being set to `text`, as that request to the actual transport provider does not return XML (like all other requests), but a simple string as download url. To anticipate that, the responseType on the rest service is being set to `text` before the request is triggered (line 326/327). 

The bug starts happening when multiple packages are installed in a single request (through `Gitify package:install --all`), as the responseType is not set back to its default value of xml on the service. (Only a single rest service instances is used throughout the request thanks to the getService calls). This causes issues on subsequent calls to the provider to list or download a certain package. 

### Why is it needed

This pull request makes sure the responseType is set back to its original value after the call to get the download url with responseType=text. That way batch downloads/installs with tools like Gitify work again as they did in 2.3.x. 

### Related issue(s)/PR(s)
modmore/Gitify#131

On a final note, I believe this should probably target 2.4.3 instead of 2.5 as it's a bug fix for behaviour that was inadvertently broken in 2.4.0 @rtripault.

**Comment by pixelchutes** [comment]
Thanks Mark. I'd agree, definitely `2.4.x`. Is there a signed release?

**Comment by hansek** [comment]
Thanks guys, hope this will be released in next 2.4.x release ;)

**Comment by rtripault** [comment]
Right, this is indeed a fix for commit cb48cc3c2a4c8cfe67b31e81ad29d0fd39bccd3e.
Sorry for not checking

**Comment by Mark-H** [comment]
@pixelchutes If by signed release you mean the CLA, then I'm not sure..

@tyllo Have you ever signed the MODX CLA? If not, can you please do so at modx.com/cla and post here when you did that?

**Comment by tyllo** [comment]
I am not registered to MODX CLA, I'm bad at writing English. If is still actual, you can take my commit themselves to recycle, I will not be offended.

**Comment by Mark-H** [comment]
Hi @tyllo, this pull request is still actual, thanks :)

If you could just go to http://modx.com/cla and fill in the form, that will allow us to merge it and include it in the next release. The CLA gives the MODX project the legal right to the code you provide, so it can be licensed as GPL.

**Comment by tyllo** [comment]
done

**Comment by pixelchutes** [comment]
Merged via d1f05558c26a04b892169b211239947f6ff2e293

**Comment by hansek** [comment]
:clap:

**Comment by graphiclunarkid** [comment]
:heart:

**Pull request closed without merging**
