### PR TITLE
Fixed context sub-menu not appearing in resource tree

### PR DESCRIPTION
**Pull request by muzzwood**
### What does it do?
Changed array of core resource class names to use single slashes rather than double.

### Why is it needed?
After a previous PR #15424 , the context sub-menu was no longer being triggered.

### How to test
Use the resource tree context menu (right-click) to create a resource.

### Related issue(s)/PR(s)
Issue: #15590
Previous PR: #15424

### CODE REVIEW

**Comment by ghost** [comment]
Still not working

Edited line in the file
Cleared browser cache
Cleared core/cache

**Comment by muzzwood** [comment]
Hi @sottwell, this change would only be in the uncompressed js assets. It's possible your manager is using the compressed versions. Could you check the system setting?

**Comment by ghost** [comment]
That was it. Works fine now. Thank you!

**Review by Ibochkarev — APPROVED** [review]
It worked!

**Review by Ruslan-Aleev — APPROVED** [review]

**Pull request merged**
