### PR TITLE
Improve the processor permission response error message

### PR DESCRIPTION
**Pull request by Jako**
### What does it do?
- Add a lexicon entry for the processor permission message.
- Output the permission and the processor action in the message (Moving the permission class property to the modProcessor class was needed).
- Show the new error message in the MODx.combo.ComboBox loadexception

### Why is it needed?
It is not easy to detect, which permission is needed for a combobox processor permission error.

Before:

Bildschirmfoto 2021-02-20 um 21 13 52

After:

Bildschirmfoto 2021-02-20 um 21 14 42

### How to test
Add the following code to i.e. core/model/modx/processors/workspace/namespace/getlist.class.php and open the MODX system settings.

```
    public function checkPermissions() {
        return false;
    }
```

In a grid, the message is shown in the empty grid content.

### Related issue(s)/PR(s)
#13243, #12568, #15344

### CODE REVIEW

**Comment by Ruslan-Aleev** [comment]
Also related with - https://github.com/modxcms/revolution/issues/15344
Powerful PR! Will there be no problem with encoding in json here? As in the issue above.

**Comment by Jako** [comment]
Yes, the JSON will be decoded and the encoded unicode chars will be transformed to readable text.

**Comment by Mark-H** [comment]
I don't typically want to engage in nitpicking textual stuff, but would "Permission 'foo bar' is **required** for 'action'" be better English? 

I think "permission denied 'foo' for 'bar'" may give users the impression they **have** permission 'foo' but that it's not a valid role of sorts.

**Review by Ruslan-Aleev — APPROVED** [review]
Thanks for the PR! Everything works visually.

res_changes
template_views

**Comment by Jako** [comment]
@Mark-H You are right. Thanks!

**Review by theboxer — APPROVED** [review]

**Pull request merged**
