### PR TITLE
Remove Unused Window Config for Lexicons Grid

### PR DESCRIPTION
**Pull request by smg6511**
Came across this when working on another PR. There is no export Lexicons feature, nor was there one in 2.x. 

### How to test
No testing to do per-se. Just verify that there is, in fact, no implementation that removing this code would break.

### Related issue(s)/PR(s)
None

### CODE REVIEW

**Comment by Mark-H** [comment]
Huh, that's funny. There is lexicon entry for `lexicon_export_desc` and a window definition, but no processor or any usages I can find either. 

Looks like it was removed [in 2.1.0](https://github.com/modxcms/revolution/commit/05551131788a8cd6ef343bdc951aea8223b98a4e#diff-67b383681ba332c789685cab38f07a646ad972d1c5cc725e4c8ab18d6ef8bcbc), just 12 years ago 😂

**Review by Mark-H — APPROVED** [review]

**Comment by JoshuaLuckers** [comment]
It's a feature that's been requested a few times, wouldn't it be a better idea to bring back this feature?

**Comment by smg6511** [comment]
@JoshuaLuckers - While it might be a nice feature for someone to redevelop, it's been an awful long time since it's been around. The code being deleted is just stray at this point and shouldn't been in the production codebase, right?

**Comment by JoshuaLuckers** [comment]
> @JoshuaLuckers - The code being deleted is just stray at this point and shouldn't been in the production codebase, right?

You're right!

**Pull request merged**
