### PR TITLE
Convert usergroup tree to usergroup grid in ACL page

### PR DESCRIPTION
**Pull request by goldsky**
Convert usergroup tree to tabbed usergroup grids in ACL page to handle huge amount of groups/members.

From this:
modx-tree-usergroup

To this:
modx-grid-user-group-groups

Clicking the row will open closable tab which contains the members of the selected group.
anonymous-group

### CODE REVIEW

**Comment by Mark-H** [comment]
Hey @goldsky - this is super cool and seems to work great. Would love to get this merged in for 2.4.

 The only problem I'm seeing is with the toggle.. when toggled once there's no way to bring the panel back into view permanently? Clicking the bar on the left will show it again, but it hides automatically again when moving the mouse out of the panel.

Thoughts on simply disabling the collapse (manager/assets/modext/widgets/security/modx.panel.groups.roles.js:68) or other solutions?

**Comment by Mark-H** [comment]
Oh and I'm also getting an error on this last line:

```` js
    ,fixPanelHeight: function() {
        // fixing border layout's height regarding to tree panel's
        var treeEl = Ext.getCmp('modx-tree-usergroup').getEl();
        var treeH = treeEl.getHeight();
        var tb = treeEl.up('.main-wrapper').down('.x-panel-header');
        var xHeight = tb.getHeight() + 20; // 10px x 2 padding
````

Cannot read property 'getHeight' of null

**Comment by goldsky** [comment]
@Mark-H ,
Collapsible works, so pls **don't disable it**.
https://www.screenr.com/HhzN
It is needed for small screen.

**Comment by goldsky** [comment]
Is there a chance someone can push this forward to the next release?

Unavailability of this feature down voting MODX to handle membership-center web site/application.
This keeps blocking me to persuade people to convert sites with huge subscribers.

**Comment by Mark-H** [comment]
I see in your screencast that there's a button in the top left that I missed during my testing to bring the panel back in view permanently. No objections from me. :+1:

**Comment by OptimusCrime** [comment]
Much better. +1 for keeping the tree.

**Comment by TheBoxer** [comment]
Looks cool :)

I would be for adding `cls:'main-wrapper'` to to
```js
{
    region: 'center'
    ,id: 'modx-usergroup-users'
    ,layout: 'fit'
}
```

Which will add nice padding around the grid with users.

Also it would be nice to improve the collapsible icon, which is almost invisible in the collapsed state, maybe do it similar as the icon for resource/elements/files tree?

**Comment by goldsky** [comment]
as requested, add padding (`.main-wrapper`) and fix collapse mode

**Pull request merged**
