### PR TITLE
Update modresource.class.php

### PR DESCRIPTION
**Pull request by vgrish**
- fix error

### What does it do?
Describe the technical changes you did.

### Why is it needed?
Describe the issue you are solving.

### Related issue(s)/PR(s)
Let us know if this is related to any issue/pull request (see https://github.com/blog/1506-closing-issues-via-pull-requests)

### CODE REVIEW

**Comment by OptimusCrime** [comment]
@vgrish Please provide more information. What issue are you solving?

**Comment by vgrish** [comment]
`Fatal error: Uncaught Error: Call to a member function invokeEvent() on null in modresource.class.php:1362`

**Comment by OptimusCrime** [comment]
@vgrish I don't see the problem here. How can I recreate it?

**Comment by vgrish** [comment]
There is no modx object in the class of the modresource.class.php

**Comment by bezumkin** [comment]
@OptimusCrime As I see, `modx` property is empty when I load object with getOne()
```
if ($child = $modx->getObject('modResource', 294)) {
    if ($parent = $child->getOne('Parent')) {
        $res->clearCache();
    }
}
```
Fatal error
```
2017/11/06 13:50:43 [error] 2753#2753: *892336 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function invokeEvent() on null in /home/s11000/www/core/model/modx/modresource.class.php:1362
Stack trace:
#0 /home/s11000/www/test.php(8): modResource->clearCache()
#1 {main}
  thrown in /home/s11000/www/core/model/modx/modresource.class.php on line 1362" while reading response header from upstream, client: 92.50.223.33, server: s11000.h9.modhost.pro, request: "GET /test.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:21000", host: "s11000.h9.modhost.pro"
2017/11/06 13:51:18 [error] 2753#2753: *892336 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function clearCache() on null in /home/s11000/www/test.php:8
Stack trace:
#0 {main}
  thrown in /home/s11000/www/test.php on line 8" while reading response header from upstream, client: 92.50.223.33, server: s11000.h9.modhost.pro, request: "GET /test.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:21000", host: "s11000.h9.modhost.pro"
```

This is a critical error, that must be fixes asap.

**Comment by Jako** [comment]
@vgrish Is it that difficult to answer the questions in the initial pull request template, so we could understand the issue directly without asking questions? If yes, what could we do to make it easier?

**Comment by opengeek** [comment]
This is a result of merging #13590 — @OptimusCrime this was a PR you submitted. I'm a little disappointed in the lack of attention to detail and testing in this, including by me when merging it. And also in the fact that no one caught this until after release. I'm going to suggest that we require either unit tests or testing plans with all future PRs so we can avoid these kinds of critical problems.

**Comment by opengeek** [comment]
This was merged in an experimental way, but apparently manually squashing does not update pull requests as merged. I will avoid doing it this way moving forward.

**Comment by OptimusCrime** [comment]
@opengeek Yeah. I see it. It is not good. I should have specified that my implementation was simply recreated from a butched PR and that I did not test it properly. I get your point about unit tests. As soon as I get my side project finished, I will finish my branch for a better PHPUnit setup. It will go in the 3.x branch when it is finished. Hopefully that will make it easier to test some of this.

**Pull request closed without merging**
