### PR TITLE
Fix tab tracking error in package manager

### LINKED ISSUE #16357: MODX 3.0.3 Changelog, Readme, License not visible when installing packages
### Summary
In MODX 3.0.3, when you install a package in the package manager, the information for _Changelog_, _Readme_ and _License_ is not visible.

Installing the same package in MODX 3.0.2 shows the information.

Package Management MODX Revolution

### Environment
MODX 3.0.3

### PR DESCRIPTION
**Pull request by smg6511**
### What does it do?
Makes conditionals more precise and error-proof in `beforetabchange` listener.

### Why is it needed?
A new listener method added in #16089 was interfering with package installation and upgrades. Type errors were preventing these processes from completing.

### How to test
Install one new Extra and update one Extra to verify no errors occur and installations are successful.

### Related issue(s)/PR(s)
Resolves #16357

### CODE REVIEW

**Review by JoshuaLuckers — APPROVED** [review]

**Review by Ibochkarev — APPROVED** [review]

**Comment by rthrash** [comment]
This pull request has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/3-0-3-form-customization-doesnt-work-after-upgrade/6309/4

**Review by Mark-H — APPROVED** [review]

**Comment by rthrash** [comment]
This pull request has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/is-there-a-way-to-use-md-files-in-package-builder-setpackageattributes/6342/2

**Comment by rthrash** [comment]
This pull request has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/modx-3-0-3-pl-package-manager-package-information-missing/6365/2

**Comment by rthrash** [comment]
This pull request has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/manager-form-customisation/6589/5

**Comment by modxcommunity** [comment]
This pull request has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/form-customisation-working-only-partially/7199/11

**Pull request merged**
