### PR TITLE
Fix uries checkin for creating unpublished resources

### PR DESCRIPTION
**Pull request by Fi1osof**
http://joxi.ru/nAyz3VMFXwgKer

### CODE REVIEW

**Comment by sottwell** [comment]
https://github.com/modxcms/revolution/blob/2.x/CONTRIBUTING.md

**Comment by Fi1osof** [comment]
@sottwell 
### Summary
If create unpublished resource, uri not checks for unique.

### Step to reproduce
Create two o more unpublished resources with same alias/uri/

**Comment by Mark-H** [comment]
Thanks @Fi1osof, merged into 2.x for inclusion in 2.5.0-rc1.

**Comment by Fi1osof** [comment]
@Mark-H, not at all!

**Pull request merged**
