### PR TITLE
[^p^] tag output fix on locales with comma as decimal point

### LINKED ISSUE #12474: Wrong value of [^p^] tag - almost always "0,0000 s"
### Summary
Tag [^p^] produces wrong value.

### Step to reproduce
Add this code to the bottom of a page template:
MySQL: [^qt^] ([^q^] queries) PHP: [^p^] Total: [^t^]

### Observed behavior
MODx prints "0,0000 s" instead of [^p^] tag.

### Expected behavior
MODx should print some value other than 0,0000 s

### Environment
MODX 2.3.3-pl, phpinfo: http://psychoid.ru/phpinfo.php

### How to fix
In file /core/model/modx/modresponse.class.php replace lines 107 - 113 with these:
            $totalTime= (microtime(true) - $this->modx->startTime);
            $queryTime= $this->modx->queryTime;
            $queryTime= sprintf("%2.4f s", $queryTime);
            $queries= isset ($this->modx->executedQueries) ? $this->modx->executedQueries : 0;
            $totalTime= sprintf("%2.4f s", $totalTime);
            $phpTime= $totalTime - $queryTime;
            $phpTime= sprintf("%2.4f s", $phpTime);

### PR DESCRIPTION
**Pull request by sitex-pro**
### What does it do ?

The order of certain lines in core/model/modx/modresponse.class.php changed in order to avoid subtraction between float and string variables.
### Why is it needed ?

Without these changes [^p^] tag produced wrong output on locales which use comma as decimal point (For example, 'ru_RU.utf8')
### Related issue(s)/PR(s)

fixes #12474

### CODE REVIEW

**Comment by Mark-H** [comment]
Hi @sitex-pro, thanks for the useful contribution :) In order to merge it in, I need to make sure you have signed the CLA. Can you please sign it at http://develop.modx.com/contribute/cla/ and let me know?

**Comment by sitex-pro** [comment]
Hi @Mark-H , signed !

**Comment by Mark-H** [comment]
Thanks @sitex-pro, merged in for 2.3.6!

**Comment by sitex-pro** [comment]
@Mark-H, thank you!

**Pull request merged**
