### PR TITLE
MySQL Uberbar fixed to use fulltext indexes

### PR DESCRIPTION
**Pull request by the-dunnock**
Also resolves Ryan's feature request : https://github.com/modxcms/revolution/issues/11117

### CODE REVIEW

**Comment by amdbuilder** [comment]
It might be worth noting that MySQL 5.5 will be EOL December 31, 2015 - at least from a cPanel perspective.  I do know some hosts are transitioning to MySQL 5.6 / MariaDB 10 before that time for performance improvements.

**Comment by Mark-H** [comment]
So what should we do with this PR? Get back to it in a few years?

**Comment by pixelchutes** [comment]
Great points re: MySQL 5.5 EOL. Is it something worth waiting for? I'd hate to see this get neglected unnecessarily, as it probably makes a great candidate for breaking change release (2.4?), or whenever the minimum MySQL version officially gets bumped next.

Unless somebody knows a way to make it conditional on MySQL version *(didn't see how to achieve this per the associated map files)*, I worry about the potential impact of the FULLTEXT. Does anyone know what would happen to MySQL 5.5 / InnoDB users with this PR? Would it degrade gracefully and still be useable, minus the new indices?

I also wonder if this may be related to #12515, and whether or not it would impact the efforts there *(or help improve it.)*

**Comment by OptimusCrime** [comment]
> It might be worth noting that MySQL 5.5 will be EOL December 31, 2015 - at least from a cPanel perspective. I do know some hosts are transitioning to MySQL 5.6 / MariaDB 10 before that time for performance improvements.

MySQL 5.5 EOL has passed. Any reason not to merge this now?

**Comment by rtripault** [comment]
I guess the main reason for not merging this is Backward Compatibility.
We should be able to do so for the 3.x branch, so assigning to this milestone

**Comment by OptimusCrime** [comment]
I was not aware that this broke BC.

**Comment by rtripault** [comment]
Sorry, i may have not used the most appropriate term... my point being (from my understanding), merging this PR means rising the MySQL minimum supported version, which could be considered as a breaking change

**Comment by OptimusCrime** [comment]
Ah, then we agree. However, does anyone know what happens if you tried to run this on a 5.5 version? Would the query fail? Is there any way to check if the engine has FT and enable it if it has? That way we could keep the old minimum supported version and at the same time give this functionality too.

**Comment by pixelchutes** [comment]
@OptimusCrime It's my understanding that FULLTEXT indices cannot be created for that version/engine combo. I presume this would result in a MySQL error and a failed install. That said, I have not personally tried it against this PR w/ MySQL 5.5 + InnoDB.

To your point, it would be good to have someone verify the behavior here. Does it fail? Is it "fatal" or is the index simply not created, with the system still functional (only less performant) on MySQL < 5.6?

I'd love to see this support merged one way or another. Is [MySQL 4.1.20](https://develop.modx.com/develop/revolution/requirements/) really the current minimum database requiremed?

**Comment by Mark-H** [comment]
"A few years later", this is once again relevant per #13462. Given the conflicts in this PR and the required minimum version bump, I think we should close it and look towards a fix in 3.0 or after #13462 has been resolved.

**Comment by Mark-H** [comment]
Closing as proposed.

**Pull request closed without merging**
