### PR TITLE
Add guard-clause to clearDirty method

### PR DESCRIPTION
**Pull request by sebastian-marinescu**
### What does it do?
This makes sure the JS doesn't throw an error in the case that the items-object is an array, just like in https://github.com/modxcms/revolution/pull/16404 for 3.x

### Why is it needed?
When using ExtJS to create components of the xtype: 'radiogroup' to be used in CMPs inside a form,
this function gets called and tries to iterate over it's items array with a method that doesn't exist.

This PR isn't changing the way forms or the clearDirty-method are handled, it just assures no error is thrown when using radiogroup-components.

### Related issue(s)/PR(s)
Resolves https://github.com/modmore/ClientConfig/issues/202
Resolves https://github.com/modmore/ClientConfig/pull/176
Resolves https://github.com/modmore/ClientConfig/issues/143

### CODE REVIEW

**Comment by sebastian-marinescu** [comment]
@opengeek @Mark-H 

Hi guys, can we also tag/label this for the [v2.8.6-milestone](https://github.com/modxcms/revolution/milestone/104), please?

I'd appreciate it ❤️

**Comment by sebastian-marinescu** [comment]
Thank you _very_ much @Ibochkarev

**Review by smg6511 — APPROVED** [review]

**Review by theboxer — DISMISSED** [review]
👍

**Review by Mark-H — DISMISSED** [review]

**Comment by opengeek** [comment]
This change is currently breaking the grunt build with the following error:

```
Running "uglify:jsgrps" (uglify) task
JS_Parse_Error [SyntaxError]: Unexpected token: punc «.»
    at JS_Parse_Error.get (eval at <anonymous> (/Users/opengeek/www/revo-2.x/_build/templates/default/node_modules/uglify-js/tools/node.js:18:1), <anonymous>:71:23)
    at formatError (internal/util/inspect.js:1149:38)
    at formatRaw (internal/util/inspect.js:919:14)
    at formatValue (internal/util/inspect.js:774:10)
    at inspect (internal/util/inspect.js:319:10)
    at formatWithOptionsInternal (internal/util/inspect.js:1979:40)
    at formatWithOptions (internal/util/inspect.js:1861:10)
    at console.value (internal/console/constructor.js:328:14)
    at console.log (internal/console/constructor.js:364:61)
    at /Users/opengeek/www/revo-2.x/_build/templates/default/node_modules/grunt-contrib-uglify/tasks/uglify.js:144:17 {
  filename: 'util/utilities.js',
  line: 85,
  col: 22,
  pos: 2432
}
```

**Comment by opengeek** [comment]
I'd really like to move forward on this. What needs to be done?

**Comment by smg6511** [comment]
> I'd really like to move forward on this. What needs to be done?

Hey Jason -- working on the build routine for 2.x to bring it in line with 3.x (will solve these problems that are cropping up) ... should be good in the next day or two.

**Pull request merged**
