### PR TITLE
Anonymous username as System Setting

### PR DESCRIPTION
**Pull request by ghost**
Changed the hard-coded (anonymous) username to take a System Setting named 'default_username' in the 'session' area, and added the setting to the build data script.

### CODE REVIEW

**Comment by TheBoxer** [comment]
@sottwell Why it's called `default_username`, when it's used for setting username for anonymous user?
Also there is missing english translation for that setting.

**Comment by sottwell** [comment]
Because it is the default username for an unauthenticated user. At least that was my reasoning. However, feel free to call it anything you like. Or just cancel it and drop the whole thing if you don't like the idea.

**Comment by sottwell** [comment]
What area should this be in? I was thinking session, but now I think it should be in authentication.

**Comment by TheBoxer** [comment]
Thanks for clarification. 
Merged to develop.

**Comment by sottwell** [comment]
I'll try to do it better next time.

**Pull request closed without merging**
